Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [2]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [3]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULIgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULImidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULImidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULImidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/bundesliga/BULImidfielderPASSING.csv")

In [4]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [5]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name               0
Team               0
Tackles            0
Clearances         0
Interceptions      0
aerialsWon         0
Blocks             0
Mins               0
duelsWon           0
unnamed          100
dtype: int64

In [6]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,0.0
mean,24.040000,60.60000,16.010000,27.470000,2.290000,1312.080000,67.070000,NaN
std,19.171696,54.92842,13.812229,28.851923,2.701646,941.243468,51.798806,NaN
min,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,8.000000,10.50000,4.000000,4.750000,0.000000,280.000000,12.750000,NaN
50%,22.000000,50.00000,13.000000,16.000000,1.000000,1388.000000,65.500000,NaN
75%,36.250000,91.75000,25.000000,44.500000,3.250000,2149.500000,109.250000,NaN
max,79.000000,231.00000,55.000000,107.000000,13.000000,2970.000000,182.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [7]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within 2BULIcomplete.csv we can see the final id is 169.

In [8]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 170)
dfDdef["ID"] = (dfDdef.index + 170)
dfDatt["ID"] = (dfDatt.index + 170)
dfDpas["ID"] = (dfDpas.index + 170) #should end at id no 269
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 314
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 352
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 465
dfMdft.head(300) #to check final id number

            Name                 Team  App  Mins   ID
0    T. Chandler  Eintracht Frankfurt   10    27  353
1     C. Trimmel   1. FC Union Berlin   32  1743  354
2      N. Höfler          SC Freiburg   34   787  355
3       M. Götze  Eintracht Frankfurt   28  1546  356
4       K. Kampl           RB Leipzig   28  1596  357
..           ...                  ...  ...   ...  ...
108  J. Manzambi          SC Freiburg   20   339  461
109   D. Gleiber      1. FSV Mainz 05    9     0  462
110     B. Touré       TSG Hoffenheim   14   618  463
111    N. Swider  Borussia M'gladbach    4     0  464
112      L. Karl    FC Bayern München    3     0  465

[113 rows x 5 columns]

#### Further Data Erasure

In [9]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [10]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [11]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [12]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/bundesliga/BULIdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/bundesliga/BULIforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/bundesliga/BULIgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/bundesliga/BULImidfielder.csv", index=None)

Master merge

In [13]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,K. Vogt,VfL Bochum 1848,22,1280,170,0,1.0,1,1,0.7884,NaN,0.2359,10,66,8,12,0,32,809,710,120,0,0,2,Defender,NaN
1,D. da Costa,1. FSV Mainz 05,32,2011,171,1,5.0,1,0,0.0987,0.099,1.2573,42,94,27,33,2,87,1142,905,204,22,1,10,Defender,NaN
2,A. Jung,SC Freiburg,33,1905,172,0,1.0,0,0,0.0411,0.041,0.4531,33,74,25,34,0,89,1492,1339,108,4,0,2,Defender,NaN
3,S. Bell,1. FSV Mainz 05,23,1438,173,1,12.0,4,0,0.7696,0.771,0.6541,22,107,28,84,3,117,713,564,135,0,1,5,Defender,NaN
4,C. Gamboa,VfL Bochum 1848,30,230,174,0,4.0,1,1,0.1615,0.161,0.3356,8,8,2,0,1,11,99,62,24,7,0,3,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,J. Manzambi,SC Freiburg,20,339,461,1,11.0,3,2,1.3145,1.324,0.5566,8,6,4,9,3,30,137,107,9,5,0,3,Midfielder,NaN
292,D. Gleiber,1. FSV Mainz 05,9,0,462,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
293,B. Touré,TSG Hoffenheim,14,618,463,3,19.0,5,0,1.3705,1.398,1.8206,12,0,3,12,5,39,158,114,8,24,2,13,Midfielder,NaN
294,N. Swider,Borussia M'gladbach,4,0,464,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
295,L. Karl,FC Bayern München,3,0,465,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [14]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,K. Vogt,VfL Bochum 1848,22,1280,170,0,1.0,1,1,0.7884,0.000,0.2359,10,66,8,12,0,32,809,710,120,0,0,2,Defender,0.0
1,D. da Costa,1. FSV Mainz 05,32,2011,171,1,5.0,1,0,0.0987,0.099,1.2573,42,94,27,33,2,87,1142,905,204,22,1,10,Defender,0.0
2,A. Jung,SC Freiburg,33,1905,172,0,1.0,0,0,0.0411,0.041,0.4531,33,74,25,34,0,89,1492,1339,108,4,0,2,Defender,0.0
3,S. Bell,1. FSV Mainz 05,23,1438,173,1,12.0,4,0,0.7696,0.771,0.6541,22,107,28,84,3,117,713,564,135,0,1,5,Defender,0.0
4,C. Gamboa,VfL Bochum 1848,30,230,174,0,4.0,1,1,0.1615,0.161,0.3356,8,8,2,0,1,11,99,62,24,7,0,3,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,B. Dárdai,VfL Wolfsburg,34,1312,456,1,11.0,1,1,1.0429,1.059,0.9677,24,26,12,11,5,53,431,352,35,10,2,11,Midfielder,0.0
287,L. Djuric,TSG Hoffenheim,1,0,457,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
288,T. Gomis,RB Leipzig,13,153,458,1,5.0,1,0,0.2504,0.251,0.5866,0,0,1,1,2,8,48,41,1,4,2,3,Midfielder,0.0
289,K. Wätjen,VfL Bochum 1848,11,14,459,0,0.0,0,0,0.0000,0.000,0.0000,0,2,0,0,0,1,8,3,0,0,0,0,Midfielder,0.0
290,C. Uzun,Eintracht Frankfurt,33,675,460,1,27.0,11,4,2.9988,3.000,1.1394,10,3,1,5,4,42,281,233,13,18,1,14,Midfielder,0.0

Moving "ID" and "Position" rows

In [15]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,170,Defender,K. Vogt,VfL Bochum 1848,22,1280,0,1.0,1,1,0.7884,0.000,0.2359,10,66,8,12,0,32,809,710,120,0,0,2,0.0
1,171,Defender,D. da Costa,1. FSV Mainz 05,32,2011,1,5.0,1,0,0.0987,0.099,1.2573,42,94,27,33,2,87,1142,905,204,22,1,10,0.0
2,172,Defender,A. Jung,SC Freiburg,33,1905,0,1.0,0,0,0.0411,0.041,0.4531,33,74,25,34,0,89,1492,1339,108,4,0,2,0.0
3,173,Defender,S. Bell,1. FSV Mainz 05,23,1438,1,12.0,4,0,0.7696,0.771,0.6541,22,107,28,84,3,117,713,564,135,0,1,5,0.0
4,174,Defender,C. Gamboa,VfL Bochum 1848,30,230,0,4.0,1,1,0.1615,0.161,0.3356,8,8,2,0,1,11,99,62,24,7,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,456,Midfielder,B. Dárdai,VfL Wolfsburg,34,1312,1,11.0,1,1,1.0429,1.059,0.9677,24,26,12,11,5,53,431,352,35,10,2,11,0.0
287,457,Midfielder,L. Djuric,TSG Hoffenheim,1,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
288,458,Midfielder,T. Gomis,RB Leipzig,13,153,1,5.0,1,0,0.2504,0.251,0.5866,0,0,1,1,2,8,48,41,1,4,2,3,0.0
289,459,Midfielder,K. Wätjen,VfL Bochum 1848,11,14,0,0.0,0,0,0.0000,0.000,0.0000,0,2,0,0,0,1,8,3,0,0,0,0,0.0
290,460,Midfielder,C. Uzun,Eintracht Frankfurt,33,675,1,27.0,11,4,2.9988,3.000,1.1394,10,3,1,5,4,42,281,233,13,18,1,14,0.0

Checking if expected stats exist

In [16]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000
mean,317.500000,23.476351,1255.152027,1.337838,15.290541,5.388514,1.885135,1.711086,1.596848,1.545924,19.726351,32.327703,10.935811,19.679054,4.263514,59.118243,611.415541,504.239865,72.422297,23.395270,2.449324,12.391892,4.432432
std,85.592056,10.558607,946.854504,2.148879,19.020329,8.032207,3.516592,2.948482,2.604291,2.002566,19.455890,40.635762,12.633528,25.912925,5.308594,53.716357,572.550766,505.677703,103.202388,39.072152,3.711293,15.687687,17.499312
min,170.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,243.750000,15.750000,297.500000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.072500,1.000000,4.000000,0.750000,2.750000,0.000000,8.750000,120.500000,95.500000,6.000000,0.000000,0.000000,1.000000,0.000000
50%,317.500000,28.000000,1289.000000,0.000000,9.000000,2.000000,1.000000,0.768650,0.732000,0.764900,14.000000,17.000000,6.000000,11.000000,2.000000,48.500000,479.500000,353.500000,37.500000,6.500000,1.000000,7.000000,0.000000
75%,391.250000,32.000000,2046.500000,2.000000,21.000000,7.000000,2.000000,1.812650,1.803000,2.186175,34.000000,45.250000,18.000000,24.250000,6.000000,99.250000,964.250000,770.250000,96.250000,25.000000,3.000000,19.000000,0.000000
max,465.000000,35.000000,3060.000000,15.000000,114.000000,54.000000,26.000000,22.901900,19.728000,12.509000,95.000000,231.000000,65.000000,169.000000,28.000000,222.000000,3425.000000,3183.000000,627.000000,217.000000,32.000000,93.000000,104.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [17]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,170,Defender,K. Vogt,VfL Bochum 1848,22,1280,0,1.0,1,1,0.7884,0.000,0.2359,10,66,8,12,0,32,809,710,120,0,0,2,0.0,0.070312,0.000000,1,0.070312,0.070312,0.070312,2.250000,56.882813,49.921875,8.437500,0.000000,0.000000,0.140625,0.703125,4.640625,0.562500,0.843750,0.000000,0.0,0.055434,0.000000,0.016587
1,171,Defender,D. da Costa,1. FSV Mainz 05,32,2011,1,5.0,1,0,0.0987,0.099,1.2573,42,94,27,33,2,87,1142,905,204,22,1,10,0.0,0.000000,0.044754,1,0.044754,0.223769,0.044754,3.893585,51.108901,40.502238,9.129786,0.984585,0.044754,0.447539,1.879662,4.206862,1.208354,1.476877,0.089508,0.0,0.004417,0.004431,0.056269
2,172,Defender,A. Jung,SC Freiburg,33,1905,0,1.0,0,0,0.0411,0.041,0.4531,33,74,25,34,0,89,1492,1339,108,4,0,2,0.0,0.000000,0.000000,0,0.000000,0.047244,0.000000,4.204724,70.488189,63.259843,5.102362,0.188976,0.000000,0.094488,1.559055,3.496063,1.181102,1.606299,0.000000,0.0,0.001942,0.001937,0.021406
3,173,Defender,S. Bell,1. FSV Mainz 05,23,1438,1,12.0,4,0,0.7696,0.771,0.6541,22,107,28,84,3,117,713,564,135,0,1,5,0.0,0.000000,0.062587,1,0.062587,0.751043,0.250348,7.322670,44.624478,35.299026,8.449235,0.000000,0.062587,0.312935,1.376912,6.696801,1.752434,5.257302,0.187761,0.0,0.048167,0.048255,0.040938
4,174,Defender,C. Gamboa,VfL Bochum 1848,30,230,0,4.0,1,1,0.1615,0.161,0.3356,8,8,2,0,1,11,99,62,24,7,0,3,0.0,0.391304,0.000000,1,0.391304,1.565217,0.391304,4.304348,38.739130,24.260870,9.391304,2.739130,0.000000,1.173913,3.130435,3.130435,0.782609,0.000000,0.391304,0.0,0.063196,0.063000,0.131322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,456,Midfielder,B. Dárdai,VfL Wolfsburg,34,1312,1,11.0,1,1,1.0429,1.059,0.9677,24,26,12,11,5,53,431,352,35,10,2,11,0.0,0.068598,0.068598,2,0.137195,0.754573,0.068598,3.635671,29.565549,24.146341,2.400915,0.685976,0.137195,0.754573,1.646341,1.783537,0.823171,0.754573,0.342988,0.0,0.071540,0.072645,0.066382
287,457,Midfielder,L. Djuric,TSG Hoffenheim,1,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,458,Midfielder,T. Gomis,RB Leipzig,13,153,1,5.0,1,0,0.2504,0.251,0.5866,0,0,1,1,2,8,48,41,1,4,2,3,0.0,0.000000,0.588235,1,0.588235,2.941176,0.588235,4.705882,28.235294,24.117647,0.588235,2.352941,1.176471,1.764706,0.000000,0.000000,0.588235,0.588235,1.176471,0.0,0.147294,0.147647,0.345059
289,459,Midfielder,K. Wätjen,VfL Bochum 1848,11,14,0,0.0,0,0,0.0000,0.000,0.0000,0,2,0,0,0,1,8,3,0,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,6.428571,51.428571,19.285714,0.000000,0.000000,0.000000,0.000000,0.000000,12.857143,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
290,460,Midfielder,C. Uzun,Eintracht Frankfurt,33,675,1,27.0,11,4,2.9988,3.000,1.1394,10,3,1,5,4,42,281,233,13,18,1,14,0.0,0.533333,0.133333,5,0.666667,3.600000,1.466667,5.600000,37.466667,31.066667,1.733333,2.400000,0.133333,1.866667,1.333333,0.400000,0.133333,0.666667,0.533333,0.0,0.399840,0.400000,0.151920

Removing NaN again and fixing decimal places

In [18]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,170,Defender,K. Vogt,VfL Bochum 1848,22,1280,0,1.0,1,1,0.79,0.00,0.24,10,66,8,12,0,32,809,710,120,0,0,2,0.0,0.07,0.00,1,0.07,0.07,0.07,2.25,56.88,49.92,8.44,0.00,0.00,0.14,0.70,4.64,0.56,0.84,0.00,0.0,0.06,0.00,0.02
1,171,Defender,D. da Costa,1. FSV Mainz 05,32,2011,1,5.0,1,0,0.10,0.10,1.26,42,94,27,33,2,87,1142,905,204,22,1,10,0.0,0.00,0.04,1,0.04,0.22,0.04,3.89,51.11,40.50,9.13,0.98,0.04,0.45,1.88,4.21,1.21,1.48,0.09,0.0,0.00,0.00,0.06
2,172,Defender,A. Jung,SC Freiburg,33,1905,0,1.0,0,0,0.04,0.04,0.45,33,74,25,34,0,89,1492,1339,108,4,0,2,0.0,0.00,0.00,0,0.00,0.05,0.00,4.20,70.49,63.26,5.10,0.19,0.00,0.09,1.56,3.50,1.18,1.61,0.00,0.0,0.00,0.00,0.02
3,173,Defender,S. Bell,1. FSV Mainz 05,23,1438,1,12.0,4,0,0.77,0.77,0.65,22,107,28,84,3,117,713,564,135,0,1,5,0.0,0.00,0.06,1,0.06,0.75,0.25,7.32,44.62,35.30,8.45,0.00,0.06,0.31,1.38,6.70,1.75,5.26,0.19,0.0,0.05,0.05,0.04
4,174,Defender,C. Gamboa,VfL Bochum 1848,30,230,0,4.0,1,1,0.16,0.16,0.34,8,8,2,0,1,11,99,62,24,7,0,3,0.0,0.39,0.00,1,0.39,1.57,0.39,4.30,38.74,24.26,9.39,2.74,0.00,1.17,3.13,3.13,0.78,0.00,0.39,0.0,0.06,0.06,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,456,Midfielder,B. Dárdai,VfL Wolfsburg,34,1312,1,11.0,1,1,1.04,1.06,0.97,24,26,12,11,5,53,431,352,35,10,2,11,0.0,0.07,0.07,2,0.14,0.75,0.07,3.64,29.57,24.15,2.40,0.69,0.14,0.75,1.65,1.78,0.82,0.75,0.34,0.0,0.07,0.07,0.07
287,457,Midfielder,L. Djuric,TSG Hoffenheim,1,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
288,458,Midfielder,T. Gomis,RB Leipzig,13,153,1,5.0,1,0,0.25,0.25,0.59,0,0,1,1,2,8,48,41,1,4,2,3,0.0,0.00,0.59,1,0.59,2.94,0.59,4.71,28.24,24.12,0.59,2.35,1.18,1.76,0.00,0.00,0.59,0.59,1.18,0.0,0.15,0.15,0.35
289,459,Midfielder,K. Wätjen,VfL Bochum 1848,11,14,0,0.0,0,0,0.00,0.00,0.00,0,2,0,0,0,1,8,3,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,6.43,51.43,19.29,0.00,0.00,0.00,0.00,0.00,12.86,0.00,0.00,0.00,0.0,0.00,0.00,0.00
290,460,Midfielder,C. Uzun,Eintracht Frankfurt,33,675,1,27.0,11,4,3.00,3.00,1.14,10,3,1,5,4,42,281,233,13,18,1,14,0.0,0.53,0.13,5,0.67,3.60,1.47,5.60,37.47,31.07,1.73,2.40,0.13,1.87,1.33,0.40,0.13,0.67,0.53,0.0,0.40,0.40,0.15

In [19]:
finalData.dtypes

ID                          int64
Position                   object
Name                       object
Team                       object
App                         int64
Mins                        int64
Assists                     int64
Shots                     float64
shotsOnTarget               int64
Goals                       int64
xG                        float64
npxG                      float64
xA                        float64
Tackles                     int64
Clearances                  int64
Interceptions               int64
aerialsWon                  int64
Blocks                      int64
duelsWon                    int64
Passes                      int64
accuratePasses              int64
longBalls                   int64
Crosses                     int64
bigChancesCreated           int64
keyPasses                   int64
Saves                     float64
goalsPer90                float64
assistsPer90              float64
g+a                         int64
g+aPer90                  float64
shotsPer90                float64
shotsOnTargetPer90        float64
duelsWonPer90             float64
passesPer90               float64
accuratePassesPer90       float64
longBallsPer90            float64
crossesPer90              float64
bigChancesCreatedPer90    float64
keyPassesPer90            float64
tacklesPer90              float64
clearancesPer90           float64
interceptionsPer90        float64
aerialsWonPer90           float64
blocksPer90               float64
savesPer90                float64
xgPer90                   float64
npxgPer90                 float64
xaPer90                   float64
dtype: object

Adding and moving "League" column

In [20]:
#label
leagueLabel = "Bundesliga"

#adding label to df
finalData["League"] = leagueLabel

In [21]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,170,Defender,Bundesliga,K. Vogt,VfL Bochum 1848,22,1280,0,1.0,1,1,0.79,0.00,0.24,10,66,8,12,0,32,809,710,120,0,0,2,0.0,0.07,0.00,1,0.07,0.07,0.07,2.25,56.88,49.92,8.44,0.00,0.00,0.14,0.70,4.64,0.56,0.84,0.00,0.0,0.06,0.00,0.02
1,171,Defender,Bundesliga,D. da Costa,1. FSV Mainz 05,32,2011,1,5.0,1,0,0.10,0.10,1.26,42,94,27,33,2,87,1142,905,204,22,1,10,0.0,0.00,0.04,1,0.04,0.22,0.04,3.89,51.11,40.50,9.13,0.98,0.04,0.45,1.88,4.21,1.21,1.48,0.09,0.0,0.00,0.00,0.06
2,172,Defender,Bundesliga,A. Jung,SC Freiburg,33,1905,0,1.0,0,0,0.04,0.04,0.45,33,74,25,34,0,89,1492,1339,108,4,0,2,0.0,0.00,0.00,0,0.00,0.05,0.00,4.20,70.49,63.26,5.10,0.19,0.00,0.09,1.56,3.50,1.18,1.61,0.00,0.0,0.00,0.00,0.02
3,173,Defender,Bundesliga,S. Bell,1. FSV Mainz 05,23,1438,1,12.0,4,0,0.77,0.77,0.65,22,107,28,84,3,117,713,564,135,0,1,5,0.0,0.00,0.06,1,0.06,0.75,0.25,7.32,44.62,35.30,8.45,0.00,0.06,0.31,1.38,6.70,1.75,5.26,0.19,0.0,0.05,0.05,0.04
4,174,Defender,Bundesliga,C. Gamboa,VfL Bochum 1848,30,230,0,4.0,1,1,0.16,0.16,0.34,8,8,2,0,1,11,99,62,24,7,0,3,0.0,0.39,0.00,1,0.39,1.57,0.39,4.30,38.74,24.26,9.39,2.74,0.00,1.17,3.13,3.13,0.78,0.00,0.39,0.0,0.06,0.06,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,456,Midfielder,Bundesliga,B. Dárdai,VfL Wolfsburg,34,1312,1,11.0,1,1,1.04,1.06,0.97,24,26,12,11,5,53,431,352,35,10,2,11,0.0,0.07,0.07,2,0.14,0.75,0.07,3.64,29.57,24.15,2.40,0.69,0.14,0.75,1.65,1.78,0.82,0.75,0.34,0.0,0.07,0.07,0.07
287,457,Midfielder,Bundesliga,L. Djuric,TSG Hoffenheim,1,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
288,458,Midfielder,Bundesliga,T. Gomis,RB Leipzig,13,153,1,5.0,1,0,0.25,0.25,0.59,0,0,1,1,2,8,48,41,1,4,2,3,0.0,0.00,0.59,1,0.59,2.94,0.59,4.71,28.24,24.12,0.59,2.35,1.18,1.76,0.00,0.00,0.59,0.59,1.18,0.0,0.15,0.15,0.35
289,459,Midfielder,Bundesliga,K. Wätjen,VfL Bochum 1848,11,14,0,0.0,0,0,0.00,0.00,0.00,0,2,0,0,0,1,8,3,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,6.43,51.43,19.29,0.00,0.00,0.00,0.00,0.00,12.86,0.00,0.00,0.00,0.0,0.00,0.00,0.00
290,460,Midfielder,Bundesliga,C. Uzun,Eintracht Frankfurt,33,675,1,27.0,11,4,3.00,3.00,1.14,10,3,1,5,4,42,281,233,13,18,1,14,0.0,0.53,0.13,5,0.67,3.60,1.47,5.60,37.47,31.07,1.73,2.40,0.13,1.87,1.33,0.40,0.13,0.67,0.53,0.0,0.40,0.40,0.15

In [22]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/BULIcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- BULIcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- BULIcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [23]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [24]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [25]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000
mean,314.792829,26.597610,1478.529880,1.577689,18.011952,6.350598,2.223108,2.015817,1.881315,1.821474,23.243028,38.067729,12.868526,23.163347,5.015936,69.597610,720.239044,594.003984,85.382470,27.573705,2.884462,14.601594,5.227092,0.137171,0.096056,3.800797,0.233785,1.182669,0.398606,4.268725,42.240837,34.621355,4.964781,1.632072,0.186972,0.880159,1.415020,2.223904,0.752988,1.391713,0.349562,0.309920,0.125976,0.119124,0.109562
std,85.967836,7.824157,853.422743,2.251431,19.441087,8.367353,3.719949,3.105389,2.732877,2.056533,19.103735,41.602973,12.791038,26.683950,5.431735,51.760385,555.514017,498.511372,107.044725,41.062264,3.872802,16.066133,18.899106,0.196781,0.126111,5.148996,0.257928,1.059998,0.425022,1.913338,16.780684,16.817861,4.991673,1.966176,0.222494,0.720256,0.843842,1.922051,0.566948,1.283441,0.428883,0.955426,0.154646,0.143013,0.095984
min,170.000000,1.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25.000000,16.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.670000,10.510000,0.110000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,236.500000,23.500000,748.500000,0.000000,4.500000,1.000000,0.000000,0.285000,0.270000,0.370000,7.000000,9.000000,2.000000,6.000000,1.000000,20.500000,265.500000,196.000000,17.500000,2.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.405000,0.060000,3.320000,30.360000,22.735000,1.955000,0.230000,0.000000,0.280000,0.765000,0.855000,0.300000,0.490000,0.060000,0.000000,0.030000,0.030000,0.030000
50%,315.000000,29.000000,1564.000000,1.000000,12.000000,4.000000,1.000000,1.040000,0.960000,1.200000,20.000000,24.000000,9.000000,13.000000,3.000000,64.000000,617.000000,478.000000,48.000000,11.000000,2.000000,9.000000,0.000000,0.060000,0.060000,2.000000,0.150000,0.830000,0.250000,4.310000,38.270000,30.380000,3.460000,0.820000,0.110000,0.790000,1.480000,1.580000,0.690000,0.960000,0.250000,0.000000,0.070000,0.070000,0.090000
75%,389.500000,32.000000,2222.500000,2.000000,24.000000,8.000000,3.000000,2.230000,2.250000,2.530000,37.000000,51.000000,20.000000,30.000000,7.000000,107.500000,1031.500000,851.000000,105.500000,31.000000,4.000000,21.500000,0.000000,0.200000,0.150000,5.000000,0.370000,1.800000,0.640000,5.550000,51.090000,42.545000,5.845000,2.375000,0.290000,1.345000,1.995000,3.015000,1.115000,1.955000,0.525000,0.000000,0.180000,0.170000,0.170000
max,463.000000,35.000000,3060.000000,15.000000,114.000000,54.000000,26.000000,22.900000,19.730000,12.510000,95.000000,231.000000,65.000000,169.000000,28.000000,222.000000,3425.000000,3183.000000,627.000000,217.000000,32.000000,93.000000,104.000000,1.120000,0.720000,34.000000,1.280000,6.430000,2.030000,9.180000,108.270000,100.620000,27.460000,9.460000,1.230000,3.570000,3.770000,11.920000,2.590000,7.000000,4.590000,4.750000,0.890000,0.890000,0.660000

In [26]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/BULIcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [27]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [28]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000
mean,317.500000,23.476351,1255.152027,1.337838,15.290541,5.388514,1.885135,1.710845,1.596791,1.545845,19.726351,32.327703,10.935811,19.679054,4.263514,59.118243,611.415541,504.239865,72.422297,23.395270,2.449324,12.391892,4.432432,0.116318,0.081453,3.222973,0.198243,1.196115,0.345236,4.015135,37.668581,30.726385,4.269155,1.417331,0.164088,0.762939,1.243953,2.056486,0.711014,1.424020,0.330372,0.262804,0.110541,0.104730,0.095372
std,85.592056,10.558607,946.854504,2.148879,19.020329,8.032207,3.516592,2.948447,2.604382,2.002388,19.455890,40.635762,12.633528,25.912925,5.308594,53.716357,572.550766,505.677703,103.202388,39.072152,3.711293,15.687687,17.499312,0.187749,0.121126,4.933209,0.251890,2.787102,0.429195,3.435714,20.561532,19.039750,4.905735,1.901697,0.231944,0.772297,0.997668,2.146497,0.863810,2.994267,0.547958,0.886576,0.153547,0.143068,0.097372
min,170.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,243.750000,15.750000,297.500000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.070000,1.000000,4.000000,0.750000,2.750000,0.000000,8.750000,120.500000,95.500000,6.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.065000,0.000000,2.660000,26.742500,18.860000,1.102500,0.000000,0.000000,0.090000,0.240000,0.637500,0.022500,0.287500,0.000000,0.000000,0.000000,0.000000,0.020000
50%,317.500000,28.000000,1289.000000,0.000000,9.000000,2.000000,1.000000,0.770000,0.735000,0.765000,14.000000,17.000000,6.000000,11.000000,2.000000,48.500000,479.500000,353.500000,37.500000,6.500000,1.000000,7.000000,0.000000,0.030000,0.000000,1.000000,0.100000,0.745000,0.170000,4.085000,36.195000,27.530000,2.870000,0.630000,0.070000,0.525000,1.330000,1.395000,0.570000,0.850000,0.185000,0.000000,0.055000,0.050000,0.070000
75%,391.250000,32.000000,2046.500000,2.000000,21.000000,7.000000,2.000000,1.815000,1.805000,2.182500,34.000000,45.250000,18.000000,24.250000,6.000000,99.250000,964.250000,770.250000,96.250000,25.000000,3.000000,19.000000,0.000000,0.162500,0.132500,4.000000,0.312500,1.640000,0.540000,5.502500,47.822500,40.572500,5.397500,2.110000,0.262500,1.212500,1.910000,2.820000,1.070000,1.795000,0.462500,0.000000,0.160000,0.140000,0.150000
max,465.000000,35.000000,3060.000000,15.000000,114.000000,54.000000,26.000000,22.900000,19.730000,12.510000,95.000000,231.000000,65.000000,169.000000,28.000000,222.000000,3425.000000,3183.000000,627.000000,217.000000,32.000000,93.000000,104.000000,1.120000,0.720000,34.000000,1.280000,45.000000,2.140000,45.000000,108.270000,100.620000,27.460000,9.460000,1.640000,4.910000,6.430000,12.860000,10.000000,45.000000,6.000000,4.750000,0.890000,0.890000,0.660000

In [29]:
#We can see that the 25% cutoff is 297.5, once again we round up to 298
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 298].index)

In [30]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000,222.000000
mean,315.031532,28.297297,1646.693694,1.761261,19.995495,7.090090,2.486486,2.250135,2.098108,2.029910,25.855856,42.454955,14.337838,25.878378,5.522523,77.477477,802.495495,661.950450,95.121622,30.788288,3.193694,16.301802,5.842342,0.141261,0.096892,4.247748,0.238739,1.157252,0.412072,4.259865,42.409009,34.819685,4.961982,1.646261,0.175721,0.892703,1.418784,2.264640,0.758784,1.417297,0.321396,0.318108,0.128243,0.120450,0.109910
std,86.156670,5.629744,759.988715,2.328601,19.804131,8.621818,3.876755,3.227941,2.833400,2.095279,18.762554,42.266074,12.881581,27.210900,5.552460,49.861046,538.474380,490.630772,110.084043,42.606006,4.009418,16.323203,20.009668,0.192319,0.112091,5.311719,0.251209,0.985655,0.431183,1.843529,17.196547,17.206402,4.910550,1.924023,0.192991,0.711634,0.779624,1.880805,0.552385,1.217919,0.293731,0.970503,0.150787,0.137287,0.087783
min,170.000000,9.000000,300.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,60.000000,45.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.120000,14.670000,10.510000,0.110000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,236.250000,27.000000,998.000000,0.000000,6.000000,1.000000,0.000000,0.450000,0.420000,0.562500,11.000000,13.250000,4.000000,9.000000,1.000000,37.250000,383.750000,286.250000,27.000000,3.000000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.032500,0.440000,0.080000,3.370000,29.925000,22.627500,1.952500,0.252500,0.000000,0.292500,0.892500,0.905000,0.310000,0.550000,0.090000,0.000000,0.030000,0.030000,0.040000
50%,319.500000,30.000000,1679.500000,1.000000,14.000000,4.000000,1.000000,1.235000,1.190000,1.380000,24.000000,27.000000,11.000000,17.000000,4.000000,70.500000,710.500000,569.000000,59.500000,14.000000,2.000000,12.000000,0.000000,0.070000,0.070000,3.000000,0.165000,0.830000,0.250000,4.250000,37.970000,30.720000,3.565000,0.845000,0.110000,0.795000,1.510000,1.585000,0.700000,0.985000,0.250000,0.000000,0.070000,0.070000,0.090000
75%,389.750000,32.000000,2299.500000,2.000000,27.000000,9.000000,3.000000,2.695000,2.575000,2.677500,38.000000,53.750000,23.000000,33.750000,8.000000,114.750000,1121.250000,910.250000,114.750000,36.000000,5.000000,22.000000,0.000000,0.207500,0.150000,6.000000,0.365000,1.780000,0.650000,5.537500,51.170000,42.840000,5.835000,2.482500,0.270000,1.340000,1.950000,3.050000,1.150000,1.960000,0.505000,0.000000,0.180000,0.170000,0.160000
max,463.000000,35.000000,3060.000000,15.000000,114.000000,54.000000,26.000000,22.900000,19.730000,12.510000,95.000000,231.000000,65.000000,169.000000,28.000000,222.000000,3425.000000,3183.000000,627.000000,217.000000,32.000000,93.000000,104.000000,1.120000,0.580000,34.000000,1.280000,4.290000,2.030000,8.750000,108.270000,100.620000,27.460000,9.460000,1.230000,3.570000,3.770000,11.920000,2.590000,6.660000,1.470000,4.750000,0.790000,0.680000,0.480000

In [31]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/BULIcomplete25.csv")