Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/seriea/SEAmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name               0
Team               0
Tackles            0
Clearances         0
Interceptions      0
aerialsWon         0
Blocks             0
Mins               0
duelsWon           0
unnamed          104
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,0.0
mean,26.615385,55.442308,16.230769,30.442308,2.240385,1447.076923,74.105769,NaN
std,18.933869,49.389049,12.766941,27.924596,2.362717,1028.745628,53.199554,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,10.750000,13.750000,4.000000,7.750000,0.000000,467.750000,29.750000,NaN
50%,27.000000,47.500000,16.000000,25.000000,2.000000,1415.000000,74.500000,NaN
75%,41.000000,80.250000,25.000000,47.250000,4.000000,2253.500000,112.000000,NaN
max,71.000000,245.000000,56.000000,128.000000,10.000000,3420.000000,220.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 2987)
dfDdef["ID"] = (dfDdef.index + 2987)
dfDatt["ID"] = (dfDatt.index + 2987)
dfDpas["ID"] = (dfDpas.index + 2987) #should end at id no 3090
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 3158
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 3204
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 3338
dfMdft.head(300) #to check final id number

               Name        Team  App  Mins    ID
0        M. Darmian       Inter   33  1793  3205
1          N. Viola    Cagliari   36  1280  3206
2     H. Mkhitaryan       Inter   34  2410  3207
3         M. Badelj       Genoa   34  1486  3208
4        M. de Roon    Atalanta   37  3058  3209
..              ...         ...  ...   ...   ...
129      N. Fortini  Fiorentina    2     0  3334
130    SPS. Perciun      Torino    6   148  3335
131         L. Kasa       Genoa   25   235  3336
132  LVL. Venturino       Genoa   18   163  3337
133  RSR. Scaglione       Genoa    2     0  3338

[134 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/seriea/SEAdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/seriea/SEAforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/seriea/SEAgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/seriea/SEAmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,L. De Silvestri,Bologna,36,1055,2987,0,8.0,4,1,0.8087,0.820,0.3731,11,29,10,13,0,32,432,346,52,23,0,5,Defender,NaN
1,M. Hummels,Roma,33,918,2988,0,8.0,1,0,0.4684,0.469,0.0798,30,43,26,23,1,61,434,388,35,2,0,2,Defender,NaN
2,C. Kabasele,Udinese,37,1082,2989,0,15.0,4,2,1.4910,1.491,0.5206,16,63,13,33,2,65,539,461,81,2,0,6,Defender,NaN
3,S. de Vrij,Inter,35,1719,2990,0,13.0,3,3,1.0965,1.097,0.3047,18,88,23,65,6,91,1400,1307,63,0,0,1,Defender,NaN
4,C. Lykogiannis,Bologna,33,1038,2991,4,6.0,2,0,0.2360,0.236,2.0490,22,35,11,26,3,59,510,406,64,102,4,18,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,S. Sohm,Bologna,36,2909,3282,0,33.0,12,4,3.1328,3.076,2.0411,28,34,26,29,3,99,1177,1012,64,15,2,18,Midfielder,NaN
296,A. Harroui,Hellas Verona,11,462,3283,2,15.0,4,1,2.1587,2.190,0.5755,9,4,2,8,3,26,189,155,8,9,2,5,Midfielder,NaN
297,M. Frendrup,Genoa,36,3107,3284,0,30.0,9,2,1.6701,1.597,0.7729,102,49,47,31,7,172,1231,1057,64,3,0,14,Midfielder,NaN
298,A. Zanoli,Udinese,35,1714,3285,0,11.0,3,1,0.4332,0.433,1.0950,29,33,12,20,4,87,399,287,31,65,0,19,Midfielder,NaN
299,N. Zortea,Bologna,35,2637,3286,2,33.0,10,6,3.0682,3.082,2.2091,29,39,17,16,10,102,642,473,49,118,6,28,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,L. De Silvestri,Bologna,36,1055,2987,0,8.0,4,1,0.8087,0.820,0.3731,11,29,10,13,0,32,432,346,52,23,0,5,Defender,0.0
1,M. Hummels,Roma,33,918,2988,0,8.0,1,0,0.4684,0.469,0.0798,30,43,26,23,1,61,434,388,35,2,0,2,Defender,0.0
2,C. Kabasele,Udinese,37,1082,2989,0,15.0,4,2,1.4910,1.491,0.5206,16,63,13,33,2,65,539,461,81,2,0,6,Defender,0.0
3,S. de Vrij,Inter,35,1719,2990,0,13.0,3,3,1.0965,1.097,0.3047,18,88,23,65,6,91,1400,1307,63,0,0,1,Defender,0.0
4,C. Lykogiannis,Bologna,33,1038,2991,4,6.0,2,0,0.2360,0.236,2.0490,22,35,11,26,3,59,510,406,64,102,4,18,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,R. Belahyane,Lazio,36,1848,3329,2,6.0,2,0,0.2273,0.227,0.6543,44,24,11,7,0,97,789,670,59,3,1,16,Midfielder,0.0
343,A. Hainaut,Venezia,36,1136,3330,0,6.0,3,2,0.8323,0.833,1.1844,26,44,15,32,1,87,386,296,42,26,2,9,Midfielder,0.0
344,H. Cuenca,Genoa,4,0,3331,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
345,M. Palestra,Cagliari,31,218,3332,0,0.0,0,0,0.0000,0.000,0.5018,6,4,2,2,0,22,84,70,2,12,0,3,Midfielder,0.0
346,C. Papadopoulos,Genoa,2,0,3333,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,2987,Defender,L. De Silvestri,Bologna,36,1055,0,8.0,4,1,0.8087,0.820,0.3731,11,29,10,13,0,32,432,346,52,23,0,5,0.0
1,2988,Defender,M. Hummels,Roma,33,918,0,8.0,1,0,0.4684,0.469,0.0798,30,43,26,23,1,61,434,388,35,2,0,2,0.0
2,2989,Defender,C. Kabasele,Udinese,37,1082,0,15.0,4,2,1.4910,1.491,0.5206,16,63,13,33,2,65,539,461,81,2,0,6,0.0
3,2990,Defender,S. de Vrij,Inter,35,1719,0,13.0,3,3,1.0965,1.097,0.3047,18,88,23,65,6,91,1400,1307,63,0,0,1,0.0
4,2991,Defender,C. Lykogiannis,Bologna,33,1038,4,6.0,2,0,0.2360,0.236,2.0490,22,35,11,26,3,59,510,406,64,102,4,18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,3329,Midfielder,R. Belahyane,Lazio,36,1848,2,6.0,2,0,0.2273,0.227,0.6543,44,24,11,7,0,97,789,670,59,3,1,16,0.0
343,3330,Midfielder,A. Hainaut,Venezia,36,1136,0,6.0,3,2,0.8323,0.833,1.1844,26,44,15,32,1,87,386,296,42,26,2,9,0.0
344,3331,Midfielder,H. Cuenca,Genoa,4,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
345,3332,Midfielder,M. Palestra,Cagliari,31,218,0,0.0,0,0,0.0000,0.000,0.5018,6,4,2,2,0,22,84,70,2,12,0,3,0.0
346,3333,Midfielder,C. Papadopoulos,Genoa,2,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000
mean,3162.500000,27.090909,1319.928977,1.201705,16.298295,5.471591,1.718750,1.679330,1.554344,1.031098,19.772727,27.017045,9.474432,19.346591,4.457386,62.161932,585.727273,489.781250,68.525568,21.562500,2.011364,11.931818,2.377841
std,101.757883,11.223588,1038.625312,1.802720,20.229430,7.601866,2.876943,2.626288,2.351602,1.327165,19.404659,35.254706,11.167690,23.033588,5.672787,53.836774,559.380665,493.687982,108.829407,37.258649,2.668778,13.724016,10.365781
min,2987.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3074.750000,19.000000,267.000000,0.000000,1.000000,0.000000,0.000000,0.011175,0.011500,0.030075,2.000000,3.000000,0.000000,2.000000,0.000000,9.000000,85.500000,69.750000,6.000000,0.000000,0.000000,1.000000,0.000000
50%,3162.500000,33.000000,1144.500000,0.000000,10.000000,3.000000,0.500000,0.788400,0.746500,0.543550,16.000000,15.000000,5.500000,11.000000,2.000000,57.000000,455.500000,353.000000,33.000000,7.000000,1.000000,7.000000,0.000000
75%,3250.250000,36.000000,2249.500000,2.000000,23.250000,7.000000,2.000000,2.287725,2.153500,1.485000,31.250000,36.250000,15.000000,29.000000,7.000000,101.250000,907.500000,725.000000,84.000000,24.000000,3.000000,19.000000,0.000000
max,3338.000000,38.000000,3420.000000,10.000000,137.000000,51.000000,19.000000,19.420000,18.279000,6.257300,102.000000,245.000000,56.000000,128.000000,29.000000,220.000000,2769.000000,2521.000000,778.000000,256.000000,17.000000,69.000000,76.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2987,Defender,L. De Silvestri,Bologna,36,1055,0,8.0,4,1,0.8087,0.820,0.3731,11,29,10,13,0,32,432,346,52,23,0,5,0.0,0.085308,0.000000,1,0.085308,0.682464,0.341232,2.729858,36.853081,29.516588,4.436019,1.962085,0.000000,0.426540,0.938389,2.473934,0.853081,1.109005,0.000000,0.0,0.068989,0.069953,0.031828
1,2988,Defender,M. Hummels,Roma,33,918,0,8.0,1,0,0.4684,0.469,0.0798,30,43,26,23,1,61,434,388,35,2,0,2,0.0,0.000000,0.000000,0,0.000000,0.784314,0.098039,5.980392,42.549020,38.039216,3.431373,0.196078,0.000000,0.196078,2.941176,4.215686,2.549020,2.254902,0.098039,0.0,0.045922,0.045980,0.007824
2,2989,Defender,C. Kabasele,Udinese,37,1082,0,15.0,4,2,1.4910,1.491,0.5206,16,63,13,33,2,65,539,461,81,2,0,6,0.0,0.166359,0.000000,2,0.166359,1.247689,0.332717,5.406654,44.833641,38.345656,6.737523,0.166359,0.000000,0.499076,1.330869,5.240296,1.081331,2.744917,0.166359,0.0,0.124020,0.124020,0.043303
3,2990,Defender,S. de Vrij,Inter,35,1719,0,13.0,3,3,1.0965,1.097,0.3047,18,88,23,65,6,91,1400,1307,63,0,0,1,0.0,0.157068,0.000000,3,0.157068,0.680628,0.157068,4.764398,73.298429,68.429319,3.298429,0.000000,0.000000,0.052356,0.942408,4.607330,1.204188,3.403141,0.314136,0.0,0.057408,0.057435,0.015953
4,2991,Defender,C. Lykogiannis,Bologna,33,1038,4,6.0,2,0,0.2360,0.236,2.0490,22,35,11,26,3,59,510,406,64,102,4,18,0.0,0.000000,0.346821,4,0.346821,0.520231,0.173410,5.115607,44.219653,35.202312,5.549133,8.843931,0.346821,1.560694,1.907514,3.034682,0.953757,2.254335,0.260116,0.0,0.020462,0.020462,0.177659
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,3329,Midfielder,R. Belahyane,Lazio,36,1848,2,6.0,2,0,0.2273,0.227,0.6543,44,24,11,7,0,97,789,670,59,3,1,16,0.0,0.000000,0.097403,2,0.097403,0.292208,0.097403,4.724026,38.425325,32.629870,2.873377,0.146104,0.048701,0.779221,2.142857,1.168831,0.535714,0.340909,0.000000,0.0,0.011070,0.011055,0.031865
343,3330,Midfielder,A. Hainaut,Venezia,36,1136,0,6.0,3,2,0.8323,0.833,1.1844,26,44,15,32,1,87,386,296,42,26,2,9,0.0,0.158451,0.000000,2,0.158451,0.475352,0.237676,6.892606,30.580986,23.450704,3.327465,2.059859,0.158451,0.713028,2.059859,3.485915,1.188380,2.535211,0.079225,0.0,0.065939,0.065995,0.093835
344,3331,Midfielder,H. Cuenca,Genoa,4,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,3332,Midfielder,M. Palestra,Cagliari,31,218,0,0.0,0,0,0.0000,0.000,0.5018,6,4,2,2,0,22,84,70,2,12,0,3,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,9.082569,34.678899,28.899083,0.825688,4.954128,0.000000,1.238532,2.477064,1.651376,0.825688,0.825688,0.000000,0.0,0.000000,0.000000,0.207165
346,3333,Midfielder,C. Papadopoulos,Genoa,2,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2987,Defender,L. De Silvestri,Bologna,36,1055,0,8.0,4,1,0.81,0.82,0.37,11,29,10,13,0,32,432,346,52,23,0,5,0.0,0.09,0.00,1,0.09,0.68,0.34,2.73,36.85,29.52,4.44,1.96,0.00,0.43,0.94,2.47,0.85,1.11,0.00,0.0,0.07,0.07,0.03
1,2988,Defender,M. Hummels,Roma,33,918,0,8.0,1,0,0.47,0.47,0.08,30,43,26,23,1,61,434,388,35,2,0,2,0.0,0.00,0.00,0,0.00,0.78,0.10,5.98,42.55,38.04,3.43,0.20,0.00,0.20,2.94,4.22,2.55,2.25,0.10,0.0,0.05,0.05,0.01
2,2989,Defender,C. Kabasele,Udinese,37,1082,0,15.0,4,2,1.49,1.49,0.52,16,63,13,33,2,65,539,461,81,2,0,6,0.0,0.17,0.00,2,0.17,1.25,0.33,5.41,44.83,38.35,6.74,0.17,0.00,0.50,1.33,5.24,1.08,2.74,0.17,0.0,0.12,0.12,0.04
3,2990,Defender,S. de Vrij,Inter,35,1719,0,13.0,3,3,1.10,1.10,0.30,18,88,23,65,6,91,1400,1307,63,0,0,1,0.0,0.16,0.00,3,0.16,0.68,0.16,4.76,73.30,68.43,3.30,0.00,0.00,0.05,0.94,4.61,1.20,3.40,0.31,0.0,0.06,0.06,0.02
4,2991,Defender,C. Lykogiannis,Bologna,33,1038,4,6.0,2,0,0.24,0.24,2.05,22,35,11,26,3,59,510,406,64,102,4,18,0.0,0.00,0.35,4,0.35,0.52,0.17,5.12,44.22,35.20,5.55,8.84,0.35,1.56,1.91,3.03,0.95,2.25,0.26,0.0,0.02,0.02,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,3329,Midfielder,R. Belahyane,Lazio,36,1848,2,6.0,2,0,0.23,0.23,0.65,44,24,11,7,0,97,789,670,59,3,1,16,0.0,0.00,0.10,2,0.10,0.29,0.10,4.72,38.43,32.63,2.87,0.15,0.05,0.78,2.14,1.17,0.54,0.34,0.00,0.0,0.01,0.01,0.03
343,3330,Midfielder,A. Hainaut,Venezia,36,1136,0,6.0,3,2,0.83,0.83,1.18,26,44,15,32,1,87,386,296,42,26,2,9,0.0,0.16,0.00,2,0.16,0.48,0.24,6.89,30.58,23.45,3.33,2.06,0.16,0.71,2.06,3.49,1.19,2.54,0.08,0.0,0.07,0.07,0.09
344,3331,Midfielder,H. Cuenca,Genoa,4,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
345,3332,Midfielder,M. Palestra,Cagliari,31,218,0,0.0,0,0,0.00,0.00,0.50,6,4,2,2,0,22,84,70,2,12,0,3,0.0,0.00,0.00,0,0.00,0.00,0.00,9.08,34.68,28.90,0.83,4.95,0.00,1.24,2.48,1.65,0.83,0.83,0.00,0.0,0.00,0.00,0.21
346,3333,Midfielder,C. Papadopoulos,Genoa,2,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00

Adding and moving "League" column

In [18]:
#label
leagueLabel = "Serie A"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2987,Defender,Serie A,L. De Silvestri,Bologna,36,1055,0,8.0,4,1,0.81,0.82,0.37,11,29,10,13,0,32,432,346,52,23,0,5,0.0,0.09,0.00,1,0.09,0.68,0.34,2.73,36.85,29.52,4.44,1.96,0.00,0.43,0.94,2.47,0.85,1.11,0.00,0.0,0.07,0.07,0.03
1,2988,Defender,Serie A,M. Hummels,Roma,33,918,0,8.0,1,0,0.47,0.47,0.08,30,43,26,23,1,61,434,388,35,2,0,2,0.0,0.00,0.00,0,0.00,0.78,0.10,5.98,42.55,38.04,3.43,0.20,0.00,0.20,2.94,4.22,2.55,2.25,0.10,0.0,0.05,0.05,0.01
2,2989,Defender,Serie A,C. Kabasele,Udinese,37,1082,0,15.0,4,2,1.49,1.49,0.52,16,63,13,33,2,65,539,461,81,2,0,6,0.0,0.17,0.00,2,0.17,1.25,0.33,5.41,44.83,38.35,6.74,0.17,0.00,0.50,1.33,5.24,1.08,2.74,0.17,0.0,0.12,0.12,0.04
3,2990,Defender,Serie A,S. de Vrij,Inter,35,1719,0,13.0,3,3,1.10,1.10,0.30,18,88,23,65,6,91,1400,1307,63,0,0,1,0.0,0.16,0.00,3,0.16,0.68,0.16,4.76,73.30,68.43,3.30,0.00,0.00,0.05,0.94,4.61,1.20,3.40,0.31,0.0,0.06,0.06,0.02
4,2991,Defender,Serie A,C. Lykogiannis,Bologna,33,1038,4,6.0,2,0,0.24,0.24,2.05,22,35,11,26,3,59,510,406,64,102,4,18,0.0,0.00,0.35,4,0.35,0.52,0.17,5.12,44.22,35.20,5.55,8.84,0.35,1.56,1.91,3.03,0.95,2.25,0.26,0.0,0.02,0.02,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,3329,Midfielder,Serie A,R. Belahyane,Lazio,36,1848,2,6.0,2,0,0.23,0.23,0.65,44,24,11,7,0,97,789,670,59,3,1,16,0.0,0.00,0.10,2,0.10,0.29,0.10,4.72,38.43,32.63,2.87,0.15,0.05,0.78,2.14,1.17,0.54,0.34,0.00,0.0,0.01,0.01,0.03
343,3330,Midfielder,Serie A,A. Hainaut,Venezia,36,1136,0,6.0,3,2,0.83,0.83,1.18,26,44,15,32,1,87,386,296,42,26,2,9,0.0,0.16,0.00,2,0.16,0.48,0.24,6.89,30.58,23.45,3.33,2.06,0.16,0.71,2.06,3.49,1.19,2.54,0.08,0.0,0.07,0.07,0.09
344,3331,Midfielder,Serie A,H. Cuenca,Genoa,4,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
345,3332,Midfielder,Serie A,M. Palestra,Cagliari,31,218,0,0.0,0,0,0.00,0.00,0.50,6,4,2,2,0,22,84,70,2,12,0,3,0.0,0.00,0.00,0,0.00,0.00,0.00,9.08,34.68,28.90,0.83,4.95,0.00,1.24,2.48,1.65,0.83,0.83,0.00,0.0,0.00,0.00,0.21
346,3333,Midfielder,Serie A,C. Papadopoulos,Genoa,2,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/SEAcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.00000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.00000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000
mean,3159.638225,30.075085,1583.116041,1.443686,19.529010,6.556314,2.064846,2.012867,1.863038,1.236928,23.699659,32.416382,11.372014,23.191126,5.341297,74.522184,702.846416,587.795222,82.252560,25.860068,2.416382,14.293515,2.849829,0.117850,0.080102,3.508532,0.19785,1.150819,0.390956,4.505154,38.688532,32.108669,4.382150,1.569966,0.142321,0.828464,1.442253,1.795973,0.65256,1.350068,0.311638,0.150683,0.119795,0.111945,0.071843
std,103.912398,8.367899,939.117062,1.885708,20.719011,7.899263,3.038434,2.760983,2.464961,1.365103,18.978861,36.323659,11.328901,23.434351,5.829739,50.683922,542.221244,485.239193,114.492138,39.472171,2.753081,13.889086,11.305441,0.162905,0.106251,4.243137,0.21876,0.969757,0.399515,2.026539,15.119337,14.953250,4.230843,1.957187,0.167959,0.623648,0.867328,1.454496,0.48850,1.145455,0.336171,0.582018,0.138369,0.126429,0.068146
min,2987.000000,2.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,10.360000,5.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3066.000000,27.000000,918.000000,0.000000,5.000000,1.000000,0.000000,0.310000,0.300000,0.200000,8.000000,8.000000,2.000000,6.000000,1.000000,32.000000,268.000000,204.000000,17.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.430000,0.080000,3.480000,27.760000,20.910000,1.560000,0.160000,0.000000,0.290000,0.920000,0.750000,0.24000,0.540000,0.050000,0.000000,0.030000,0.030000,0.020000
50%,3159.000000,34.000000,1494.000000,1.000000,14.000000,4.000000,1.000000,1.030000,1.040000,0.750000,21.000000,21.000000,8.000000,14.000000,4.000000,69.000000,546.000000,437.000000,44.000000,10.000000,2.000000,10.000000,0.000000,0.060000,0.050000,2.000000,0.12000,0.850000,0.270000,4.710000,36.050000,28.950000,3.080000,0.740000,0.100000,0.780000,1.470000,1.300000,0.63000,1.080000,0.240000,0.000000,0.060000,0.060000,0.060000
75%,3254.000000,36.000000,2341.000000,2.000000,27.000000,8.000000,3.000000,2.510000,2.460000,1.800000,35.000000,43.000000,17.000000,32.000000,8.000000,111.000000,997.000000,834.000000,96.000000,28.000000,4.000000,21.000000,0.000000,0.170000,0.120000,5.000000,0.32000,1.850000,0.610000,5.570000,48.580000,41.550000,5.500000,2.330000,0.210000,1.250000,1.970000,2.460000,0.96000,1.840000,0.490000,0.000000,0.160000,0.160000,0.100000
max,3337.000000,38.000000,3420.000000,10.000000,137.000000,51.000000,19.000000,19.420000,18.280000,6.260000,102.000000,245.000000,56.000000,128.000000,29.000000,220.000000,2769.000000,2521.000000,778.000000,256.000000,17.000000,69.000000,76.000000,1.100000,0.640000,24.000000,1.12000,4.920000,2.270000,12.480000,83.830000,77.830000,22.000000,11.150000,1.120000,2.820000,5.140000,8.780000,2.55000,10.500000,2.940000,5.880000,0.640000,0.610000,0.330000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/SEAcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000,352.000000
mean,3162.500000,27.090909,1319.928977,1.201705,16.298295,5.471591,1.718750,1.679574,1.554460,1.031051,19.772727,27.017045,9.474432,19.346591,4.457386,62.161932,585.727273,489.781250,68.525568,21.562500,2.011364,11.931818,2.377841,0.098097,0.066676,2.920455,0.164687,1.039858,0.367017,4.112017,34.411960,28.450426,3.850994,1.447102,0.118466,0.761705,1.285369,1.765170,0.557841,1.228097,0.273580,0.144375,0.110455,0.102699,0.062273
std,101.757883,11.223588,1038.625312,1.802720,20.229430,7.601866,2.876943,2.626110,2.351612,1.327207,19.404659,35.254706,11.167690,23.033588,5.672787,53.836774,559.380665,493.687982,108.829407,37.258649,2.668778,13.724016,10.365781,0.154986,0.101437,4.086589,0.212812,1.095787,0.566937,2.578449,18.517378,17.176178,4.600333,2.232716,0.162180,0.856228,1.021952,3.546942,0.529124,1.307795,0.358039,0.637655,0.172811,0.151469,0.068616
min,2987.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3074.750000,19.000000,267.000000,0.000000,1.000000,0.000000,0.000000,0.010000,0.010000,0.030000,2.000000,3.000000,0.000000,2.000000,0.000000,9.000000,85.500000,69.750000,6.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.090000,0.000000,3.060000,23.247500,16.580000,1.027500,0.000000,0.000000,0.065000,0.347500,0.450000,0.000000,0.290000,0.000000,0.000000,0.000000,0.000000,0.010000
50%,3162.500000,33.000000,1144.500000,0.000000,10.000000,3.000000,0.500000,0.790000,0.745000,0.545000,16.000000,15.000000,5.500000,11.000000,2.000000,57.000000,455.500000,353.000000,33.000000,7.000000,1.000000,7.000000,0.000000,0.015000,0.000000,1.000000,0.080000,0.700000,0.180000,4.390000,34.060000,27.350000,2.435000,0.515000,0.060000,0.645000,1.300000,1.050000,0.485000,0.910000,0.160000,0.000000,0.050000,0.050000,0.040000
75%,3250.250000,36.000000,2249.500000,2.000000,23.250000,7.000000,2.000000,2.290000,2.152500,1.485000,31.250000,36.250000,15.000000,29.000000,7.000000,101.250000,907.500000,725.000000,84.000000,24.000000,3.000000,19.000000,0.000000,0.152500,0.100000,4.000000,0.260000,1.717500,0.552500,5.520000,45.902500,38.392500,5.130000,2.110000,0.190000,1.170000,1.910000,2.210000,0.882500,1.800000,0.445000,0.000000,0.142500,0.140000,0.090000
max,3338.000000,38.000000,3420.000000,10.000000,137.000000,51.000000,19.000000,19.420000,18.280000,6.260000,102.000000,245.000000,56.000000,128.000000,29.000000,220.000000,2769.000000,2521.000000,778.000000,256.000000,17.000000,69.000000,76.000000,1.100000,0.640000,24.000000,1.120000,7.200000,6.920000,12.860000,83.830000,77.830000,36.670000,22.500000,1.120000,8.180000,5.620000,60.000000,2.730000,11.250000,2.940000,6.670000,2.060000,1.640000,0.330000

In [27]:
#We can see that the 25% cutoff is 267
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 267].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000
mean,3157.575758,31.200758,1739.272727,1.598485,21.496212,7.204545,2.272727,2.214886,2.049886,1.360076,25.984848,35.534091,12.462121,25.534091,5.890152,81.742424,773.041667,646.734848,90.321970,28.306818,2.662879,15.731061,3.083333,0.122500,0.087500,3.871212,0.209848,1.190758,0.399356,4.504053,39.098106,32.579811,4.261970,1.524432,0.148030,0.848902,1.430644,1.760947,0.639280,1.393144,0.327803,0.115114,0.123977,0.115909,0.073068
std,103.520658,7.278898,855.320958,1.923874,20.895175,8.051393,3.127435,2.835042,2.526131,1.382661,18.608835,36.945222,11.413357,23.528940,5.880242,48.138760,525.651949,475.457568,117.822668,40.828965,2.785757,13.893389,11.869084,0.150749,0.107129,4.313574,0.206646,0.952835,0.376143,1.871997,15.250338,15.007656,3.917892,1.849278,0.151077,0.613235,0.796957,1.424270,0.461063,1.156551,0.324786,0.419121,0.137115,0.125440,0.065147
min,2987.000000,6.000000,270.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,61.000000,39.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.360000,7.440000,0.040000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3059.750000,29.750000,1058.750000,0.000000,6.000000,2.000000,0.000000,0.485000,0.485000,0.307500,12.000000,10.750000,3.000000,8.000000,1.000000,47.000000,388.250000,292.750000,23.000000,3.000000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.040000,0.467500,0.120000,3.535000,28.272500,20.997500,1.605000,0.187500,0.000000,0.317500,0.940000,0.745000,0.247500,0.580000,0.090000,0.000000,0.030000,0.030000,0.020000
50%,3155.000000,34.000000,1687.500000,1.000000,15.500000,5.000000,1.000000,1.155000,1.135000,0.890000,24.000000,22.500000,9.500000,18.000000,4.000000,75.000000,634.500000,486.500000,52.500000,11.000000,2.000000,11.500000,0.000000,0.070000,0.060000,2.000000,0.150000,0.885000,0.280000,4.720000,36.275000,29.855000,3.070000,0.750000,0.120000,0.800000,1.455000,1.285000,0.630000,1.125000,0.255000,0.000000,0.070000,0.070000,0.060000
75%,3250.750000,36.000000,2422.500000,2.250000,29.000000,9.000000,3.000000,2.667500,2.682500,1.992500,39.000000,46.250000,19.000000,36.000000,9.000000,118.000000,1030.000000,895.750000,103.000000,37.500000,4.000000,24.250000,0.000000,0.180000,0.130000,5.250000,0.322500,1.892500,0.612500,5.520000,49.212500,41.815000,5.467500,2.182500,0.220000,1.262500,1.942500,2.450000,0.930000,1.960000,0.502500,0.000000,0.170000,0.160000,0.100000
max,3330.000000,38.000000,3420.000000,10.000000,137.000000,51.000000,19.000000,19.420000,18.280000,6.260000,102.000000,245.000000,56.000000,128.000000,29.000000,220.000000,2769.000000,2521.000000,778.000000,256.000000,17.000000,69.000000,76.000000,0.760000,0.640000,24.000000,0.960000,4.410000,1.690000,11.460000,83.830000,77.830000,21.770000,8.840000,0.940000,2.820000,3.620000,8.780000,2.550000,10.500000,2.940000,2.400000,0.640000,0.610000,0.330000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/SEAcomplete25.csv")