Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/championship/CHAMPmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name               0
Team               0
Tackles            0
Clearances         0
Interceptions      0
aerialsWon         0
Blocks             0
Mins               0
duelsWon           0
unnamed          108
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,0.0
mean,31.972222,90.083333,20.629630,51.175926,3.527778,1758.833333,105.296296,NaN
std,26.208174,74.625185,16.262216,48.845901,4.063649,1236.073513,79.491404,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,9.750000,32.500000,5.750000,15.000000,1.000000,680.250000,34.750000,NaN
50%,27.000000,76.500000,20.000000,36.000000,2.000000,1670.500000,92.500000,NaN
75%,51.000000,135.500000,33.250000,80.000000,5.000000,2694.750000,161.250000,NaN
max,113.000000,273.000000,69.000000,217.000000,27.000000,4223.000000,376.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 466)
dfDdef["ID"] = (dfDdef.index + 466)
dfDatt["ID"] = (dfDatt.index + 466)
dfDpas["ID"] = (dfDpas.index + 466) #should end at id no 573
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 635
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 671
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 792
dfMdft.head(300) #to check final id number

                      Name               Team  App  Mins   ID
0                 J. Allen       Swansea City   33   739  672
1               M. Ritchie            Reading   46  2220  673
2                B. Bannan           Millwall   42  3469  674
3               A. Weimann       Derby County   31  1415  675
4               A. Forshaw   Blackburn Rovers   42  1271  676
..                     ...                ...  ...   ...  ...
116             C. Ashford       Cardiff City   37  1532  788
117           H. Armstrong  Preston North End   16  1110  789
118                F. Vare   Blackburn Rovers    1     0  790
119              IDI. Dunn   Blackburn Rovers    2     0  791
120  RBR. Bangura-Williams           Millwall   13   609  792

[121 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/championship/CHAMPdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/championship/CHAMPforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/championship/CHAMPgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/championship/CHAMPmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,K. Bartley,West Bromwich Albion,33,2612,466,0,24.0,6,0,1.8740,1.875,0.8605,25,179,23,111,4,148,1686,1500,158,1,3,11,Defender,NaN
1,S. Cook,Queens Park Rangers,32,2622,467,0,19.0,8,2,1.4534,1.489,1.1702,19,171,24,74,5,111,1398,1097,309,19,0,7,Defender,NaN
2,C. Forsyth,Derby County,46,2554,468,4,18.0,6,3,2.0275,2.001,1.8599,36,134,30,93,2,145,1091,780,203,35,4,12,Defender,NaN
3,A. Hughes,Preston North End,41,3238,469,1,9.0,3,0,0.6581,0.533,1.5122,73,155,36,129,3,236,1744,1330,278,42,0,15,Defender,NaN
4,D. Batth,Derby County,39,3016,470,0,17.0,6,2,2.1173,2.087,0.8756,31,239,37,154,7,206,1545,1236,271,0,1,4,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,T. Seko,Stoke City,42,1594,761,0,9.0,1,0,0.2275,0.216,0.5862,41,45,16,18,0,84,819,676,97,32,2,8,Midfielder,NaN
296,J. Anthony,Bournemouth,43,3672,762,7,97.0,34,8,9.3610,9.388,8.1348,56,40,31,20,30,177,1356,1085,89,251,14,83,Midfielder,NaN
297,E. Matazo,Hull City,6,302,763,0,4.0,2,1,0.2379,0.238,1.0055,3,6,5,3,1,15,118,98,5,9,0,7,Midfielder,NaN
298,I. Price,West Bromwich Albion,17,1055,764,1,16.0,4,1,1.1875,1.183,1.6309,29,30,11,15,2,64,451,354,53,63,2,21,Midfielder,NaN
299,D. Gyabi,Hull City,44,2892,765,2,33.0,9,1,2.9899,3.030,1.0485,68,46,22,33,10,204,886,720,61,6,2,24,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,K. Bartley,West Bromwich Albion,33,2612,466,0,24.0,6,0,1.8740,1.875,0.8605,25,179,23,111,4,148,1686,1500,158,1,3,11,Defender,0.0
1,S. Cook,Queens Park Rangers,32,2622,467,0,19.0,8,2,1.4534,1.489,1.1702,19,171,24,74,5,111,1398,1097,309,19,0,7,Defender,0.0
2,C. Forsyth,Derby County,46,2554,468,4,18.0,6,3,2.0275,2.001,1.8599,36,134,30,93,2,145,1091,780,203,35,4,12,Defender,0.0
3,A. Hughes,Preston North End,41,3238,469,1,9.0,3,0,0.6581,0.533,1.5122,73,155,36,129,3,236,1744,1330,278,42,0,15,Defender,0.0
4,D. Batth,Derby County,39,3016,470,0,17.0,6,2,2.1173,2.087,0.8756,31,239,37,154,7,206,1545,1236,271,0,1,4,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,A. Brooks,Sheffield United,43,1072,783,2,24.0,12,4,3.3645,3.712,2.6419,39,11,7,15,8,92,315,260,22,17,4,13,Midfielder,0.0
318,K. Morgan,Queens Park Rangers,40,1592,784,2,17.0,3,1,0.9140,0.909,0.7821,24,20,10,8,4,48,664,496,66,20,4,10,Midfielder,0.0
319,R. Esse,Coventry City,24,2029,785,1,30.0,12,4,2.1147,2.199,3.1746,66,18,9,24,13,204,496,337,63,69,6,27,Midfielder,0.0
320,L. McCabe,Middlesbrough,22,0,786,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
321,D. Bennie,Queens Park Rangers,32,228,787,0,3.0,1,0,0.2192,0.219,0.0836,0,7,1,7,2,8,58,40,6,5,0,1,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,466,Defender,K. Bartley,West Bromwich Albion,33,2612,0,24.0,6,0,1.8740,1.875,0.8605,25,179,23,111,4,148,1686,1500,158,1,3,11,0.0
1,467,Defender,S. Cook,Queens Park Rangers,32,2622,0,19.0,8,2,1.4534,1.489,1.1702,19,171,24,74,5,111,1398,1097,309,19,0,7,0.0
2,468,Defender,C. Forsyth,Derby County,46,2554,4,18.0,6,3,2.0275,2.001,1.8599,36,134,30,93,2,145,1091,780,203,35,4,12,0.0
3,469,Defender,A. Hughes,Preston North End,41,3238,1,9.0,3,0,0.6581,0.533,1.5122,73,155,36,129,3,236,1744,1330,278,42,0,15,0.0
4,470,Defender,D. Batth,Derby County,39,3016,0,17.0,6,2,2.1173,2.087,0.8756,31,239,37,154,7,206,1545,1236,271,0,1,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,783,Midfielder,A. Brooks,Sheffield United,43,1072,2,24.0,12,4,3.3645,3.712,2.6419,39,11,7,15,8,92,315,260,22,17,4,13,0.0
318,784,Midfielder,K. Morgan,Queens Park Rangers,40,1592,2,17.0,3,1,0.9140,0.909,0.7821,24,20,10,8,4,48,664,496,66,20,4,10,0.0
319,785,Midfielder,R. Esse,Coventry City,24,2029,1,30.0,12,4,2.1147,2.199,3.1746,66,18,9,24,13,204,496,337,63,69,6,27,0.0
320,786,Midfielder,L. McCabe,Middlesbrough,22,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
321,787,Midfielder,D. Bennie,Queens Park Rangers,32,228,0,3.0,1,0,0.2192,0.219,0.0836,0,7,1,7,2,8,58,40,6,5,0,1,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000
mean,629.000000,29.810398,1668.412844,1.302752,20.021407,6.519878,1.902141,2.062618,1.980089,1.501755,27.217125,43.996942,13.373089,30.629969,6.125382,86.183486,683.541284,539.214067,99.262997,32.461774,2.388379,14.996942,5.003058
std,94.540996,14.216365,1240.188299,1.874128,21.759340,8.099765,2.844038,2.720075,2.571275,1.886786,27.992088,56.262177,14.629628,38.280456,7.289765,75.595935,654.944486,547.613201,151.908386,50.402347,3.234058,17.978770,21.702888
min,466.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,547.500000,19.000000,555.000000,0.000000,2.000000,0.000000,0.000000,0.128500,0.127500,0.088350,3.000000,7.000000,1.000000,5.000000,0.000000,21.500000,166.500000,111.500000,12.500000,1.000000,0.000000,1.000000,0.000000
50%,629.000000,33.000000,1570.000000,1.000000,13.000000,3.000000,1.000000,0.934300,0.935000,0.796700,18.000000,24.000000,8.000000,17.000000,3.000000,71.000000,467.000000,360.000000,50.000000,11.000000,1.000000,8.000000,0.000000
75%,710.500000,42.000000,2611.000000,2.000000,30.000000,9.500000,3.000000,2.766000,2.723000,2.201800,43.000000,50.500000,22.000000,41.500000,10.000000,139.000000,1081.000000,858.500000,124.500000,43.000000,4.000000,22.500000,0.000000
max,792.000000,49.000000,4230.000000,12.000000,97.000000,36.000000,13.000000,12.624000,12.838000,9.342100,151.000000,273.000000,69.000000,234.000000,38.000000,376.000000,3793.000000,3443.000000,1078.000000,297.000000,16.000000,83.000000,152.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,466,Defender,K. Bartley,West Bromwich Albion,33,2612,0,24.0,6,0,1.8740,1.875,0.8605,25,179,23,111,4,148,1686,1500,158,1,3,11,0.0,0.000000,0.000000,0,0.000000,0.826953,0.206738,5.099541,58.093415,51.684533,5.444104,0.034456,0.103369,0.379020,0.861409,6.167688,0.792496,3.824655,0.137825,0.0,0.064571,0.064606,0.029650
1,467,Defender,S. Cook,Queens Park Rangers,32,2622,0,19.0,8,2,1.4534,1.489,1.1702,19,171,24,74,5,111,1398,1097,309,19,0,7,0.0,0.068650,0.000000,2,0.068650,0.652174,0.274600,3.810069,47.986270,37.654462,10.606407,0.652174,0.000000,0.240275,0.652174,5.869565,0.823799,2.540046,0.171625,0.0,0.049888,0.051110,0.040167
2,468,Defender,C. Forsyth,Derby County,46,2554,4,18.0,6,3,2.0275,2.001,1.8599,36,134,30,93,2,145,1091,780,203,35,4,12,0.0,0.105717,0.140955,7,0.246672,0.634299,0.211433,5.109632,38.445576,27.486296,7.153485,1.233359,0.140955,0.422866,1.268598,4.722005,1.057165,3.277212,0.070478,0.0,0.071447,0.070513,0.065541
3,469,Defender,A. Hughes,Preston North End,41,3238,1,9.0,3,0,0.6581,0.533,1.5122,73,155,36,129,3,236,1744,1330,278,42,0,15,0.0,0.000000,0.027795,1,0.027795,0.250154,0.083385,6.559605,48.474367,36.967264,7.726992,1.167387,0.000000,0.416924,2.029030,4.308215,1.000618,3.585547,0.083385,0.0,0.018292,0.014815,0.042032
4,470,Defender,D. Batth,Derby County,39,3016,0,17.0,6,2,2.1173,2.087,0.8756,31,239,37,154,7,206,1545,1236,271,0,1,4,0.0,0.059682,0.000000,2,0.059682,0.507294,0.179045,6.147215,46.104111,36.883289,8.086870,0.000000,0.029841,0.119363,0.925066,7.131963,1.104111,4.595491,0.208886,0.0,0.063182,0.062278,0.026129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,783,Midfielder,A. Brooks,Sheffield United,43,1072,2,24.0,12,4,3.3645,3.712,2.6419,39,11,7,15,8,92,315,260,22,17,4,13,0.0,0.335821,0.167910,6,0.503731,2.014925,1.007463,7.723881,26.445896,21.828358,1.847015,1.427239,0.335821,1.091418,3.274254,0.923507,0.587687,1.259328,0.671642,0.0,0.282467,0.311642,0.221801
318,784,Midfielder,K. Morgan,Queens Park Rangers,40,1592,2,17.0,3,1,0.9140,0.909,0.7821,24,20,10,8,4,48,664,496,66,20,4,10,0.0,0.056533,0.113065,3,0.169598,0.961055,0.169598,2.713568,37.537688,28.040201,3.731156,1.130653,0.226131,0.565327,1.356784,1.130653,0.565327,0.452261,0.226131,0.0,0.051671,0.051388,0.044214
319,785,Midfielder,R. Esse,Coventry City,24,2029,1,30.0,12,4,2.1147,2.199,3.1746,66,18,9,24,13,204,496,337,63,69,6,27,0.0,0.177427,0.044357,5,0.221784,1.330705,0.532282,9.048793,22.000986,14.948250,2.794480,3.060621,0.266141,1.197634,2.927551,0.798423,0.399211,1.064564,0.576639,0.0,0.093801,0.097541,0.140815
320,786,Midfielder,L. McCabe,Middlesbrough,22,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,787,Midfielder,D. Bennie,Queens Park Rangers,32,228,0,3.0,1,0,0.2192,0.219,0.0836,0,7,1,7,2,8,58,40,6,5,0,1,0.0,0.000000,0.000000,0,0.000000,1.184211,0.394737,3.157895,22.894737,15.789474,2.368421,1.973684,0.000000,0.394737,0.000000,2.763158,0.394737,2.763158,0.789474,0.0,0.086526,0.086447,0.033000

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,466,Defender,K. Bartley,West Bromwich Albion,33,2612,0,24.0,6,0,1.87,1.88,0.86,25,179,23,111,4,148,1686,1500,158,1,3,11,0.0,0.00,0.00,0,0.00,0.83,0.21,5.10,58.09,51.68,5.44,0.03,0.10,0.38,0.86,6.17,0.79,3.82,0.14,0.0,0.06,0.06,0.03
1,467,Defender,S. Cook,Queens Park Rangers,32,2622,0,19.0,8,2,1.45,1.49,1.17,19,171,24,74,5,111,1398,1097,309,19,0,7,0.0,0.07,0.00,2,0.07,0.65,0.27,3.81,47.99,37.65,10.61,0.65,0.00,0.24,0.65,5.87,0.82,2.54,0.17,0.0,0.05,0.05,0.04
2,468,Defender,C. Forsyth,Derby County,46,2554,4,18.0,6,3,2.03,2.00,1.86,36,134,30,93,2,145,1091,780,203,35,4,12,0.0,0.11,0.14,7,0.25,0.63,0.21,5.11,38.45,27.49,7.15,1.23,0.14,0.42,1.27,4.72,1.06,3.28,0.07,0.0,0.07,0.07,0.07
3,469,Defender,A. Hughes,Preston North End,41,3238,1,9.0,3,0,0.66,0.53,1.51,73,155,36,129,3,236,1744,1330,278,42,0,15,0.0,0.00,0.03,1,0.03,0.25,0.08,6.56,48.47,36.97,7.73,1.17,0.00,0.42,2.03,4.31,1.00,3.59,0.08,0.0,0.02,0.01,0.04
4,470,Defender,D. Batth,Derby County,39,3016,0,17.0,6,2,2.12,2.09,0.88,31,239,37,154,7,206,1545,1236,271,0,1,4,0.0,0.06,0.00,2,0.06,0.51,0.18,6.15,46.10,36.88,8.09,0.00,0.03,0.12,0.93,7.13,1.10,4.60,0.21,0.0,0.06,0.06,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,783,Midfielder,A. Brooks,Sheffield United,43,1072,2,24.0,12,4,3.36,3.71,2.64,39,11,7,15,8,92,315,260,22,17,4,13,0.0,0.34,0.17,6,0.50,2.01,1.01,7.72,26.45,21.83,1.85,1.43,0.34,1.09,3.27,0.92,0.59,1.26,0.67,0.0,0.28,0.31,0.22
318,784,Midfielder,K. Morgan,Queens Park Rangers,40,1592,2,17.0,3,1,0.91,0.91,0.78,24,20,10,8,4,48,664,496,66,20,4,10,0.0,0.06,0.11,3,0.17,0.96,0.17,2.71,37.54,28.04,3.73,1.13,0.23,0.57,1.36,1.13,0.57,0.45,0.23,0.0,0.05,0.05,0.04
319,785,Midfielder,R. Esse,Coventry City,24,2029,1,30.0,12,4,2.11,2.20,3.17,66,18,9,24,13,204,496,337,63,69,6,27,0.0,0.18,0.04,5,0.22,1.33,0.53,9.05,22.00,14.95,2.79,3.06,0.27,1.20,2.93,0.80,0.40,1.06,0.58,0.0,0.09,0.10,0.14
320,786,Midfielder,L. McCabe,Middlesbrough,22,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
321,787,Midfielder,D. Bennie,Queens Park Rangers,32,228,0,3.0,1,0,0.22,0.22,0.08,0,7,1,7,2,8,58,40,6,5,0,1,0.0,0.00,0.00,0,0.00,1.18,0.39,3.16,22.89,15.79,2.37,1.97,0.00,0.39,0.00,2.76,0.39,2.76,0.79,0.0,0.09,0.09,0.03

Adding and moving "League" column

In [18]:
#label
leagueLabel = "Championship"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,466,Defender,Championship,K. Bartley,West Bromwich Albion,33,2612,0,24.0,6,0,1.87,1.88,0.86,25,179,23,111,4,148,1686,1500,158,1,3,11,0.0,0.00,0.00,0,0.00,0.83,0.21,5.10,58.09,51.68,5.44,0.03,0.10,0.38,0.86,6.17,0.79,3.82,0.14,0.0,0.06,0.06,0.03
1,467,Defender,Championship,S. Cook,Queens Park Rangers,32,2622,0,19.0,8,2,1.45,1.49,1.17,19,171,24,74,5,111,1398,1097,309,19,0,7,0.0,0.07,0.00,2,0.07,0.65,0.27,3.81,47.99,37.65,10.61,0.65,0.00,0.24,0.65,5.87,0.82,2.54,0.17,0.0,0.05,0.05,0.04
2,468,Defender,Championship,C. Forsyth,Derby County,46,2554,4,18.0,6,3,2.03,2.00,1.86,36,134,30,93,2,145,1091,780,203,35,4,12,0.0,0.11,0.14,7,0.25,0.63,0.21,5.11,38.45,27.49,7.15,1.23,0.14,0.42,1.27,4.72,1.06,3.28,0.07,0.0,0.07,0.07,0.07
3,469,Defender,Championship,A. Hughes,Preston North End,41,3238,1,9.0,3,0,0.66,0.53,1.51,73,155,36,129,3,236,1744,1330,278,42,0,15,0.0,0.00,0.03,1,0.03,0.25,0.08,6.56,48.47,36.97,7.73,1.17,0.00,0.42,2.03,4.31,1.00,3.59,0.08,0.0,0.02,0.01,0.04
4,470,Defender,Championship,D. Batth,Derby County,39,3016,0,17.0,6,2,2.12,2.09,0.88,31,239,37,154,7,206,1545,1236,271,0,1,4,0.0,0.06,0.00,2,0.06,0.51,0.18,6.15,46.10,36.88,8.09,0.00,0.03,0.12,0.93,7.13,1.10,4.60,0.21,0.0,0.06,0.06,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,783,Midfielder,Championship,A. Brooks,Sheffield United,43,1072,2,24.0,12,4,3.36,3.71,2.64,39,11,7,15,8,92,315,260,22,17,4,13,0.0,0.34,0.17,6,0.50,2.01,1.01,7.72,26.45,21.83,1.85,1.43,0.34,1.09,3.27,0.92,0.59,1.26,0.67,0.0,0.28,0.31,0.22
318,784,Midfielder,Championship,K. Morgan,Queens Park Rangers,40,1592,2,17.0,3,1,0.91,0.91,0.78,24,20,10,8,4,48,664,496,66,20,4,10,0.0,0.06,0.11,3,0.17,0.96,0.17,2.71,37.54,28.04,3.73,1.13,0.23,0.57,1.36,1.13,0.57,0.45,0.23,0.0,0.05,0.05,0.04
319,785,Midfielder,Championship,R. Esse,Coventry City,24,2029,1,30.0,12,4,2.11,2.20,3.17,66,18,9,24,13,204,496,337,63,69,6,27,0.0,0.18,0.04,5,0.22,1.33,0.53,9.05,22.00,14.95,2.79,3.06,0.27,1.20,2.93,0.80,0.40,1.06,0.58,0.0,0.09,0.10,0.14
320,786,Midfielder,Championship,L. McCabe,Middlesbrough,22,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
321,787,Midfielder,Championship,D. Bennie,Queens Park Rangers,32,228,0,3.0,1,0,0.22,0.22,0.08,0,7,1,7,2,8,58,40,6,5,0,1,0.0,0.00,0.00,0,0.00,1.18,0.39,3.16,22.89,15.79,2.37,1.97,0.00,0.39,0.00,2.76,0.39,2.76,0.79,0.0,0.09,0.09,0.03

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/CHAMPcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- CHAMPcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- CHAMPcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000,287.000000
mean,628.275261,33.066202,1899.714286,1.477352,22.780488,7.418118,2.156794,2.348328,2.254599,1.709408,30.972125,50.121951,15.222997,34.891986,6.975610,98.118467,778.236934,613.895470,113.069686,36.937282,2.714286,17.062718,5.700348,0.105470,0.070035,3.634146,0.175331,1.111045,0.372056,4.747352,34.765331,27.236655,4.920139,1.743902,0.124390,0.788118,1.481916,2.325993,0.708955,1.701707,0.338014,0.232195,0.116934,0.113484,0.077003
std,97.473885,11.589684,1146.398664,1.935682,21.843785,8.255497,2.945866,2.786068,2.630362,1.924313,27.881478,57.448875,14.692147,39.004108,7.391838,73.110367,644.486188,544.108493,157.288637,52.261074,3.323245,18.258906,23.084690,0.137979,0.099655,4.113166,0.181924,0.859705,0.398240,2.068127,13.563873,12.755031,4.849676,1.925667,0.141753,0.627510,0.919364,1.983412,0.506116,1.463214,0.294908,0.743960,0.131887,0.126144,0.066475
min,466.000000,3.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,31.000000,21.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.740000,4.330000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,538.500000,24.000000,944.000000,0.000000,6.000000,1.000000,0.000000,0.310000,0.310000,0.290000,9.000000,11.000000,3.000000,9.000000,1.500000,37.000000,282.500000,205.500000,20.500000,3.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.495000,0.080000,3.755000,25.790000,18.155000,1.720000,0.220000,0.000000,0.295000,0.800000,0.905000,0.285000,0.650000,0.110000,0.000000,0.030000,0.030000,0.030000
50%,625.000000,36.000000,1788.000000,1.000000,17.000000,4.000000,1.000000,1.400000,1.360000,1.030000,23.000000,30.000000,11.000000,21.000000,5.000000,84.000000,582.000000,443.000000,62.000000,15.000000,1.000000,11.000000,0.000000,0.060000,0.040000,2.000000,0.110000,0.920000,0.240000,4.870000,33.530000,25.600000,3.810000,1.050000,0.090000,0.650000,1.430000,1.520000,0.720000,1.260000,0.270000,0.000000,0.070000,0.070000,0.060000
75%,715.500000,43.000000,2761.500000,2.000000,33.000000,10.500000,3.000000,3.120000,2.965000,2.325000,48.500000,62.500000,24.000000,46.000000,10.000000,149.500000,1184.500000,926.500000,144.000000,51.500000,4.000000,24.000000,0.000000,0.150000,0.110000,6.000000,0.275000,1.655000,0.575000,6.085000,42.915000,34.810000,6.195000,2.850000,0.190000,1.135000,2.140000,3.105000,1.010000,2.310000,0.525000,0.000000,0.150000,0.140000,0.110000
max,792.000000,49.000000,4230.000000,12.000000,97.000000,36.000000,13.000000,12.620000,12.840000,9.340000,151.000000,273.000000,69.000000,234.000000,38.000000,376.000000,3793.000000,3443.000000,1078.000000,297.000000,16.000000,83.000000,152.000000,0.600000,0.800000,22.000000,0.800000,3.840000,2.800000,10.850000,81.570000,74.040000,27.970000,12.100000,1.030000,2.820000,4.660000,8.900000,2.520000,7.680000,1.350000,4.000000,0.940000,0.870000,0.360000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/CHAMPcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000
mean,629.000000,29.810398,1668.412844,1.302752,20.021407,6.519878,1.902141,2.062508,1.980214,1.501835,27.217125,43.996942,13.373089,30.629969,6.125382,86.183486,683.541284,539.214067,99.262997,32.461774,2.388379,14.996942,5.003058,0.112477,0.076514,3.204893,0.188838,1.024037,0.346453,4.312232,31.436820,24.619144,4.353823,1.612722,0.124220,0.730122,1.361988,2.051131,0.640000,1.517982,0.300703,0.203792,0.105260,0.102263,0.070673
std,94.540996,14.216365,1240.188299,1.874128,21.759340,8.099765,2.844038,2.719902,2.571355,1.886524,27.992088,56.262177,14.629628,38.280456,7.289765,75.595935,654.944486,547.613201,151.908386,50.402347,3.234058,17.978770,21.702888,0.259726,0.228600,4.023425,0.445634,0.969851,0.440744,2.518316,16.563744,14.661491,4.804548,1.949677,0.246722,0.692781,1.048620,2.006197,0.555452,1.505569,0.302538,0.700979,0.129825,0.124459,0.070707
min,466.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,547.500000,19.000000,555.000000,0.000000,2.000000,0.000000,0.000000,0.130000,0.125000,0.090000,3.000000,7.000000,1.000000,5.000000,0.000000,21.500000,166.500000,111.500000,12.500000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.265000,0.000000,3.005000,22.050000,15.260000,1.100000,0.030000,0.000000,0.155000,0.515000,0.675000,0.125000,0.440000,0.000000,0.000000,0.010000,0.010000,0.010000
50%,629.000000,33.000000,1570.000000,1.000000,13.000000,3.000000,1.000000,0.930000,0.940000,0.800000,18.000000,24.000000,8.000000,17.000000,3.000000,71.000000,467.000000,360.000000,50.000000,11.000000,1.000000,8.000000,0.000000,0.040000,0.020000,2.000000,0.090000,0.750000,0.200000,4.700000,31.530000,23.420000,3.010000,0.760000,0.070000,0.590000,1.340000,1.330000,0.630000,1.080000,0.230000,0.000000,0.060000,0.060000,0.050000
75%,710.500000,42.000000,2611.000000,2.000000,30.000000,9.500000,3.000000,2.765000,2.725000,2.205000,43.000000,50.500000,22.000000,41.500000,10.000000,139.000000,1081.000000,858.500000,124.500000,43.000000,4.000000,22.500000,0.000000,0.135000,0.090000,5.000000,0.250000,1.530000,0.515000,5.905000,41.630000,33.345000,5.715000,2.720000,0.180000,1.090000,2.040000,2.785000,0.985000,2.175000,0.470000,0.000000,0.140000,0.130000,0.110000
max,792.000000,49.000000,4230.000000,12.000000,97.000000,36.000000,13.000000,12.620000,12.840000,9.340000,151.000000,273.000000,69.000000,234.000000,38.000000,376.000000,3793.000000,3443.000000,1078.000000,297.000000,16.000000,83.000000,152.000000,3.600000,3.600000,22.000000,7.200000,7.350000,3.600000,13.850000,81.570000,74.040000,27.970000,12.100000,3.600000,3.600000,5.290000,8.900000,3.160000,7.680000,1.350000,4.000000,0.940000,0.870000,0.390000

In [27]:
#We can see that the 25% cutoff is 555
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 555].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000
mean,628.616327,35.424490,2172.885714,1.710204,26.122449,8.473469,2.485714,2.697061,2.586408,1.974939,35.571429,57.416327,17.514286,39.869388,8.012245,112.485714,894.444898,706.738776,128.714286,42.477551,3.142857,19.616327,6.330612,0.109673,0.072449,4.195918,0.181918,1.127469,0.370531,4.797959,35.646816,28.180735,4.746571,1.782082,0.131184,0.814449,1.519673,2.368449,0.730367,1.690041,0.343265,0.183592,0.119388,0.115184,0.081878
std,99.506156,9.806708,1012.473584,2.000435,21.915666,8.458451,3.064337,2.867898,2.704372,1.961807,27.634618,59.079397,14.699336,40.087089,7.515820,69.500065,627.405131,536.232934,164.775754,54.642622,3.411648,18.573948,24.862097,0.130807,0.082689,4.196308,0.169990,0.824650,0.346492,1.914123,13.944611,13.088770,4.192146,1.941969,0.121084,0.615144,0.894891,1.993408,0.473994,1.395843,0.285866,0.661699,0.123109,0.117336,0.065828
min,466.000000,10.000000,570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,70.000000,45.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,6.740000,4.330000,0.090000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,535.000000,30.000000,1245.000000,0.000000,9.000000,2.000000,0.000000,0.600000,0.590000,0.570000,15.000000,19.000000,6.000000,13.000000,2.000000,57.000000,420.000000,314.000000,29.000000,4.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.060000,0.520000,0.110000,3.810000,26.430000,18.260000,1.900000,0.260000,0.030000,0.330000,0.870000,0.930000,0.320000,0.670000,0.140000,0.000000,0.030000,0.030000,0.030000
50%,633.000000,38.000000,2104.000000,1.000000,21.000000,6.000000,1.000000,1.640000,1.650000,1.420000,29.000000,36.000000,13.000000,26.000000,6.000000,101.000000,705.000000,525.000000,72.000000,20.000000,2.000000,14.000000,0.000000,0.070000,0.050000,3.000000,0.130000,0.920000,0.250000,4.910000,34.630000,26.590000,3.920000,1.060000,0.110000,0.690000,1.480000,1.520000,0.740000,1.260000,0.280000,0.000000,0.070000,0.070000,0.070000
75%,718.000000,43.000000,3064.000000,3.000000,40.000000,12.000000,3.000000,3.760000,3.640000,2.530000,52.000000,72.000000,26.000000,52.000000,12.000000,161.000000,1291.000000,979.000000,164.000000,58.000000,4.000000,27.000000,0.000000,0.150000,0.120000,7.000000,0.280000,1.660000,0.560000,5.970000,44.260000,36.210000,6.200000,2.880000,0.190000,1.140000,2.150000,3.410000,1.020000,2.300000,0.500000,0.000000,0.160000,0.150000,0.120000
max,792.000000,49.000000,4230.000000,12.000000,97.000000,36.000000,13.000000,12.620000,12.840000,9.340000,151.000000,273.000000,69.000000,234.000000,38.000000,376.000000,3793.000000,3443.000000,1078.000000,297.000000,16.000000,83.000000,152.000000,0.560000,0.480000,22.000000,0.660000,3.400000,1.470000,10.100000,81.570000,74.040000,23.430000,12.100000,0.550000,2.820000,4.660000,8.900000,2.290000,6.870000,1.350000,3.300000,0.490000,0.500000,0.360000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/CHAMPcomplete25.csv")