Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          79
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,0.0
mean,22.481013,47.291139,14.594937,22.189873,1.531646,1130.341772,60.126582,NaN
std,20.488809,46.686942,14.102663,24.483420,1.953534,943.465677,53.363141,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,2.500000,5.000000,1.000000,3.000000,0.000000,125.500000,7.000000,NaN
50%,23.000000,34.000000,12.000000,14.000000,1.000000,956.000000,57.000000,NaN
75%,38.500000,76.500000,25.500000,34.500000,3.000000,1980.000000,102.500000,NaN
max,69.000000,155.000000,59.000000,125.000000,7.000000,2709.000000,209.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 1715)
dfDdef["ID"] = (dfDdef.index + 1715)
dfDatt["ID"] = (dfDatt.index + 1715)
dfDpas["ID"] = (dfDpas.index + 1715) #should end at id no 1793
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 1837
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 1860
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 1940
dfMdft.head(300) #to check final id number

              Name            Team  App  Mins    ID
0      J. Moutinho  Sporting Braga   24  1587  1861
1       P. Moreira       FC Arouca    7     0  1862
2         J. Mário         Benfica    2   155  1863
3            Bruma         Benfica   30  1629  1864
4       RLR. Lopes         Tondela   14  1134  1865
..             ...             ...  ...   ...   ...
75           G. Sá       Famalicão   31  2383  1936
76     GBG. Beleza     Gil Vicente    3     0  1937
77      AAA. Assis      Moreirense    5    13  1938
78        D. Costa     Gil Vicente    6    74  1939
79  RRR. Rodrigues     Gil Vicente    1     9  1940

[80 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/ligaportugal/LIGAPmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,I. Marcano,FC Porto,11,943,1715,0,7.0,1,1,0.6426,0.648,0.2803,11,43,13,29,1,45,760,678,90,10,1,4,Defender,NaN
1,N. Otamendi,Benfica,32,2709,1716,2,29.0,12,6,3.8829,3.825,1.9409,53,107,59,125,5,209,2014,1804,212,2,2,10,Defender,NaN
2,P. Oliveira,Sporting Braga,24,1713,1717,0,15.0,6,1,2.1248,2.084,0.3862,23,128,27,45,0,77,1147,980,145,1,0,1,Defender,NaN
3,A. Santos,AVS - Futebol SAD,14,678,1718,0,1.0,0,0,0.0115,0.011,0.0247,9,70,4,19,0,29,238,196,38,0,0,0,Defender,NaN
4,L. Rocha,Vizela,30,2490,1719,0,10.0,2,0,0.3348,0.416,0.1703,32,135,18,51,4,97,1091,934,106,1,1,3,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,G. Sá,Famalicão,31,2383,1936,5,34.0,11,4,3.4202,3.351,2.6117,43,21,11,49,9,185,804,584,77,55,7,35,Midfielder,NaN
222,GBG. Beleza,Gil Vicente,3,0,1937,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
223,AAA. Assis,Moreirense,5,13,1938,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,4,3,0,0,0,0,Midfielder,NaN
224,D. Costa,Gil Vicente,6,74,1939,0,NaN,0,0,0.0000,NaN,0.0000,0,5,1,0,0,1,27,19,10,0,0,0,Midfielder,NaN
225,RRR. Rodrigues,Gil Vicente,1,9,1940,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,1,0,1,5,1,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,I. Marcano,FC Porto,11,943,1715,0,7.0,1,1,0.6426,0.648,0.2803,11,43,13,29,1,45,760,678,90,10,1,4,Defender,0.0
1,N. Otamendi,Benfica,32,2709,1716,2,29.0,12,6,3.8829,3.825,1.9409,53,107,59,125,5,209,2014,1804,212,2,2,10,Defender,0.0
2,P. Oliveira,Sporting Braga,24,1713,1717,0,15.0,6,1,2.1248,2.084,0.3862,23,128,27,45,0,77,1147,980,145,1,0,1,Defender,0.0
3,A. Santos,AVS - Futebol SAD,14,678,1718,0,1.0,0,0,0.0115,0.011,0.0247,9,70,4,19,0,29,238,196,38,0,0,0,Defender,0.0
4,L. Rocha,Vizela,30,2490,1719,0,10.0,2,0,0.3348,0.416,0.1703,32,135,18,51,4,97,1091,934,106,1,1,3,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,RRR. Ribeiro,Famalicão,3,0,1931,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
217,A. Rodrigues,Tondela,9,14,1932,0,1.0,0,0,0.0684,0.068,0.0000,0,0,0,2,0,3,4,2,0,1,0,0,Midfielder,0.0
218,M. De Amorim,Famalicão,30,982,1933,1,14.0,2,1,1.0420,0.997,1.1941,38,8,14,8,3,84,412,343,24,13,3,16,Midfielder,0.0
219,M. Ribeiro,Boavista,18,361,1934,0,2.0,0,0,0.2637,0.263,0.3398,10,5,1,3,1,20,117,87,15,14,0,5,Midfielder,0.0
220,LGL. Gomes,Estoril Praia,1,0,1935,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,1715,Defender,I. Marcano,FC Porto,11,943,0,7.0,1,1,0.6426,0.648,0.2803,11,43,13,29,1,45,760,678,90,10,1,4,0.0
1,1716,Defender,N. Otamendi,Benfica,32,2709,2,29.0,12,6,3.8829,3.825,1.9409,53,107,59,125,5,209,2014,1804,212,2,2,10,0.0
2,1717,Defender,P. Oliveira,Sporting Braga,24,1713,0,15.0,6,1,2.1248,2.084,0.3862,23,128,27,45,0,77,1147,980,145,1,0,1,0.0
3,1718,Defender,A. Santos,AVS - Futebol SAD,14,678,0,1.0,0,0,0.0115,0.011,0.0247,9,70,4,19,0,29,238,196,38,0,0,0,0.0
4,1719,Defender,L. Rocha,Vizela,30,2490,0,10.0,2,0,0.3348,0.416,0.1703,32,135,18,51,4,97,1091,934,106,1,1,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,1931,Midfielder,RRR. Ribeiro,Famalicão,3,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
217,1932,Midfielder,A. Rodrigues,Tondela,9,14,0,1.0,0,0,0.0684,0.068,0.0000,0,0,0,2,0,3,4,2,0,1,0,0,0.0
218,1933,Midfielder,M. De Amorim,Famalicão,30,982,1,14.0,2,1,1.0420,0.997,1.1941,38,8,14,8,3,84,412,343,24,13,3,16,0.0
219,1934,Midfielder,M. Ribeiro,Boavista,18,361,0,2.0,0,0,0.2637,0.263,0.3398,10,5,1,3,1,20,117,87,15,14,0,5,0.0
220,1935,Midfielder,LGL. Gomes,Estoril Praia,1,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000
mean,1827.500000,19.159292,1006.809735,0.991150,12.123894,4.212389,1.415929,1.315448,1.208704,0.905581,17.172566,23.415929,8.858407,14.694690,3.115044,52.115044,432.420354,353.203540,53.358407,18.199115,1.747788,9.517699,2.336283
std,65.384759,11.026889,898.074471,1.763812,16.667004,6.273686,2.665752,2.343822,2.040509,1.249541,18.583896,34.329961,11.318317,19.339302,4.968795,50.990936,460.633791,395.865491,80.706325,28.389359,2.711805,12.708078,11.340085
min,1715.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1771.250000,9.000000,125.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.250000,0.000000,1.000000,0.000000,5.000000,44.250000,36.000000,2.250000,0.000000,0.000000,0.000000,0.000000
50%,1827.500000,23.000000,826.000000,0.000000,6.000000,2.000000,0.000000,0.386900,0.387500,0.348250,9.000000,9.000000,4.000000,7.000000,1.000000,39.000000,280.000000,218.500000,21.000000,4.000000,1.000000,5.000000,0.000000
75%,1883.750000,30.000000,1740.500000,2.000000,16.000000,6.000000,2.000000,1.534300,1.451250,1.371475,31.750000,28.000000,13.000000,21.000000,4.000000,90.000000,752.250000,582.250000,75.750000,22.000000,2.000000,14.000000,0.000000
max,1940.000000,33.000000,2875.000000,13.000000,102.000000,37.000000,19.000000,18.133200,15.970000,7.338600,69.000000,155.000000,59.000000,125.000000,38.000000,217.000000,2074.000000,1888.000000,546.000000,144.000000,17.000000,74.000000,84.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,1715,Defender,I. Marcano,FC Porto,11,943,0,7.0,1,1,0.6426,0.648,0.2803,11,43,13,29,1,45,760,678,90,10,1,4,0.0,0.095440,0.000000,1,0.095440,0.668081,0.095440,4.294804,72.534464,64.708378,8.589608,0.954401,0.095440,0.381760,1.049841,4.103924,1.240721,2.767762,0.095440,0.0,0.061330,0.061845,0.026752
1,1716,Defender,N. Otamendi,Benfica,32,2709,2,29.0,12,6,3.8829,3.825,1.9409,53,107,59,125,5,209,2014,1804,212,2,2,10,0.0,0.199336,0.066445,8,0.265781,0.963455,0.398671,6.943522,66.910299,59.933555,7.043189,0.066445,0.066445,0.332226,1.760797,3.554817,1.960133,4.152824,0.166113,0.0,0.129000,0.127076,0.064482
2,1717,Defender,P. Oliveira,Sporting Braga,24,1713,0,15.0,6,1,2.1248,2.084,0.3862,23,128,27,45,0,77,1147,980,145,1,0,1,0.0,0.052539,0.000000,1,0.052539,0.788091,0.315236,4.045534,60.262697,51.488616,7.618214,0.052539,0.000000,0.052539,1.208406,6.725044,1.418564,2.364273,0.000000,0.0,0.111636,0.109492,0.020291
3,1718,Defender,A. Santos,AVS - Futebol SAD,14,678,0,1.0,0,0,0.0115,0.011,0.0247,9,70,4,19,0,29,238,196,38,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.132743,0.000000,3.849558,31.592920,26.017699,5.044248,0.000000,0.000000,0.000000,1.194690,9.292035,0.530973,2.522124,0.000000,0.0,0.001527,0.001460,0.003279
4,1719,Defender,L. Rocha,Vizela,30,2490,0,10.0,2,0,0.3348,0.416,0.1703,32,135,18,51,4,97,1091,934,106,1,1,3,0.0,0.000000,0.000000,0,0.000000,0.361446,0.072289,3.506024,39.433735,33.759036,3.831325,0.036145,0.036145,0.108434,1.156627,4.879518,0.650602,1.843373,0.144578,0.0,0.012101,0.015036,0.006155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,1931,Midfielder,RRR. Ribeiro,Famalicão,3,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,1932,Midfielder,A. Rodrigues,Tondela,9,14,0,1.0,0,0,0.0684,0.068,0.0000,0,0,0,2,0,3,4,2,0,1,0,0,0.0,0.000000,0.000000,0,0.000000,6.428571,0.000000,19.285714,25.714286,12.857143,0.000000,6.428571,0.000000,0.000000,0.000000,0.000000,0.000000,12.857143,0.000000,0.0,0.439714,0.437143,0.000000
218,1933,Midfielder,M. De Amorim,Famalicão,30,982,1,14.0,2,1,1.0420,0.997,1.1941,38,8,14,8,3,84,412,343,24,13,3,16,0.0,0.091650,0.091650,2,0.183299,1.283096,0.183299,7.698574,37.759674,31.435845,2.199593,1.191446,0.274949,1.466395,3.482688,0.733198,1.283096,0.733198,0.274949,0.0,0.095499,0.091375,0.109439
219,1934,Midfielder,M. Ribeiro,Boavista,18,361,0,2.0,0,0,0.2637,0.263,0.3398,10,5,1,3,1,20,117,87,15,14,0,5,0.0,0.000000,0.000000,0,0.000000,0.498615,0.000000,4.986150,29.168975,21.689751,3.739612,3.490305,0.000000,1.246537,2.493075,1.246537,0.249307,0.747922,0.249307,0.0,0.065742,0.065568,0.084715
220,1935,Midfielder,LGL. Gomes,Estoril Praia,1,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,1715,Defender,I. Marcano,FC Porto,11,943,0,7.0,1,1,0.64,0.65,0.28,11,43,13,29,1,45,760,678,90,10,1,4,0.0,0.10,0.00,1,0.10,0.67,0.10,4.29,72.53,64.71,8.59,0.95,0.10,0.38,1.05,4.10,1.24,2.77,0.10,0.0,0.06,0.06,0.03
1,1716,Defender,N. Otamendi,Benfica,32,2709,2,29.0,12,6,3.88,3.82,1.94,53,107,59,125,5,209,2014,1804,212,2,2,10,0.0,0.20,0.07,8,0.27,0.96,0.40,6.94,66.91,59.93,7.04,0.07,0.07,0.33,1.76,3.55,1.96,4.15,0.17,0.0,0.13,0.13,0.06
2,1717,Defender,P. Oliveira,Sporting Braga,24,1713,0,15.0,6,1,2.12,2.08,0.39,23,128,27,45,0,77,1147,980,145,1,0,1,0.0,0.05,0.00,1,0.05,0.79,0.32,4.05,60.26,51.49,7.62,0.05,0.00,0.05,1.21,6.73,1.42,2.36,0.00,0.0,0.11,0.11,0.02
3,1718,Defender,A. Santos,AVS - Futebol SAD,14,678,0,1.0,0,0,0.01,0.01,0.02,9,70,4,19,0,29,238,196,38,0,0,0,0.0,0.00,0.00,0,0.00,0.13,0.00,3.85,31.59,26.02,5.04,0.00,0.00,0.00,1.19,9.29,0.53,2.52,0.00,0.0,0.00,0.00,0.00
4,1719,Defender,L. Rocha,Vizela,30,2490,0,10.0,2,0,0.33,0.42,0.17,32,135,18,51,4,97,1091,934,106,1,1,3,0.0,0.00,0.00,0,0.00,0.36,0.07,3.51,39.43,33.76,3.83,0.04,0.04,0.11,1.16,4.88,0.65,1.84,0.14,0.0,0.01,0.02,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,1931,Midfielder,RRR. Ribeiro,Famalicão,3,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
217,1932,Midfielder,A. Rodrigues,Tondela,9,14,0,1.0,0,0,0.07,0.07,0.00,0,0,0,2,0,3,4,2,0,1,0,0,0.0,0.00,0.00,0,0.00,6.43,0.00,19.29,25.71,12.86,0.00,6.43,0.00,0.00,0.00,0.00,0.00,12.86,0.00,0.0,0.44,0.44,0.00
218,1933,Midfielder,M. De Amorim,Famalicão,30,982,1,14.0,2,1,1.04,1.00,1.19,38,8,14,8,3,84,412,343,24,13,3,16,0.0,0.09,0.09,2,0.18,1.28,0.18,7.70,37.76,31.44,2.20,1.19,0.27,1.47,3.48,0.73,1.28,0.73,0.27,0.0,0.10,0.09,0.11
219,1934,Midfielder,M. Ribeiro,Boavista,18,361,0,2.0,0,0,0.26,0.26,0.34,10,5,1,3,1,20,117,87,15,14,0,5,0.0,0.00,0.00,0,0.00,0.50,0.00,4.99,29.17,21.69,3.74,3.49,0.00,1.25,2.49,1.25,0.25,0.75,0.25,0.0,0.07,0.07,0.08
220,1935,Midfielder,LGL. Gomes,Estoril Praia,1,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00

Adding and moving "League" column

In [18]:
#label
leagueLabel = "Liga Portugal"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,1715,Defender,Liga Portugal,I. Marcano,FC Porto,11,943,0,7.0,1,1,0.64,0.65,0.28,11,43,13,29,1,45,760,678,90,10,1,4,0.0,0.10,0.00,1,0.10,0.67,0.10,4.29,72.53,64.71,8.59,0.95,0.10,0.38,1.05,4.10,1.24,2.77,0.10,0.0,0.06,0.06,0.03
1,1716,Defender,Liga Portugal,N. Otamendi,Benfica,32,2709,2,29.0,12,6,3.88,3.82,1.94,53,107,59,125,5,209,2014,1804,212,2,2,10,0.0,0.20,0.07,8,0.27,0.96,0.40,6.94,66.91,59.93,7.04,0.07,0.07,0.33,1.76,3.55,1.96,4.15,0.17,0.0,0.13,0.13,0.06
2,1717,Defender,Liga Portugal,P. Oliveira,Sporting Braga,24,1713,0,15.0,6,1,2.12,2.08,0.39,23,128,27,45,0,77,1147,980,145,1,0,1,0.0,0.05,0.00,1,0.05,0.79,0.32,4.05,60.26,51.49,7.62,0.05,0.00,0.05,1.21,6.73,1.42,2.36,0.00,0.0,0.11,0.11,0.02
3,1718,Defender,Liga Portugal,A. Santos,AVS - Futebol SAD,14,678,0,1.0,0,0,0.01,0.01,0.02,9,70,4,19,0,29,238,196,38,0,0,0,0.0,0.00,0.00,0,0.00,0.13,0.00,3.85,31.59,26.02,5.04,0.00,0.00,0.00,1.19,9.29,0.53,2.52,0.00,0.0,0.00,0.00,0.00
4,1719,Defender,Liga Portugal,L. Rocha,Vizela,30,2490,0,10.0,2,0,0.33,0.42,0.17,32,135,18,51,4,97,1091,934,106,1,1,3,0.0,0.00,0.00,0,0.00,0.36,0.07,3.51,39.43,33.76,3.83,0.04,0.04,0.11,1.16,4.88,0.65,1.84,0.14,0.0,0.01,0.02,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,1931,Midfielder,Liga Portugal,RRR. Ribeiro,Famalicão,3,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
217,1932,Midfielder,Liga Portugal,A. Rodrigues,Tondela,9,14,0,1.0,0,0,0.07,0.07,0.00,0,0,0,2,0,3,4,2,0,1,0,0,0.0,0.00,0.00,0,0.00,6.43,0.00,19.29,25.71,12.86,0.00,6.43,0.00,0.00,0.00,0.00,0.00,12.86,0.00,0.0,0.44,0.44,0.00
218,1933,Midfielder,Liga Portugal,M. De Amorim,Famalicão,30,982,1,14.0,2,1,1.04,1.00,1.19,38,8,14,8,3,84,412,343,24,13,3,16,0.0,0.09,0.09,2,0.18,1.28,0.18,7.70,37.76,31.44,2.20,1.19,0.27,1.47,3.48,0.73,1.28,0.73,0.27,0.0,0.10,0.09,0.11
219,1934,Midfielder,Liga Portugal,M. Ribeiro,Boavista,18,361,0,2.0,0,0,0.26,0.26,0.34,10,5,1,3,1,20,117,87,15,14,0,5,0.0,0.00,0.00,0,0.00,0.50,0.00,4.99,29.17,21.69,3.74,3.49,0.00,1.25,2.49,1.25,0.25,0.75,0.25,0.0,0.07,0.07,0.08
220,1935,Midfielder,Liga Portugal,LGL. Gomes,Estoril Praia,1,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/LIGAPcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,1822.365169,22.865169,1273.247191,1.258427,15.325843,5.348315,1.797753,1.667640,1.532079,1.149382,21.719101,29.606742,11.219101,18.573034,3.943820,65.926966,547.191011,446.966292,67.533708,23.000000,2.219101,12.056180,2.966292,0.133371,0.081629,3.056180,0.215393,1.138876,0.389213,4.803652,36.781966,29.882022,4.377865,1.738596,0.163989,0.892528,1.499382,2.025112,0.721011,1.371854,0.299888,0.232978,0.116798,0.109213,0.080618
std,65.095812,9.058119,830.014230,1.901698,17.450349,6.627457,2.888433,2.528642,2.190150,1.304994,18.465720,36.280956,11.679925,20.101375,5.302935,49.002367,455.326340,396.930595,85.600844,30.251675,2.880340,13.219024,12.711887,0.197627,0.122954,4.187308,0.250935,0.972571,0.386882,2.072091,14.822054,14.463599,4.032641,2.045068,0.229040,0.751972,0.916299,2.077135,0.538654,1.152084,0.386187,0.782061,0.147646,0.134044,0.082168
min,1715.000000,1.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.010000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1763.250000,16.000000,453.000000,0.000000,4.000000,1.000000,0.000000,0.192500,0.135000,0.162500,4.000000,5.250000,2.000000,4.000000,0.000000,19.250000,155.500000,116.000000,10.250000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.432500,0.070000,3.750000,26.147500,18.895000,1.722500,0.060000,0.000000,0.330000,0.910000,0.715000,0.300000,0.550000,0.000000,0.000000,0.020000,0.020000,0.020000
50%,1819.500000,26.000000,1273.000000,0.000000,11.000000,3.000000,1.000000,0.700000,0.720000,0.695000,17.500000,16.000000,8.000000,11.500000,2.000000,64.000000,442.500000,331.500000,36.000000,10.000000,1.000000,8.000000,0.000000,0.040000,0.000000,2.000000,0.130000,0.825000,0.270000,4.765000,35.820000,28.070000,3.605000,1.010000,0.090000,0.775000,1.520000,1.255000,0.665000,1.085000,0.175000,0.000000,0.060000,0.055000,0.065000
75%,1879.750000,30.000000,1943.250000,2.000000,18.750000,7.000000,2.750000,2.107500,2.102500,1.900000,35.750000,37.750000,18.000000,25.000000,5.000000,99.250000,833.000000,679.500000,93.750000,37.000000,3.000000,17.750000,0.000000,0.197500,0.110000,4.000000,0.347500,1.697500,0.637500,5.872500,44.125000,36.350000,5.635000,2.707500,0.237500,1.327500,2.047500,2.760000,1.100000,1.965000,0.410000,0.000000,0.160000,0.150000,0.100000
max,1936.000000,33.000000,2875.000000,13.000000,102.000000,37.000000,19.000000,18.130000,15.970000,7.340000,69.000000,155.000000,59.000000,125.000000,38.000000,217.000000,2074.000000,1888.000000,546.000000,144.000000,17.000000,74.000000,84.000000,1.020000,0.600000,26.000000,1.040000,4.390000,1.560000,12.050000,82.850000,74.340000,23.670000,9.920000,1.680000,4.290000,3.910000,14.400000,2.130000,6.030000,2.240000,4.000000,0.730000,0.640000,0.440000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/LIGAPcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000
mean,1827.500000,19.159292,1006.809735,0.991150,12.123894,4.212389,1.415929,1.315398,1.208451,0.905752,17.172566,23.415929,8.858407,14.694690,3.115044,52.115044,432.420354,353.203540,53.358407,18.199115,1.747788,9.517699,2.336283,0.105044,0.064292,2.407080,0.169646,1.043673,0.306549,4.271195,32.421947,26.212212,3.763673,1.580708,0.129159,0.737876,1.338451,1.924956,0.597522,1.264823,0.259425,0.183496,0.096593,0.090354,0.064425
std,65.384759,11.026889,898.074471,1.763812,16.667004,6.273686,2.665752,2.343556,2.040509,1.249320,18.583896,34.329961,11.318317,19.339302,4.968795,50.990936,460.633791,395.865491,80.706325,28.389359,2.711805,12.708078,11.340085,0.183611,0.114071,3.919495,0.239438,1.199997,0.378417,2.858654,18.246298,16.704385,4.065748,2.123053,0.213978,0.788796,1.243435,3.552611,0.583869,1.530240,0.439738,0.700186,0.140508,0.128405,0.079554
min,1715.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1771.250000,9.000000,125.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.250000,0.000000,1.000000,0.000000,5.000000,44.250000,36.000000,2.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.840000,22.047500,13.792500,0.722500,0.000000,0.000000,0.000000,0.047500,0.350000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1827.500000,23.000000,826.000000,0.000000,6.000000,2.000000,0.000000,0.385000,0.385000,0.350000,9.000000,9.000000,4.000000,7.000000,1.000000,39.000000,280.000000,218.500000,21.000000,4.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.060000,0.685000,0.140000,4.380000,32.745000,25.315000,3.015000,0.670000,0.035000,0.580000,1.210000,1.000000,0.510000,0.895000,0.100000,0.000000,0.040000,0.040000,0.040000
75%,1883.750000,30.000000,1740.500000,2.000000,16.000000,6.000000,2.000000,1.530000,1.450000,1.372500,31.750000,28.000000,13.000000,21.000000,4.000000,90.000000,752.250000,582.250000,75.750000,22.000000,2.000000,14.000000,0.000000,0.140000,0.090000,3.000000,0.270000,1.557500,0.525000,5.730000,42.820000,35.562500,5.215000,2.525000,0.207500,1.217500,1.942500,2.500000,1.022500,1.840000,0.337500,0.000000,0.130000,0.120000,0.090000
max,1940.000000,33.000000,2875.000000,13.000000,102.000000,37.000000,19.000000,18.130000,15.970000,7.340000,69.000000,155.000000,59.000000,125.000000,38.000000,217.000000,2074.000000,1888.000000,546.000000,144.000000,17.000000,74.000000,84.000000,1.020000,0.600000,26.000000,1.040000,7.500000,1.560000,19.290000,82.850000,74.340000,23.670000,11.250000,1.680000,4.290000,7.500000,45.000000,2.950000,12.860000,3.750000,4.000000,0.730000,0.640000,0.440000

In [27]:
#We can see that the 25% cutoff is 125.75, so we round up to 126
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 126].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000
mean,1822.988166,23.591716,1335.733728,1.325444,16.082840,5.621302,1.887574,1.751775,1.609112,1.209467,22.798817,30.952663,11.792899,19.402367,4.142012,69.059172,574.118343,469.005917,70.911243,24.147929,2.331361,12.639053,3.106509,0.135976,0.085976,3.213018,0.222367,1.150947,0.400059,4.726686,36.741657,29.872781,4.405740,1.768935,0.166805,0.890000,1.510355,1.925207,0.737515,1.298047,0.306805,0.227633,0.119231,0.111361,0.084083
std,65.437901,8.439853,805.072849,1.928947,17.587001,6.692108,2.936697,2.567881,2.221244,1.312374,18.328867,36.734214,11.711754,20.292891,5.368887,48.310714,451.656802,395.374273,86.560111,30.619332,2.912865,13.311958,13.031117,0.194827,0.124706,4.240066,0.249636,0.959647,0.385788,1.986052,14.941488,14.529152,4.089794,2.028034,0.223205,0.706716,0.893342,1.801456,0.537499,1.043996,0.379199,0.772138,0.147656,0.133332,0.082595
min,1715.000000,2.000000,149.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.010000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1763.000000,18.000000,662.000000,0.000000,4.000000,1.000000,0.000000,0.220000,0.230000,0.220000,6.000000,6.000000,2.000000,5.000000,0.000000,24.000000,180.000000,140.000000,13.000000,1.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.440000,0.090000,3.750000,26.110000,18.680000,1.730000,0.100000,0.000000,0.340000,0.930000,0.690000,0.320000,0.520000,0.000000,0.000000,0.020000,0.020000,0.030000
50%,1820.000000,27.000000,1361.000000,1.000000,11.000000,3.000000,1.000000,0.760000,0.770000,0.790000,20.000000,17.000000,8.000000,14.000000,3.000000,68.000000,470.000000,356.000000,40.000000,12.000000,1.000000,8.000000,0.000000,0.050000,0.040000,2.000000,0.140000,0.810000,0.290000,4.750000,35.640000,27.980000,3.590000,1.060000,0.100000,0.800000,1.530000,1.250000,0.670000,1.030000,0.190000,0.000000,0.060000,0.060000,0.070000
75%,1881.000000,30.000000,2014.000000,2.000000,19.000000,8.000000,3.000000,2.270000,2.170000,1.940000,37.000000,39.000000,18.000000,26.000000,5.000000,102.000000,851.000000,710.000000,97.000000,38.000000,3.000000,18.000000,0.000000,0.200000,0.120000,4.000000,0.350000,1.710000,0.640000,5.740000,44.180000,37.280000,5.650000,2.820000,0.240000,1.320000,2.010000,2.760000,1.150000,1.850000,0.420000,0.000000,0.160000,0.150000,0.110000
max,1936.000000,33.000000,2875.000000,13.000000,102.000000,37.000000,19.000000,18.130000,15.970000,7.340000,69.000000,155.000000,59.000000,125.000000,38.000000,217.000000,2074.000000,1888.000000,546.000000,144.000000,17.000000,74.000000,84.000000,1.020000,0.600000,26.000000,1.040000,4.390000,1.560000,9.900000,82.850000,74.340000,23.670000,9.920000,1.680000,4.290000,3.910000,9.290000,2.130000,6.030000,2.240000,4.000000,0.730000,0.640000,0.440000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/LIGAPcomplete25.csv")