Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/eredivisie/EREmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name               0
Team               0
Tackles            0
Clearances         0
Interceptions      0
aerialsWon         0
Blocks             0
Mins               0
duelsWon           0
unnamed          100
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,0.0
mean,28.460000,69.370000,18.720000,27.080000,2.480000,1429.940000,73.760000,NaN
std,23.540818,63.312541,15.645104,28.736237,3.003298,1024.545248,57.064047,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,7.000000,11.750000,4.000000,6.000000,0.000000,417.000000,22.750000,NaN
50%,27.000000,57.500000,16.000000,19.000000,1.000000,1653.500000,73.000000,NaN
75%,45.250000,103.500000,32.000000,40.000000,4.000000,2201.000000,110.500000,NaN
max,104.000000,256.000000,63.000000,152.000000,14.000000,3232.000000,222.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 793)
dfDdef["ID"] = (dfDdef.index + 793)
dfDatt["ID"] = (dfDatt.index + 793)
dfDpas["ID"] = (dfDpas.index + 793) #should end at id no 892
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 941
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 988
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 1119
dfMdft.head(300) #to check final id number

                   Name               Team  App  Mins    ID
0             L. Schöne       NEC Nijmegen   34   328   989
1          J. de Guzmán   Sparta Rotterdam   23    45   990
2            I. Perišić      PSV Eindhoven   29  1804   991
3        M. Kieftenbeld         SC Cambuur    1    26   992
4           D. Klaassen           AFC Ajax   31  2182   993
..                  ...                ...  ...   ...   ...
126   HKH. Korkmazyürek    Fortuna Sittard    3     4  1115
127  T. van den Elshout          Feyenoord    1     0  1116
128      UvU. van Aalst  Willem II Tilburg   14    37  1117
129         DVD. Visser         SC Cambuur    1     0  1118
130    ABA. Burak Sayin    Fortuna Sittard    1     3  1119

[131 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/eredivisie/EREdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/eredivisie/EREforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/eredivisie/EREgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/eredivisie/EREmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,N. Viergever,FC Utrecht,33,2951,793,1,14.0,7,3,3.4994,3.494,1.5018,52,159,28,53,1,120,1818,1569,180,2,1,7,Defender,NaN
1,B. Nuytinck,NEC Nijmegen,27,1699,794,0,13.0,4,1,1.1339,1.133,0.6226,27,120,16,59,3,96,1060,941,124,2,1,4,Defender,NaN
2,P. van Aanholt,Sparta Rotterdam,21,1679,795,0,19.0,1,0,0.6422,0.648,2.1121,29,44,21,7,7,48,655,544,57,24,1,18,Defender,NaN
3,M. Peersman,FC Groningen,26,1814,796,2,4.0,0,0,0.2082,0.208,1.2633,36,91,22,40,1,123,1041,831,114,26,2,10,Defender,NaN
4,I. Pinto,Fortuna Sittard,31,2514,797,3,5.0,1,0,0.2480,0.248,4.4972,50,76,24,16,1,91,931,682,187,95,2,26,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,J. Faberski,PEC Zwolle,1,0,1088,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
296,TKT. Kraaijeveld,Feyenoord,1,0,1089,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
297,R. Weijenberg,Go Ahead Eagles,26,344,1090,0,3.0,0,0,0.7606,0.760,0.5681,17,13,2,5,1,31,169,142,16,0,1,5,Midfielder,NaN
298,T. Schenkhuizen,Fortuna Sittard,17,5,1091,0,1.0,0,0,0.0449,0.045,0.0058,0,0,0,0,0,0,6,4,0,0,0,0,Midfielder,NaN
299,D. Mathieu,Willem II Tilburg,2,0,1092,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,N. Viergever,FC Utrecht,33,2951,793,1,14.0,7,3,3.4994,3.494,1.5018,52,159,28,53,1,120,1818,1569,180,2,1,7,Defender,0.0
1,B. Nuytinck,NEC Nijmegen,27,1699,794,0,13.0,4,1,1.1339,1.133,0.6226,27,120,16,59,3,96,1060,941,124,2,1,4,Defender,0.0
2,P. van Aanholt,Sparta Rotterdam,21,1679,795,0,19.0,1,0,0.6422,0.648,2.1121,29,44,21,7,7,48,655,544,57,24,1,18,Defender,0.0
3,M. Peersman,FC Groningen,26,1814,796,2,4.0,0,0,0.2082,0.208,1.2633,36,91,22,40,1,123,1041,831,114,26,2,10,Defender,0.0
4,I. Pinto,Fortuna Sittard,31,2514,797,3,5.0,1,0,0.2480,0.248,4.4972,50,76,24,16,1,91,931,682,187,95,2,26,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,IAI. Ahmed,SC Heerenveen,13,8,1110,0,0.0,0,0,0.0000,0.000,0.0000,1,0,0,0,0,1,4,2,0,0,0,0,Midfielder,0.0
318,SSS. Steur,AFC Ajax,3,10,1111,0,0.0,0,0,0.0000,0.000,0.0000,0,2,0,0,0,1,3,2,0,0,0,0,Midfielder,0.0
319,D. van der Werff,FC Groningen,18,22,1112,0,2.0,1,0,0.2031,0.203,0.1576,0,0,0,0,1,0,5,5,0,2,0,1,Midfielder,0.0
320,GRG. Reiziger,PEC Zwolle,4,0,1113,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
321,L. Tunjić,Fortuna Sittard,31,481,1114,1,9.0,3,1,0.7644,0.790,0.6068,7,4,4,7,2,25,124,101,9,28,0,12,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,793,Defender,N. Viergever,FC Utrecht,33,2951,1,14.0,7,3,3.4994,3.494,1.5018,52,159,28,53,1,120,1818,1569,180,2,1,7,0.0
1,794,Defender,B. Nuytinck,NEC Nijmegen,27,1699,0,13.0,4,1,1.1339,1.133,0.6226,27,120,16,59,3,96,1060,941,124,2,1,4,0.0
2,795,Defender,P. van Aanholt,Sparta Rotterdam,21,1679,0,19.0,1,0,0.6422,0.648,2.1121,29,44,21,7,7,48,655,544,57,24,1,18,0.0
3,796,Defender,M. Peersman,FC Groningen,26,1814,2,4.0,0,0,0.2082,0.208,1.2633,36,91,22,40,1,123,1041,831,114,26,2,10,0.0
4,797,Defender,I. Pinto,Fortuna Sittard,31,2514,3,5.0,1,0,0.2480,0.248,4.4972,50,76,24,16,1,91,931,682,187,95,2,26,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,1110,Midfielder,IAI. Ahmed,SC Heerenveen,13,8,0,0.0,0,0,0.0000,0.000,0.0000,1,0,0,0,0,1,4,2,0,0,0,0,0.0
318,1111,Midfielder,SSS. Steur,AFC Ajax,3,10,0,0.0,0,0,0.0000,0.000,0.0000,0,2,0,0,0,1,3,2,0,0,0,0,0.0
319,1112,Midfielder,D. van der Werff,FC Groningen,18,22,0,2.0,1,0,0.2031,0.203,0.1576,0,0,0,0,1,0,5,5,0,2,0,1,0.0
320,1113,Midfielder,GRG. Reiziger,PEC Zwolle,4,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
321,1114,Midfielder,L. Tunjić,Fortuna Sittard,31,481,1,9.0,3,1,0.7644,0.790,0.6068,7,4,4,7,2,25,124,101,9,28,0,12,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000
mean,956.000000,22.740061,1120.975535,1.195719,14.000000,4.996942,1.633028,1.508443,1.439006,1.256394,18.568807,30.110092,9.489297,17.189602,3.831804,53.642202,504.223242,409.788991,69.990826,21.146789,1.889908,11.012232,4.272171
std,94.540996,11.308679,987.078207,1.854752,18.127869,7.515015,2.961907,2.485704,2.312538,1.660469,21.143115,45.373570,12.372753,25.596218,5.299540,54.310602,533.095540,457.660188,124.674877,38.198342,2.965050,13.524569,19.264925
min,793.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,874.500000,15.000000,93.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005650,0.000000,1.000000,0.000000,1.000000,0.000000,4.000000,46.500000,35.000000,3.000000,0.000000,0.000000,0.000000,0.000000
50%,956.000000,26.000000,1085.000000,0.000000,7.000000,2.000000,0.000000,0.554500,0.574000,0.551600,11.000000,12.000000,4.000000,8.000000,2.000000,40.000000,369.000000,290.000000,25.000000,4.000000,1.000000,5.000000,0.000000
75%,1037.500000,32.000000,1905.500000,2.000000,20.500000,7.000000,2.000000,1.844450,1.707500,1.789000,29.000000,35.500000,15.000000,22.500000,6.000000,87.500000,782.000000,630.500000,78.000000,24.000000,2.000000,18.000000,0.000000
max,1119.000000,38.000000,3450.000000,11.000000,98.000000,48.000000,27.000000,17.034700,14.423000,9.785200,114.000000,256.000000,63.000000,233.000000,26.000000,300.000000,2892.000000,2614.000000,890.000000,291.000000,15.000000,76.000000,140.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,793,Defender,N. Viergever,FC Utrecht,33,2951,1,14.0,7,3,3.4994,3.494,1.5018,52,159,28,53,1,120,1818,1569,180,2,1,7,0.0,0.091494,0.030498,4,0.121993,0.426974,0.213487,3.659776,55.445612,47.851576,5.489665,0.060996,0.030498,0.213487,1.585903,4.849204,0.853948,1.616401,0.030498,0.0,0.106725,0.106560,0.045802
1,794,Defender,B. Nuytinck,NEC Nijmegen,27,1699,0,13.0,4,1,1.1339,1.133,0.6226,27,120,16,59,3,96,1060,941,124,2,1,4,0.0,0.052972,0.000000,1,0.052972,0.688640,0.211889,5.085344,56.150677,49.846969,6.568570,0.105945,0.052972,0.211889,1.430253,6.356680,0.847557,3.125368,0.158917,0.0,0.060065,0.060018,0.032981
2,795,Defender,P. van Aanholt,Sparta Rotterdam,21,1679,0,19.0,1,0,0.6422,0.648,2.1121,29,44,21,7,7,48,655,544,57,24,1,18,0.0,0.000000,0.000000,0,0.000000,1.018463,0.053603,2.572960,35.110185,29.160214,3.055390,1.286480,0.053603,0.964860,1.554497,2.358547,1.125670,0.375223,0.375223,0.0,0.034424,0.034735,0.113216
3,796,Defender,M. Peersman,FC Groningen,26,1814,2,4.0,0,0,0.2082,0.208,1.2633,36,91,22,40,1,123,1041,831,114,26,2,10,0.0,0.000000,0.099228,2,0.099228,0.198456,0.000000,6.102536,51.648291,41.229327,5.656009,1.289967,0.099228,0.496141,1.786108,4.514884,1.091510,1.984564,0.049614,0.0,0.010330,0.010320,0.062678
4,797,Defender,I. Pinto,Fortuna Sittard,31,2514,3,5.0,1,0,0.2480,0.248,4.4972,50,76,24,16,1,91,931,682,187,95,2,26,0.0,0.000000,0.107399,3,0.107399,0.178998,0.035800,3.257757,33.329356,24.415274,6.694511,3.400955,0.071599,0.930788,1.789976,2.720764,0.859189,0.572792,0.035800,0.0,0.008878,0.008878,0.160998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,1110,Midfielder,IAI. Ahmed,SC Heerenveen,13,8,0,0.0,0,0,0.0000,0.000,0.0000,1,0,0,0,0,1,4,2,0,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,11.250000,45.000000,22.500000,0.000000,0.000000,0.000000,0.000000,11.250000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
318,1111,Midfielder,SSS. Steur,AFC Ajax,3,10,0,0.0,0,0,0.0000,0.000,0.0000,0,2,0,0,0,1,3,2,0,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,9.000000,27.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
319,1112,Midfielder,D. van der Werff,FC Groningen,18,22,0,2.0,1,0,0.2031,0.203,0.1576,0,0,0,0,1,0,5,5,0,2,0,1,0.0,0.000000,0.000000,0,0.000000,8.181818,4.090909,0.000000,20.454545,20.454545,0.000000,8.181818,0.000000,4.090909,0.000000,0.000000,0.000000,0.000000,4.090909,0.0,0.830864,0.830455,0.644727
320,1113,Midfielder,GRG. Reiziger,PEC Zwolle,4,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,1114,Midfielder,L. Tunjić,Fortuna Sittard,31,481,1,9.0,3,1,0.7644,0.790,0.6068,7,4,4,7,2,25,124,101,9,28,0,12,0.0,0.187110,0.187110,2,0.374220,1.683992,0.561331,4.677755,23.201663,18.898129,1.683992,5.239085,0.000000,2.245322,1.309771,0.748441,0.748441,1.309771,0.374220,0.0,0.143027,0.147817,0.113538

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,793,Defender,N. Viergever,FC Utrecht,33,2951,1,14.0,7,3,3.50,3.49,1.50,52,159,28,53,1,120,1818,1569,180,2,1,7,0.0,0.09,0.03,4,0.12,0.43,0.21,3.66,55.45,47.85,5.49,0.06,0.03,0.21,1.59,4.85,0.85,1.62,0.03,0.0,0.11,0.11,0.05
1,794,Defender,B. Nuytinck,NEC Nijmegen,27,1699,0,13.0,4,1,1.13,1.13,0.62,27,120,16,59,3,96,1060,941,124,2,1,4,0.0,0.05,0.00,1,0.05,0.69,0.21,5.09,56.15,49.85,6.57,0.11,0.05,0.21,1.43,6.36,0.85,3.13,0.16,0.0,0.06,0.06,0.03
2,795,Defender,P. van Aanholt,Sparta Rotterdam,21,1679,0,19.0,1,0,0.64,0.65,2.11,29,44,21,7,7,48,655,544,57,24,1,18,0.0,0.00,0.00,0,0.00,1.02,0.05,2.57,35.11,29.16,3.06,1.29,0.05,0.96,1.55,2.36,1.13,0.38,0.38,0.0,0.03,0.03,0.11
3,796,Defender,M. Peersman,FC Groningen,26,1814,2,4.0,0,0,0.21,0.21,1.26,36,91,22,40,1,123,1041,831,114,26,2,10,0.0,0.00,0.10,2,0.10,0.20,0.00,6.10,51.65,41.23,5.66,1.29,0.10,0.50,1.79,4.51,1.09,1.98,0.05,0.0,0.01,0.01,0.06
4,797,Defender,I. Pinto,Fortuna Sittard,31,2514,3,5.0,1,0,0.25,0.25,4.50,50,76,24,16,1,91,931,682,187,95,2,26,0.0,0.00,0.11,3,0.11,0.18,0.04,3.26,33.33,24.42,6.69,3.40,0.07,0.93,1.79,2.72,0.86,0.57,0.04,0.0,0.01,0.01,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,1110,Midfielder,IAI. Ahmed,SC Heerenveen,13,8,0,0.0,0,0,0.00,0.00,0.00,1,0,0,0,0,1,4,2,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,11.25,45.00,22.50,0.00,0.00,0.00,0.00,11.25,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
318,1111,Midfielder,SSS. Steur,AFC Ajax,3,10,0,0.0,0,0,0.00,0.00,0.00,0,2,0,0,0,1,3,2,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,9.00,27.00,18.00,0.00,0.00,0.00,0.00,0.00,18.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
319,1112,Midfielder,D. van der Werff,FC Groningen,18,22,0,2.0,1,0,0.20,0.20,0.16,0,0,0,0,1,0,5,5,0,2,0,1,0.0,0.00,0.00,0,0.00,8.18,4.09,0.00,20.45,20.45,0.00,8.18,0.00,4.09,0.00,0.00,0.00,0.00,4.09,0.0,0.83,0.83,0.64
320,1113,Midfielder,GRG. Reiziger,PEC Zwolle,4,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
321,1114,Midfielder,L. Tunjić,Fortuna Sittard,31,481,1,9.0,3,1,0.76,0.79,0.61,7,4,4,7,2,25,124,101,9,28,0,12,0.0,0.19,0.19,2,0.37,1.68,0.56,4.68,23.20,18.90,1.68,5.24,0.00,2.25,1.31,0.75,0.75,1.31,0.37,0.0,0.14,0.15,0.11

Adding and moving "League" column

In [18]:
#label
leagueLabel = "Eredivisie"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,793,Defender,Eredivisie,N. Viergever,FC Utrecht,33,2951,1,14.0,7,3,3.50,3.49,1.50,52,159,28,53,1,120,1818,1569,180,2,1,7,0.0,0.09,0.03,4,0.12,0.43,0.21,3.66,55.45,47.85,5.49,0.06,0.03,0.21,1.59,4.85,0.85,1.62,0.03,0.0,0.11,0.11,0.05
1,794,Defender,Eredivisie,B. Nuytinck,NEC Nijmegen,27,1699,0,13.0,4,1,1.13,1.13,0.62,27,120,16,59,3,96,1060,941,124,2,1,4,0.0,0.05,0.00,1,0.05,0.69,0.21,5.09,56.15,49.85,6.57,0.11,0.05,0.21,1.43,6.36,0.85,3.13,0.16,0.0,0.06,0.06,0.03
2,795,Defender,Eredivisie,P. van Aanholt,Sparta Rotterdam,21,1679,0,19.0,1,0,0.64,0.65,2.11,29,44,21,7,7,48,655,544,57,24,1,18,0.0,0.00,0.00,0,0.00,1.02,0.05,2.57,35.11,29.16,3.06,1.29,0.05,0.96,1.55,2.36,1.13,0.38,0.38,0.0,0.03,0.03,0.11
3,796,Defender,Eredivisie,M. Peersman,FC Groningen,26,1814,2,4.0,0,0,0.21,0.21,1.26,36,91,22,40,1,123,1041,831,114,26,2,10,0.0,0.00,0.10,2,0.10,0.20,0.00,6.10,51.65,41.23,5.66,1.29,0.10,0.50,1.79,4.51,1.09,1.98,0.05,0.0,0.01,0.01,0.06
4,797,Defender,Eredivisie,I. Pinto,Fortuna Sittard,31,2514,3,5.0,1,0,0.25,0.25,4.50,50,76,24,16,1,91,931,682,187,95,2,26,0.0,0.00,0.11,3,0.11,0.18,0.04,3.26,33.33,24.42,6.69,3.40,0.07,0.93,1.79,2.72,0.86,0.57,0.04,0.0,0.01,0.01,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,1110,Midfielder,Eredivisie,IAI. Ahmed,SC Heerenveen,13,8,0,0.0,0,0,0.00,0.00,0.00,1,0,0,0,0,1,4,2,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,11.25,45.00,22.50,0.00,0.00,0.00,0.00,11.25,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
318,1111,Midfielder,Eredivisie,SSS. Steur,AFC Ajax,3,10,0,0.0,0,0,0.00,0.00,0.00,0,2,0,0,0,1,3,2,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,9.00,27.00,18.00,0.00,0.00,0.00,0.00,0.00,18.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
319,1112,Midfielder,Eredivisie,D. van der Werff,FC Groningen,18,22,0,2.0,1,0,0.20,0.20,0.16,0,0,0,0,1,0,5,5,0,2,0,1,0.0,0.00,0.00,0,0.00,8.18,4.09,0.00,20.45,20.45,0.00,8.18,0.00,4.09,0.00,0.00,0.00,0.00,4.09,0.0,0.83,0.83,0.64
320,1113,Midfielder,Eredivisie,GRG. Reiziger,PEC Zwolle,4,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
321,1114,Midfielder,Eredivisie,L. Tunjić,Fortuna Sittard,31,481,1,9.0,3,1,0.76,0.79,0.61,7,4,4,7,2,25,124,101,9,28,0,12,0.0,0.19,0.19,2,0.37,1.68,0.56,4.68,23.20,18.90,1.68,5.24,0.00,2.25,1.31,0.75,0.75,1.31,0.37,0.0,0.14,0.15,0.11

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/EREcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- EREcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- EREcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000
mean,943.467742,26.399194,1473.169355,1.568548,18.330645,6.552419,2.153226,1.977984,1.887016,1.652500,24.346774,39.592742,12.483871,22.572581,5.008065,70.399194,662.725806,538.625000,92.060484,27.758065,2.483871,14.455645,5.625000,0.148065,0.098871,3.721774,0.247258,1.222298,0.430444,4.465000,39.524879,32.013710,5.150403,1.801089,0.149798,0.945524,1.519435,2.192742,0.727258,1.393306,0.331855,0.280323,0.124194,0.120161,0.100968
std,94.727945,8.664105,877.640578,1.988667,18.856467,8.027614,3.233289,2.689104,2.493732,1.728247,21.235348,48.406840,12.835290,27.276860,5.592065,52.200078,520.222731,455.443202,135.977494,41.755772,3.182655,13.856920,21.959488,0.218410,0.132605,4.494622,0.281616,1.084361,0.469390,2.013441,15.638763,15.429867,5.278708,2.258684,0.172073,0.767134,0.998932,1.827240,0.554353,1.265631,0.366715,0.919140,0.148684,0.143372,0.086436
min,793.000000,1.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.020000,7.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,856.750000,23.000000,626.000000,0.000000,4.000000,1.000000,0.000000,0.210000,0.225000,0.385000,7.000000,8.000000,2.000000,6.000000,1.000000,25.750000,236.000000,185.250000,16.750000,2.000000,0.000000,3.750000,0.000000,0.000000,0.000000,1.000000,0.030000,0.427500,0.067500,3.480000,28.947500,20.330000,1.880000,0.167500,0.000000,0.365000,0.877500,0.787500,0.250000,0.547500,0.050000,0.000000,0.020000,0.020000,0.040000
50%,934.000000,29.000000,1467.000000,1.000000,13.000000,4.000000,1.000000,1.010000,1.030000,1.110000,21.500000,21.000000,8.000000,13.000000,3.000000,68.000000,574.500000,439.000000,49.000000,9.000000,1.000000,10.000000,0.000000,0.070000,0.060000,2.000000,0.180000,0.865000,0.270000,4.605000,36.810000,28.590000,3.700000,0.890000,0.100000,0.885000,1.410000,1.655000,0.710000,1.125000,0.220000,0.000000,0.060000,0.060000,0.080000
75%,1030.250000,33.000000,2079.250000,2.000000,26.000000,9.000000,3.000000,2.730000,2.502500,2.340000,35.250000,47.500000,19.250000,31.000000,7.000000,99.000000,926.250000,732.000000,97.250000,37.000000,4.000000,23.000000,0.000000,0.190000,0.160000,5.000000,0.362500,1.852500,0.652500,5.572500,47.940000,39.717500,6.057500,2.725000,0.242500,1.355000,2.160000,3.010000,1.112500,1.852500,0.510000,0.000000,0.190000,0.160000,0.150000
max,1114.000000,38.000000,3450.000000,11.000000,98.000000,48.000000,27.000000,17.030000,14.420000,9.790000,114.000000,256.000000,63.000000,233.000000,26.000000,300.000000,2892.000000,2614.000000,890.000000,291.000000,15.000000,76.000000,140.000000,1.450000,1.200000,34.000000,1.710000,6.000000,3.000000,11.520000,93.750000,85.810000,26.250000,15.000000,0.760000,4.800000,5.180000,8.970000,2.430000,7.730000,3.000000,5.670000,0.780000,0.780000,0.480000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/EREcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000
mean,956.000000,22.740061,1120.975535,1.195719,14.000000,4.996942,1.633028,1.508287,1.439021,1.256575,18.568807,30.110092,9.489297,17.189602,3.831804,53.642202,504.223242,409.788991,69.990826,21.146789,1.889908,11.012232,4.272171,0.112294,0.084465,2.828746,0.197003,1.464954,0.565535,4.047278,34.613089,27.851804,4.542844,1.595076,0.148563,0.920367,1.441774,1.883823,0.604771,1.238960,0.407431,0.291223,0.150612,0.147278,0.083700
std,94.540996,11.308679,987.078207,1.854752,18.127869,7.515015,2.961907,2.485548,2.312522,1.660499,21.143115,45.373570,12.372753,25.596218,5.299540,54.310602,533.095540,457.660188,124.674877,38.198342,2.965050,13.524569,19.264925,0.200430,0.169488,4.221770,0.287734,3.378513,2.633668,2.946190,21.096719,18.626608,6.083861,2.524741,0.532865,1.905960,1.610042,2.183624,0.710343,1.620403,1.385844,1.625552,0.612349,0.611254,0.094415
min,793.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,874.500000,15.000000,93.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,4.000000,46.500000,35.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.145000,22.525000,16.275000,0.675000,0.000000,0.000000,0.000000,0.000000,0.340000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,956.000000,26.000000,1085.000000,0.000000,7.000000,2.000000,0.000000,0.550000,0.570000,0.550000,11.000000,12.000000,4.000000,8.000000,2.000000,40.000000,369.000000,290.000000,25.000000,4.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.080000,0.730000,0.160000,4.250000,34.160000,25.870000,2.940000,0.450000,0.030000,0.560000,1.200000,1.240000,0.450000,0.780000,0.150000,0.000000,0.050000,0.050000,0.060000
75%,1037.500000,32.000000,1905.500000,2.000000,20.500000,7.000000,2.000000,1.845000,1.705000,1.790000,29.000000,35.500000,15.000000,22.500000,6.000000,87.500000,782.000000,630.500000,78.000000,24.000000,2.000000,18.000000,0.000000,0.150000,0.120000,4.000000,0.305000,1.800000,0.560000,5.540000,45.720000,37.440000,5.360000,2.320000,0.180000,1.240000,2.070000,2.595000,1.000000,1.665000,0.450000,0.000000,0.155000,0.150000,0.135000
max,1119.000000,38.000000,3450.000000,11.000000,98.000000,48.000000,27.000000,17.030000,14.420000,9.790000,114.000000,256.000000,63.000000,233.000000,26.000000,300.000000,2892.000000,2614.000000,890.000000,291.000000,15.000000,76.000000,140.000000,1.450000,1.800000,34.000000,1.800000,45.000000,45.000000,17.310000,108.000000,92.200000,45.000000,18.000000,9.000000,30.000000,11.250000,18.000000,6.920000,13.850000,22.500000,25.710000,10.600000,10.600000,0.640000

In [27]:
#We can see that the 25% cutoff is 93
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 93].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000,245.000000
mean,943.400000,26.632653,1490.097959,1.587755,18.538776,6.620408,2.175510,2.000653,1.908531,1.671510,24.636735,40.048980,12.620408,22.832653,5.069388,71.224490,670.391837,544.844898,93.138776,28.085714,2.514286,14.620408,5.693878,0.145796,0.100082,3.763265,0.246204,1.220939,0.423469,4.483224,39.564245,32.034204,5.164571,1.810980,0.151633,0.944857,1.529959,2.191306,0.720000,1.394041,0.335918,0.283755,0.124163,0.120041,0.100980
std,94.547646,8.438043,869.445677,1.993188,18.875876,8.051499,3.246343,2.697617,2.501264,1.730174,21.201480,48.525446,12.853796,27.341356,5.598529,51.978899,518.728768,454.715179,136.456582,41.905397,3.190149,13.859911,22.085159,0.212439,0.132961,4.506038,0.278313,1.070713,0.440917,2.016930,15.685249,15.471316,5.280807,2.268934,0.172320,0.755714,0.999131,1.828807,0.551539,1.269072,0.367101,0.924244,0.148271,0.142798,0.086611
min,793.000000,1.000000,94.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,37.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.020000,7.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,856.000000,23.000000,678.000000,0.000000,4.000000,1.000000,0.000000,0.230000,0.250000,0.400000,8.000000,9.000000,2.000000,6.000000,1.000000,26.000000,242.000000,187.000000,18.000000,3.000000,0.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.030000,0.440000,0.070000,3.540000,29.040000,20.330000,1.990000,0.170000,0.000000,0.380000,0.880000,0.790000,0.250000,0.550000,0.050000,0.000000,0.020000,0.020000,0.040000
50%,935.000000,29.000000,1472.000000,1.000000,13.000000,4.000000,1.000000,1.030000,1.030000,1.130000,22.000000,21.000000,8.000000,13.000000,3.000000,69.000000,585.000000,445.000000,49.000000,10.000000,1.000000,10.000000,0.000000,0.070000,0.070000,2.000000,0.180000,0.880000,0.270000,4.610000,36.590000,28.560000,3.700000,0.890000,0.100000,0.890000,1.410000,1.650000,0.710000,1.120000,0.230000,0.000000,0.060000,0.060000,0.080000
75%,1030.000000,33.000000,2083.000000,2.000000,26.000000,9.000000,3.000000,2.760000,2.570000,2.340000,36.000000,49.000000,20.000000,31.000000,7.000000,99.000000,927.000000,735.000000,98.000000,37.000000,4.000000,23.000000,0.000000,0.190000,0.160000,5.000000,0.360000,1.850000,0.650000,5.580000,47.970000,39.620000,6.000000,2.740000,0.250000,1.350000,2.190000,3.010000,1.110000,1.840000,0.510000,0.000000,0.190000,0.160000,0.150000
max,1114.000000,38.000000,3450.000000,11.000000,98.000000,48.000000,27.000000,17.030000,14.420000,9.790000,114.000000,256.000000,63.000000,233.000000,26.000000,300.000000,2892.000000,2614.000000,890.000000,291.000000,15.000000,76.000000,140.000000,1.450000,1.200000,34.000000,1.710000,6.000000,2.240000,11.520000,93.750000,85.810000,26.250000,15.000000,0.760000,4.800000,5.180000,8.970000,2.430000,7.730000,3.000000,5.670000,0.780000,0.780000,0.480000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/EREcomplete25.csv")