Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/laliga/LALIGAmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name               0
Team               0
Tackles            0
Clearances         0
Interceptions      0
aerialsWon         0
Blocks             0
Mins               0
duelsWon           0
unnamed          118
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,0.0
mean,30.966102,67.754237,17.906780,25.483051,2.254237,1558.042373,76.305085,NaN
std,24.756569,55.897791,14.102183,23.848788,2.605669,1009.276176,54.071417,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,12.000000,23.750000,6.250000,7.000000,0.000000,652.250000,29.500000,NaN
50%,26.000000,55.500000,14.000000,19.500000,2.000000,1574.500000,73.000000,NaN
75%,46.000000,102.750000,27.750000,36.750000,3.000000,2502.500000,115.500000,NaN
max,111.000000,221.000000,68.000000,131.000000,14.000000,3326.000000,204.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 1120)
dfDdef["ID"] = (dfDdef.index + 1120)
dfDatt["ID"] = (dfDatt.index + 1120)
dfDpas["ID"] = (dfDpas.index + 1120) #should end at id no 1237
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 1300
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 1336
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 1477
dfMdft.head(300) #to check final id number

            Name             Team  App  Mins    ID
0       Ó. Trejo   Rayo Vallecano   38   525  1337
1      D. Parejo       Villarreal   36  2277  1338
2      N. Gudelj          Sevilla   35  2495  1339
3       O. Romeu        Barcelona   30  1375  1340
4           Koke  Atlético Madrid   33  1927  1341
..           ...              ...  ...   ...   ...
136    M. Bernal        Barcelona    3   243  1473
137         OOso          Sevilla    4     0  1474
138   JSJ. Salas         Mallorca   15    44  1475
139  M. Domenech         Mallorca   22   305  1476
140   LNL. Núñez         Valencia    1     0  1477

[141 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/laliga/LALIGAdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/laliga/LALIGAforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/laliga/LALIGAgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/laliga/LALIGAmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,J. Navas,Sevilla,18,440,1120,0,3.0,2,1,0.5332,0.533,0.6074,5,5,4,6,0,18,209,174,18,33,0,10,Defender,NaN
1,C. Azpilicueta,Sevilla,31,877,1121,0,5.0,2,1,0.2415,0.241,0.3923,25,29,5,14,2,46,583,511,45,5,0,3,Defender,NaN
2,Ó. de Marcos,Athletic Club,37,1574,1122,4,8.0,2,0,0.9958,0.996,2.1882,32,31,16,8,1,49,759,602,95,55,6,19,Defender,NaN
3,K. Femenía,Getafe,30,2229,1123,1,3.0,0,0,0.3590,0.359,2.1206,50,55,40,6,1,85,1254,1134,71,47,3,16,Defender,NaN
4,D. Alaba,Real Madrid,12,316,1124,0,NaN,0,0,0.0000,NaN,0.0856,1,7,6,4,0,5,222,204,22,3,0,1,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,E. Camavinga,Real Madrid,20,1096,1415,2,8.0,2,1,0.4366,0.436,0.7006,42,19,18,22,4,108,761,677,43,2,1,11,Midfielder,NaN
296,J. Moncayola,Osasuna,33,2112,1416,0,21.0,9,0,1.6771,1.588,4.6134,70,19,11,15,4,98,874,701,106,107,4,34,Midfielder,NaN
297,R. Moro,Osasuna,33,2346,1417,5,46.0,16,4,4.1736,4.118,5.4804,22,19,10,8,16,103,611,445,64,149,8,44,Midfielder,NaN
298,B. Turrientes,Real Sociedad,34,939,1418,0,7.0,2,0,0.5512,0.551,0.3672,15,13,5,10,1,61,432,398,34,19,1,3,Midfielder,NaN
299,A. Oroz,Osasuna,37,2981,1419,4,48.0,16,5,4.1606,3.549,3.4769,35,10,20,19,18,166,1086,912,59,29,6,41,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,J. Navas,Sevilla,18,440,1120,0,3.0,2,1,0.5332,0.533,0.6074,5,5,4,6,0,18,209,174,18,33,0,10,Defender,0.0
1,C. Azpilicueta,Sevilla,31,877,1121,0,5.0,2,1,0.2415,0.241,0.3923,25,29,5,14,2,46,583,511,45,5,0,3,Defender,0.0
2,Ó. de Marcos,Athletic Club,37,1574,1122,4,8.0,2,0,0.9958,0.996,2.1882,32,31,16,8,1,49,759,602,95,55,6,19,Defender,0.0
3,K. Femenía,Getafe,30,2229,1123,1,3.0,0,0,0.3590,0.359,2.1206,50,55,40,6,1,85,1254,1134,71,47,3,16,Defender,0.0
4,D. Alaba,Real Madrid,12,316,1124,0,0.0,0,0,0.0000,0.000,0.0856,1,7,6,4,0,5,222,204,22,3,0,1,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,L. Yamal,Barcelona,35,2861,1468,13,144.0,47,9,9.8122,9.890,11.6123,42,3,16,1,46,264,1414,1116,62,108,28,65,Midfielder,0.0
349,Y. Enríquez,Deportivo Alavés,6,0,1469,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
350,P. Canales,Athletic Club,21,259,1470,0,3.0,0,0,0.1898,0.190,0.2333,3,2,1,0,1,10,97,85,5,16,1,6,Midfielder,0.0
351,M. Jauregizar,Athletic Club,36,2243,1471,1,21.0,8,2,1.0798,1.071,1.1621,84,34,29,35,5,180,1089,897,115,27,2,23,Midfielder,0.0
352,E. Buján,Athletic Club,3,10,1472,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,1,4,4,0,1,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,1120,Defender,J. Navas,Sevilla,18,440,0,3.0,2,1,0.5332,0.533,0.6074,5,5,4,6,0,18,209,174,18,33,0,10,0.0
1,1121,Defender,C. Azpilicueta,Sevilla,31,877,0,5.0,2,1,0.2415,0.241,0.3923,25,29,5,14,2,46,583,511,45,5,0,3,0.0
2,1122,Defender,Ó. de Marcos,Athletic Club,37,1574,4,8.0,2,0,0.9958,0.996,2.1882,32,31,16,8,1,49,759,602,95,55,6,19,0.0
3,1123,Defender,K. Femenía,Getafe,30,2229,1,3.0,0,0,0.3590,0.359,2.1206,50,55,40,6,1,85,1254,1134,71,47,3,16,0.0
4,1124,Defender,D. Alaba,Real Madrid,12,316,0,0.0,0,0,0.0000,0.000,0.0856,1,7,6,4,0,5,222,204,22,3,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1468,Midfielder,L. Yamal,Barcelona,35,2861,13,144.0,47,9,9.8122,9.890,11.6123,42,3,16,1,46,264,1414,1116,62,108,28,65,0.0
349,1469,Midfielder,Y. Enríquez,Deportivo Alavés,6,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
350,1470,Midfielder,P. Canales,Athletic Club,21,259,0,3.0,0,0,0.1898,0.190,0.2333,3,2,1,0,1,10,97,85,5,16,1,6,0.0
351,1471,Midfielder,M. Jauregizar,Athletic Club,36,2243,1,21.0,8,2,1.0798,1.071,1.1621,84,34,29,35,5,180,1089,897,115,27,2,23,0.0
352,1472,Midfielder,E. Buján,Athletic Club,3,10,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,1,4,4,0,1,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000
mean,1298.500000,27.991620,1418.935754,1.368715,18.089385,6.273743,2.086592,2.063863,1.829617,1.381924,23.502793,32.569832,11.756983,18.986034,4.583799,70.240223,626.444134,515.477654,74.142458,27.008380,2.578212,13.720670,3.670391
std,103.489935,10.891234,982.071186,1.954188,22.291872,9.187309,3.864771,3.445549,2.904996,1.818863,22.318141,42.632484,12.792445,23.686617,5.873786,56.625591,519.172749,453.772655,108.197244,40.672187,3.715857,15.787992,16.931325
min,1120.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1209.250000,24.000000,584.000000,0.000000,2.000000,0.000000,0.000000,0.126975,0.126000,0.106550,5.000000,5.000000,1.000000,4.000000,0.000000,17.250000,199.500000,148.000000,11.250000,1.000000,0.000000,1.000000,0.000000
50%,1298.500000,32.000000,1374.500000,1.000000,11.000000,3.000000,1.000000,0.870150,0.866000,0.731700,19.000000,16.000000,7.000000,11.000000,3.000000,69.000000,525.000000,404.500000,41.000000,10.000000,1.000000,8.500000,0.000000
75%,1387.750000,36.000000,2254.000000,2.000000,25.000000,8.000000,3.000000,2.326800,2.208750,1.903125,36.000000,42.000000,18.000000,27.000000,6.000000,109.750000,967.000000,793.250000,99.750000,36.750000,4.000000,20.000000,0.000000
max,1477.000000,38.000000,3420.000000,13.000000,161.000000,85.000000,31.000000,27.114900,23.962000,12.583900,111.000000,221.000000,68.000000,161.000000,46.000000,276.000000,2672.000000,2426.000000,826.000000,231.000000,28.000000,98.000000,145.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,1120,Defender,J. Navas,Sevilla,18,440,0,3.0,2,1,0.5332,0.533,0.6074,5,5,4,6,0,18,209,174,18,33,0,10,0.0,0.204545,0.000000,1,0.204545,0.613636,0.409091,3.681818,42.750000,35.590909,3.681818,6.750000,0.000000,2.045455,1.022727,1.022727,0.818182,1.227273,0.000000,0.0,0.109064,0.109023,0.124241
1,1121,Defender,C. Azpilicueta,Sevilla,31,877,0,5.0,2,1,0.2415,0.241,0.3923,25,29,5,14,2,46,583,511,45,5,0,3,0.0,0.102623,0.000000,1,0.102623,0.513113,0.205245,4.720639,59.828962,52.440137,4.618016,0.513113,0.000000,0.307868,2.565564,2.976055,0.513113,1.436716,0.205245,0.0,0.024783,0.024732,0.040259
2,1122,Defender,Ó. de Marcos,Athletic Club,37,1574,4,8.0,2,0,0.9958,0.996,2.1882,32,31,16,8,1,49,759,602,95,55,6,19,0.0,0.000000,0.228717,4,0.228717,0.457433,0.114358,2.801779,43.398983,34.421855,5.432020,3.144854,0.343075,1.086404,1.829733,1.772554,0.914867,0.457433,0.057179,0.0,0.056939,0.056950,0.125119
3,1123,Defender,K. Femenía,Getafe,30,2229,1,3.0,0,0,0.3590,0.359,2.1206,50,55,40,6,1,85,1254,1134,71,47,3,16,0.0,0.000000,0.040377,1,0.040377,0.121131,0.000000,3.432032,50.632571,45.787349,2.866756,1.897712,0.121131,0.646030,2.018843,2.220727,1.615074,0.242261,0.040377,0.0,0.014495,0.014495,0.085623
4,1124,Defender,D. Alaba,Real Madrid,12,316,0,0.0,0,0,0.0000,0.000,0.0856,1,7,6,4,0,5,222,204,22,3,0,1,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,1.424051,63.227848,58.101266,6.265823,0.854430,0.000000,0.284810,0.284810,1.993671,1.708861,1.139241,0.000000,0.0,0.000000,0.000000,0.024380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1468,Midfielder,L. Yamal,Barcelona,35,2861,13,144.0,47,9,9.8122,9.890,11.6123,42,3,16,1,46,264,1414,1116,62,108,28,65,0.0,0.283118,0.408948,22,0.692066,4.529885,1.478504,8.304789,44.480951,35.106606,1.950367,3.397413,0.880811,2.044740,1.321216,0.094373,0.503321,0.031458,1.447046,0.0,0.308668,0.311115,0.365294
349,1469,Midfielder,Y. Enríquez,Deportivo Alavés,6,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,1470,Midfielder,P. Canales,Athletic Club,21,259,0,3.0,0,0,0.1898,0.190,0.2333,3,2,1,0,1,10,97,85,5,16,1,6,0.0,0.000000,0.000000,0,0.000000,1.042471,0.000000,3.474903,33.706564,29.536680,1.737452,5.559846,0.347490,2.084942,1.042471,0.694981,0.347490,0.000000,0.347490,0.0,0.065954,0.066023,0.081069
351,1471,Midfielder,M. Jauregizar,Athletic Club,36,2243,1,21.0,8,2,1.0798,1.071,1.1621,84,34,29,35,5,180,1089,897,115,27,2,23,0.0,0.080250,0.040125,3,0.120374,0.842621,0.320999,7.222470,43.695943,35.991975,4.614356,1.083370,0.080250,0.922871,3.370486,1.364244,1.163620,1.404369,0.200624,0.0,0.043327,0.042974,0.046629
352,1472,Midfielder,E. Buján,Athletic Club,3,10,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,1,4,4,0,1,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,9.000000,36.000000,36.000000,0.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,1120,Defender,J. Navas,Sevilla,18,440,0,3.0,2,1,0.53,0.53,0.61,5,5,4,6,0,18,209,174,18,33,0,10,0.0,0.20,0.00,1,0.20,0.61,0.41,3.68,42.75,35.59,3.68,6.75,0.00,2.05,1.02,1.02,0.82,1.23,0.00,0.0,0.11,0.11,0.12
1,1121,Defender,C. Azpilicueta,Sevilla,31,877,0,5.0,2,1,0.24,0.24,0.39,25,29,5,14,2,46,583,511,45,5,0,3,0.0,0.10,0.00,1,0.10,0.51,0.21,4.72,59.83,52.44,4.62,0.51,0.00,0.31,2.57,2.98,0.51,1.44,0.21,0.0,0.02,0.02,0.04
2,1122,Defender,Ó. de Marcos,Athletic Club,37,1574,4,8.0,2,0,1.00,1.00,2.19,32,31,16,8,1,49,759,602,95,55,6,19,0.0,0.00,0.23,4,0.23,0.46,0.11,2.80,43.40,34.42,5.43,3.14,0.34,1.09,1.83,1.77,0.91,0.46,0.06,0.0,0.06,0.06,0.13
3,1123,Defender,K. Femenía,Getafe,30,2229,1,3.0,0,0,0.36,0.36,2.12,50,55,40,6,1,85,1254,1134,71,47,3,16,0.0,0.00,0.04,1,0.04,0.12,0.00,3.43,50.63,45.79,2.87,1.90,0.12,0.65,2.02,2.22,1.62,0.24,0.04,0.0,0.01,0.01,0.09
4,1124,Defender,D. Alaba,Real Madrid,12,316,0,0.0,0,0,0.00,0.00,0.09,1,7,6,4,0,5,222,204,22,3,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,1.42,63.23,58.10,6.27,0.85,0.00,0.28,0.28,1.99,1.71,1.14,0.00,0.0,0.00,0.00,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1468,Midfielder,L. Yamal,Barcelona,35,2861,13,144.0,47,9,9.81,9.89,11.61,42,3,16,1,46,264,1414,1116,62,108,28,65,0.0,0.28,0.41,22,0.69,4.53,1.48,8.30,44.48,35.11,1.95,3.40,0.88,2.04,1.32,0.09,0.50,0.03,1.45,0.0,0.31,0.31,0.37
349,1469,Midfielder,Y. Enríquez,Deportivo Alavés,6,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
350,1470,Midfielder,P. Canales,Athletic Club,21,259,0,3.0,0,0,0.19,0.19,0.23,3,2,1,0,1,10,97,85,5,16,1,6,0.0,0.00,0.00,0,0.00,1.04,0.00,3.47,33.71,29.54,1.74,5.56,0.35,2.08,1.04,0.69,0.35,0.00,0.35,0.0,0.07,0.07,0.08
351,1471,Midfielder,M. Jauregizar,Athletic Club,36,2243,1,21.0,8,2,1.08,1.07,1.16,84,34,29,35,5,180,1089,897,115,27,2,23,0.0,0.08,0.04,3,0.12,0.84,0.32,7.22,43.70,35.99,4.61,1.08,0.08,0.92,3.37,1.36,1.16,1.40,0.20,0.0,0.04,0.04,0.05
352,1472,Midfielder,E. Buján,Athletic Club,3,10,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,1,4,4,0,1,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,9.00,36.00,36.00,0.00,9.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00

Adding and moving "League" column

In [18]:
#label
leagueLabel = "LaLiga"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,1120,Defender,LaLiga,J. Navas,Sevilla,18,440,0,3.0,2,1,0.53,0.53,0.61,5,5,4,6,0,18,209,174,18,33,0,10,0.0,0.20,0.00,1,0.20,0.61,0.41,3.68,42.75,35.59,3.68,6.75,0.00,2.05,1.02,1.02,0.82,1.23,0.00,0.0,0.11,0.11,0.12
1,1121,Defender,LaLiga,C. Azpilicueta,Sevilla,31,877,0,5.0,2,1,0.24,0.24,0.39,25,29,5,14,2,46,583,511,45,5,0,3,0.0,0.10,0.00,1,0.10,0.51,0.21,4.72,59.83,52.44,4.62,0.51,0.00,0.31,2.57,2.98,0.51,1.44,0.21,0.0,0.02,0.02,0.04
2,1122,Defender,LaLiga,Ó. de Marcos,Athletic Club,37,1574,4,8.0,2,0,1.00,1.00,2.19,32,31,16,8,1,49,759,602,95,55,6,19,0.0,0.00,0.23,4,0.23,0.46,0.11,2.80,43.40,34.42,5.43,3.14,0.34,1.09,1.83,1.77,0.91,0.46,0.06,0.0,0.06,0.06,0.13
3,1123,Defender,LaLiga,K. Femenía,Getafe,30,2229,1,3.0,0,0,0.36,0.36,2.12,50,55,40,6,1,85,1254,1134,71,47,3,16,0.0,0.00,0.04,1,0.04,0.12,0.00,3.43,50.63,45.79,2.87,1.90,0.12,0.65,2.02,2.22,1.62,0.24,0.04,0.0,0.01,0.01,0.09
4,1124,Defender,LaLiga,D. Alaba,Real Madrid,12,316,0,0.0,0,0,0.00,0.00,0.09,1,7,6,4,0,5,222,204,22,3,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,1.42,63.23,58.10,6.27,0.85,0.00,0.28,0.28,1.99,1.71,1.14,0.00,0.0,0.00,0.00,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1468,Midfielder,LaLiga,L. Yamal,Barcelona,35,2861,13,144.0,47,9,9.81,9.89,11.61,42,3,16,1,46,264,1414,1116,62,108,28,65,0.0,0.28,0.41,22,0.69,4.53,1.48,8.30,44.48,35.11,1.95,3.40,0.88,2.04,1.32,0.09,0.50,0.03,1.45,0.0,0.31,0.31,0.37
349,1469,Midfielder,LaLiga,Y. Enríquez,Deportivo Alavés,6,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
350,1470,Midfielder,LaLiga,P. Canales,Athletic Club,21,259,0,3.0,0,0,0.19,0.19,0.23,3,2,1,0,1,10,97,85,5,16,1,6,0.0,0.00,0.00,0,0.00,1.04,0.00,3.47,33.71,29.54,1.74,5.56,0.35,2.08,1.04,0.69,0.35,0.00,0.35,0.0,0.07,0.07,0.08
351,1471,Midfielder,LaLiga,M. Jauregizar,Athletic Club,36,2243,1,21.0,8,2,1.08,1.07,1.16,84,34,29,35,5,180,1089,897,115,27,2,23,0.0,0.08,0.04,3,0.12,0.84,0.32,7.22,43.70,35.99,4.61,1.08,0.08,0.92,3.37,1.36,1.16,1.40,0.20,0.0,0.04,0.04,0.05
352,1472,Midfielder,LaLiga,E. Buján,Athletic Club,3,10,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,1,4,4,0,1,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,9.00,36.00,36.00,0.00,9.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/LALIGAcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000
mean,1293.304487,30.939103,1625.788462,1.567308,20.717949,7.185897,2.387821,2.362500,2.093878,1.580417,26.948718,37.342949,13.474359,21.733974,5.250000,80.471154,718.044872,590.871795,84.993590,30.932692,2.955128,15.727564,4.208333,0.127115,0.084359,3.955128,0.211314,1.171186,0.407244,4.535769,39.281955,32.353494,4.448205,1.771474,0.161026,0.882436,1.497212,1.992404,0.748494,1.223974,0.304327,0.228462,0.128622,0.115833,0.085833
std,104.224561,7.583584,879.185033,2.018075,22.724491,9.506339,4.053530,3.595529,3.023330,1.867612,21.886669,43.685749,12.837570,24.185704,6.010307,53.507452,493.848185,438.152695,111.885822,42.173032,3.838949,15.958330,18.077847,0.187031,0.100274,5.253500,0.239532,1.006131,0.438631,1.972541,15.566502,15.502316,4.343236,2.019598,0.176880,0.716788,0.903070,1.755265,0.558863,1.168262,0.311583,0.826267,0.155111,0.135397,0.081367
min,1120.000000,3.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,27.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.620000,7.220000,0.230000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1198.750000,29.000000,870.750000,0.000000,5.000000,1.000000,0.000000,0.345000,0.330000,0.310000,10.000000,9.000000,3.750000,6.000000,1.000000,37.750000,318.000000,252.500000,21.000000,3.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.750000,0.022500,0.417500,0.080000,3.590000,26.930000,20.067500,1.830000,0.180000,0.000000,0.320000,0.927500,0.760000,0.327500,0.477500,0.080000,0.000000,0.030000,0.027500,0.027500
50%,1292.500000,33.000000,1565.000000,1.000000,14.000000,4.000000,1.000000,1.080000,1.060000,0.930000,22.000000,20.000000,9.000000,14.000000,3.500000,77.000000,639.000000,511.500000,51.500000,14.000000,2.000000,11.000000,0.000000,0.060000,0.050000,2.000000,0.145000,0.890000,0.230000,4.540000,37.970000,30.520000,3.440000,1.025000,0.120000,0.745000,1.430000,1.270000,0.675000,0.975000,0.210000,0.000000,0.070000,0.070000,0.060000
75%,1386.250000,36.000000,2347.500000,2.000000,27.000000,9.000000,3.000000,2.535000,2.412500,2.102500,40.000000,48.250000,20.250000,29.000000,7.000000,114.500000,1040.750000,857.000000,105.250000,41.000000,4.000000,22.000000,0.000000,0.180000,0.130000,5.000000,0.292500,1.802500,0.640000,5.557500,48.235000,41.660000,5.492500,2.642500,0.222500,1.252500,2.045000,2.780000,1.090000,1.590000,0.452500,0.000000,0.180000,0.162500,0.122500
max,1476.000000,38.000000,3420.000000,13.000000,161.000000,85.000000,31.000000,27.110000,23.960000,12.580000,111.000000,221.000000,68.000000,161.000000,46.000000,276.000000,2672.000000,2426.000000,826.000000,231.000000,28.000000,98.000000,145.000000,1.150000,0.490000,34.000000,1.300000,4.970000,2.620000,15.740000,97.710000,92.940000,35.000000,10.090000,0.880000,3.540000,7.000000,8.000000,3.360000,11.090000,2.330000,5.710000,0.980000,0.930000,0.440000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/LALIGAcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000
mean,1298.500000,27.991620,1418.935754,1.368715,18.089385,6.273743,2.086592,2.063771,1.829693,1.381899,23.502793,32.569832,11.756983,18.986034,4.583799,70.240223,626.444134,515.477654,74.142458,27.008380,2.578212,13.720670,3.670391,0.119804,0.078268,3.455307,0.197933,1.078883,0.372933,4.178575,35.836508,29.437179,4.013603,1.718659,0.145084,0.794832,1.334944,1.812793,0.676201,1.152933,0.280978,0.204693,0.121117,0.110028,0.084050
std,103.489935,10.891234,982.071186,1.954188,22.291872,9.187309,3.864771,3.445391,2.905020,1.818757,22.318141,42.632484,12.792445,23.686617,5.873786,56.625591,519.172749,453.772655,108.197244,40.672187,3.715857,15.787992,16.931325,0.213261,0.130119,5.074455,0.270360,1.057573,0.483711,2.382005,18.402982,17.146595,4.375139,2.314163,0.192101,0.738420,1.004977,1.831384,0.597720,1.305749,0.374076,0.780738,0.166009,0.149619,0.102482
min,1120.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1209.250000,24.000000,584.000000,0.000000,2.000000,0.000000,0.000000,0.122500,0.130000,0.110000,5.000000,5.000000,1.000000,4.000000,0.000000,17.250000,199.500000,148.000000,11.250000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.232500,0.000000,3.175000,24.405000,17.242500,1.240000,0.052500,0.000000,0.132500,0.610000,0.540000,0.152500,0.360000,0.000000,0.000000,0.010000,0.010000,0.010000
50%,1298.500000,32.000000,1374.500000,1.000000,11.000000,3.000000,1.000000,0.870000,0.865000,0.730000,19.000000,16.000000,7.000000,11.000000,3.000000,69.000000,525.000000,404.500000,41.000000,10.000000,1.000000,8.500000,0.000000,0.030000,0.035000,2.000000,0.105000,0.790000,0.190000,4.380000,35.145000,28.630000,3.065000,0.850000,0.090000,0.630000,1.275000,1.155000,0.600000,0.875000,0.160000,0.000000,0.060000,0.050000,0.060000
75%,1387.750000,36.000000,2254.000000,2.000000,25.000000,8.000000,3.000000,2.327500,2.207500,1.900000,36.000000,42.000000,18.000000,27.000000,6.000000,109.750000,967.000000,793.250000,99.750000,36.750000,4.000000,20.000000,0.000000,0.160000,0.120000,4.000000,0.277500,1.710000,0.590000,5.472500,46.792500,40.002500,5.357500,2.620000,0.210000,1.205000,1.970000,2.500000,1.050000,1.550000,0.410000,0.000000,0.157500,0.150000,0.120000
max,1477.000000,38.000000,3420.000000,13.000000,161.000000,85.000000,31.000000,27.110000,23.960000,12.580000,111.000000,221.000000,68.000000,161.000000,46.000000,276.000000,2672.000000,2426.000000,826.000000,231.000000,28.000000,98.000000,145.000000,1.960000,1.700000,34.000000,1.960000,5.070000,3.910000,15.740000,97.710000,92.940000,35.000000,22.500000,1.700000,3.540000,7.000000,11.250000,3.360000,12.270000,4.090000,5.710000,1.050000,1.050000,1.020000

In [27]:
#We can see that the 25% cutoff is 584
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 584].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,1293.294776,32.347015,1837.335821,1.772388,23.529851,8.164179,2.723881,2.696045,2.386754,1.791567,30.544776,42.335821,15.220149,24.597015,5.940299,91.067164,812.414179,668.779851,95.988806,34.723881,3.365672,17.787313,4.686567,0.134254,0.087687,4.496269,0.221754,1.200448,0.416828,4.600261,39.616381,32.713022,4.332910,1.708582,0.169664,0.900448,1.518470,1.995896,0.726679,1.240373,0.305224,0.193694,0.136119,0.122015,0.088545
std,103.514346,5.767248,760.214793,2.094326,23.294947,9.902668,4.271483,3.771984,3.163426,1.926886,21.509380,45.137649,13.009074,24.892012,6.188985,50.112338,468.081578,423.137735,116.773268,44.186681,3.984128,16.257396,19.417903,0.185756,0.096282,5.468670,0.238496,0.999010,0.437565,1.891324,15.571151,15.435979,3.814507,1.848363,0.174706,0.703638,0.811776,1.761638,0.483048,1.183858,0.272360,0.742604,0.160675,0.140026,0.078933
min,1121.000000,8.000000,587.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,112.000000,80.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060000,12.620000,7.220000,0.230000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1196.750000,30.000000,1216.750000,0.000000,8.000000,2.000000,0.000000,0.497500,0.480000,0.522500,15.000000,11.000000,5.000000,8.000000,2.000000,54.000000,431.750000,342.000000,28.000000,5.000000,1.000000,6.000000,0.000000,0.000000,0.000000,1.000000,0.050000,0.450000,0.100000,3.712500,27.600000,20.597500,1.867500,0.237500,0.050000,0.367500,1.025000,0.750000,0.337500,0.500000,0.100000,0.000000,0.030000,0.030000,0.030000
50%,1290.000000,34.000000,1825.000000,1.000000,17.500000,5.000000,1.000000,1.515000,1.470000,1.200000,25.500000,25.000000,12.000000,17.000000,4.000000,86.000000,760.000000,593.000000,62.000000,18.000000,2.000000,14.000000,0.000000,0.070000,0.070000,3.000000,0.150000,0.905000,0.250000,4.555000,38.335000,31.245000,3.470000,1.030000,0.120000,0.750000,1.480000,1.300000,0.665000,1.015000,0.210000,0.000000,0.070000,0.070000,0.070000
75%,1385.250000,36.000000,2513.000000,3.000000,31.250000,11.000000,4.000000,3.347500,3.045000,2.260000,43.250000,54.250000,22.000000,31.250000,8.000000,122.250000,1105.000000,913.750000,119.500000,49.000000,4.250000,24.000000,0.000000,0.182500,0.130000,6.000000,0.312500,1.802500,0.642500,5.522500,48.540000,41.660000,5.452500,2.620000,0.222500,1.245000,2.065000,2.785000,1.072500,1.592500,0.460000,0.000000,0.190000,0.182500,0.130000
max,1471.000000,38.000000,3420.000000,13.000000,161.000000,85.000000,31.000000,27.110000,23.960000,12.580000,111.000000,221.000000,68.000000,161.000000,46.000000,276.000000,2672.000000,2426.000000,826.000000,231.000000,28.000000,98.000000,145.000000,1.150000,0.490000,34.000000,1.300000,4.970000,2.620000,15.740000,97.710000,92.940000,24.440000,9.620000,0.880000,3.540000,4.390000,8.000000,2.200000,11.090000,1.450000,5.710000,0.980000,0.930000,0.440000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/LALIGAcomplete25.csv")