Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1defenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1defenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1defenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1defenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1forwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1forwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1forwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1forwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1goalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1goalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1goalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1goalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1goalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1midfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1midfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1midfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/ligue1/L1midfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          96
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,0.0
mean,27.395833,51.677083,15.781250,19.218750,1.770833,1245.031250,62.312500,NaN
std,21.167243,45.631590,13.025645,17.139799,2.804054,911.463398,45.078718,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,7.750000,12.750000,4.000000,4.000000,0.000000,300.000000,17.500000,NaN
50%,26.500000,50.000000,14.000000,15.000000,1.000000,1233.500000,60.000000,NaN
75%,42.500000,73.250000,27.000000,29.500000,2.000000,2021.000000,100.750000,NaN
max,75.000000,195.000000,48.000000,64.000000,16.000000,3060.000000,169.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 2075)
dfDdef["ID"] = (dfDdef.index + 2075)
dfDatt["ID"] = (dfDatt.index + 2075)
dfDpas["ID"] = (dfDpas.index + 2075) #should end at id no 2170
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 2230
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 2256
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 2340
dfMdft.head(300) #to check final id number

                Name                    Team  App  Mins    ID
0        F. Coquelin                  Nantes    6   232  2257
1           B. André                   Lille   30  2693  2258
2         R. Cabella                  Nantes   27  1032  2259
3       G. Kondogbia  Olympique de Marseille   25  2021  2260
4       B. Stambouli                    Metz    3   227  2261
..               ...                     ...  ...   ...   ...
79  SES. El Mourabet           RC Strasbourg   12     0  2336
80     TCT. Chennahi             Montpellier   23   184  2337
81        G. Yassine           RC Strasbourg    2    82  2338
82        ABA. Bamba               AS Monaco    1     0  2339
83     AOA. Ouattara           RC Strasbourg   11   161  2340

[84 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/ligue1/L1defender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/ligue1/L1forward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/ligue1/L1goalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/ligue1/L1midfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,Dante,Nice,26,1966,2075,0,9.0,2,0,0.4636,0.472,0.4940,32,71,34,41,3,93,1423,1263,143,2,0,4,Defender,NaN
1,I. Traoré,Metz,3,0,2076,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Defender,NaN
2,S. Umtiti,Lille,3,0,2077,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Defender,NaN
3,N. Pallois,Stade de Reims,32,2020,2078,2,3.0,1,0,0.4244,0.432,0.3679,61,155,28,20,0,95,843,707,138,7,1,3,Defender,NaN
4,A. Bamba,Angers,31,1520,2079,0,1.0,0,0,0.0818,0.088,0.2700,22,76,19,11,0,42,560,502,55,5,0,6,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,SES. El Mourabet,RC Strasbourg,12,0,2336,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
262,TCT. Chennahi,Montpellier,23,184,2337,0,2.0,0,0,0.1533,0.153,0.0203,6,6,2,1,2,9,53,48,1,2,0,1,Midfielder,NaN
263,G. Yassine,RC Strasbourg,2,82,2338,0,1.0,1,0,0.0000,NaN,0.0000,6,2,0,0,0,11,15,10,1,0,0,0,Midfielder,NaN
264,ABA. Bamba,AS Monaco,1,0,2339,0,NaN,0,0,0.0000,NaN,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
265,AOA. Ouattara,RC Strasbourg,11,161,2340,1,3.0,2,0,0.2083,0.208,0.0197,2,5,5,1,1,3,78,73,5,0,1,1,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,Dante,Nice,26,1966,2075,0,9.0,2,0,0.4636,0.472,0.4940,32,71,34,41,3,93,1423,1263,143,2,0,4,Defender,0.0
1,I. Traoré,Metz,3,0,2076,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Defender,0.0
2,S. Umtiti,Lille,3,0,2077,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Defender,0.0
3,N. Pallois,Stade de Reims,32,2020,2078,2,3.0,1,0,0.4244,0.432,0.3679,61,155,28,20,0,95,843,707,138,7,1,3,Defender,0.0
4,A. Bamba,Angers,31,1520,2079,0,1.0,0,0,0.0818,0.088,0.2700,22,76,19,11,0,42,560,502,55,5,0,6,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,D. Cissé,Stade Rennais,13,1074,2331,0,15.0,7,1,0.4328,0.433,0.6903,31,11,12,4,4,58,588,518,69,3,0,5,Midfielder,0.0
257,S. Mayulu,Paris Saint-Germain,29,811,2332,2,24.0,7,2,2.7685,2.919,2.0115,25,10,5,2,9,59,428,385,14,9,3,12,Midfielder,0.0
258,A. Sishuba,Montpellier,4,2,2333,0,0.0,0,0,0.0000,0.000,0.0000,1,0,0,0,0,1,0,0,0,0,0,0,Midfielder,0.0
259,A. Bouaddi,Lille,34,1154,2334,1,3.0,1,0,0.1243,0.125,1.2326,50,11,10,9,2,82,548,483,25,3,2,5,Midfielder,0.0
260,H. Makalou,Stade Brestois,8,40,2335,0,0.0,0,0,0.0000,0.000,0.0054,0,0,0,0,0,1,18,17,0,0,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,2075,Defender,Dante,Nice,26,1966,0,9.0,2,0,0.4636,0.472,0.4940,32,71,34,41,3,93,1423,1263,143,2,0,4,0.0
1,2076,Defender,I. Traoré,Metz,3,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
2,2077,Defender,S. Umtiti,Lille,3,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
3,2078,Defender,N. Pallois,Stade de Reims,32,2020,2,3.0,1,0,0.4244,0.432,0.3679,61,155,28,20,0,95,843,707,138,7,1,3,0.0
4,2079,Defender,A. Bamba,Angers,31,1520,0,1.0,0,0,0.0818,0.088,0.2700,22,76,19,11,0,42,560,502,55,5,0,6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,2331,Midfielder,D. Cissé,Stade Rennais,13,1074,0,15.0,7,1,0.4328,0.433,0.6903,31,11,12,4,4,58,588,518,69,3,0,5,0.0
257,2332,Midfielder,S. Mayulu,Paris Saint-Germain,29,811,2,24.0,7,2,2.7685,2.919,2.0115,25,10,5,2,9,59,428,385,14,9,3,12,0.0
258,2333,Midfielder,A. Sishuba,Montpellier,4,2,0,0.0,0,0,0.0000,0.000,0.0000,1,0,0,0,0,1,0,0,0,0,0,0,0.0
259,2334,Midfielder,A. Bouaddi,Lille,34,1154,1,3.0,1,0,0.1243,0.125,1.2326,50,11,10,9,2,82,548,483,25,3,2,5,0.0
260,2335,Midfielder,H. Makalou,Stade Brestois,8,40,0,0.0,0,0,0.0000,0.000,0.0054,0,0,0,0,0,1,18,17,0,0,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.00000,266.000000,266.000000,266.000000
mean,2207.500000,21.214286,1119.729323,1.161654,13.887218,5.180451,1.616541,1.693217,1.599932,1.249056,21.609023,26.112782,10.597744,13.157895,3.616541,55.142857,567.733083,485.236842,52.680451,18.93609,2.263158,10.751880,3.067669
std,76.931788,11.132612,914.430542,1.927016,17.737777,7.862339,2.914432,2.779254,2.644457,1.701775,21.320850,35.481519,11.895133,17.110007,4.924673,49.500775,575.449121,515.716955,79.475541,30.71131,3.506102,13.964865,16.267897
min,2075.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,2141.250000,11.000000,232.750000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.009625,2.000000,2.000000,1.000000,1.000000,0.000000,9.000000,89.250000,73.250000,4.000000,0.00000,0.000000,1.000000,0.000000
50%,2207.500000,26.000000,1042.000000,0.000000,7.000000,2.000000,0.000000,0.576950,0.590500,0.507950,17.500000,11.000000,6.000000,7.000000,2.000000,50.000000,423.000000,331.500000,24.000000,5.00000,1.000000,5.000000,0.000000
75%,2273.750000,31.000000,1910.500000,2.000000,21.000000,7.000000,2.000000,2.196650,2.152000,1.718575,36.000000,36.000000,18.000000,18.750000,5.000000,91.000000,921.750000,734.000000,69.000000,21.00000,3.000000,15.750000,0.000000
max,2340.000000,36.000000,3270.000000,10.000000,97.000000,51.000000,21.000000,16.611600,16.960000,7.825500,103.000000,195.000000,48.000000,133.000000,28.000000,255.000000,2866.000000,2658.000000,591.000000,194.00000,18.000000,67.000000,138.000000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2075,Defender,Dante,Nice,26,1966,0,9.0,2,0,0.4636,0.472,0.4940,32,71,34,41,3,93,1423,1263,143,2,0,4,0.0,0.000000,0.000000,0,0.000000,0.412004,0.091556,4.257375,65.142421,57.817904,6.546287,0.091556,0.000000,0.183113,1.464903,3.250254,1.556460,1.876907,0.137335,0.0,0.021223,0.021607,0.022614
1,2076,Defender,I. Traoré,Metz,3,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2077,Defender,S. Umtiti,Lille,3,0,0,0.0,0,0,0.0000,0.000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2078,Defender,N. Pallois,Stade de Reims,32,2020,2,3.0,1,0,0.4244,0.432,0.3679,61,155,28,20,0,95,843,707,138,7,1,3,0.0,0.000000,0.089109,2,0.089109,0.133663,0.044554,4.232673,37.559406,31.500000,6.148515,0.311881,0.044554,0.133663,2.717822,6.905941,1.247525,0.891089,0.000000,0.0,0.018909,0.019248,0.016392
4,2079,Defender,A. Bamba,Angers,31,1520,0,1.0,0,0,0.0818,0.088,0.2700,22,76,19,11,0,42,560,502,55,5,0,6,0.0,0.000000,0.000000,0,0.000000,0.059211,0.000000,2.486842,33.157895,29.723684,3.256579,0.296053,0.000000,0.355263,1.302632,4.500000,1.125000,0.651316,0.000000,0.0,0.004843,0.005211,0.015987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,2331,Midfielder,D. Cissé,Stade Rennais,13,1074,0,15.0,7,1,0.4328,0.433,0.6903,31,11,12,4,4,58,588,518,69,3,0,5,0.0,0.083799,0.000000,1,0.083799,1.256983,0.586592,4.860335,49.273743,43.407821,5.782123,0.251397,0.000000,0.418994,2.597765,0.921788,1.005587,0.335196,0.335196,0.0,0.036268,0.036285,0.057846
257,2332,Midfielder,S. Mayulu,Paris Saint-Germain,29,811,2,24.0,7,2,2.7685,2.919,2.0115,25,10,5,2,9,59,428,385,14,9,3,12,0.0,0.221948,0.221948,4,0.443896,2.663379,0.776819,6.547472,47.496917,42.725031,1.553637,0.998767,0.332922,1.331689,2.774353,1.109741,0.554871,0.221948,0.998767,0.0,0.307232,0.323933,0.223224
258,2333,Midfielder,A. Sishuba,Montpellier,4,2,0,0.0,0,0,0.0000,0.000,0.0000,1,0,0,0,0,1,0,0,0,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,45.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
259,2334,Midfielder,A. Bouaddi,Lille,34,1154,1,3.0,1,0,0.1243,0.125,1.2326,50,11,10,9,2,82,548,483,25,3,2,5,0.0,0.000000,0.077990,1,0.077990,0.233969,0.077990,6.395147,42.738302,37.668977,1.949740,0.233969,0.155979,0.389948,3.899480,0.857886,0.779896,0.701906,0.155979,0.0,0.009694,0.009749,0.096130
260,2335,Midfielder,H. Makalou,Stade Brestois,8,40,0,0.0,0,0,0.0000,0.000,0.0054,0,0,0,0,0,1,18,17,0,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,2.250000,40.500000,38.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.012150

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2075,Defender,Dante,Nice,26,1966,0,9.0,2,0,0.46,0.47,0.49,32,71,34,41,3,93,1423,1263,143,2,0,4,0.0,0.00,0.00,0,0.00,0.41,0.09,4.26,65.14,57.82,6.55,0.09,0.00,0.18,1.46,3.25,1.56,1.88,0.14,0.0,0.02,0.02,0.02
1,2076,Defender,I. Traoré,Metz,3,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
2,2077,Defender,S. Umtiti,Lille,3,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
3,2078,Defender,N. Pallois,Stade de Reims,32,2020,2,3.0,1,0,0.42,0.43,0.37,61,155,28,20,0,95,843,707,138,7,1,3,0.0,0.00,0.09,2,0.09,0.13,0.04,4.23,37.56,31.50,6.15,0.31,0.04,0.13,2.72,6.91,1.25,0.89,0.00,0.0,0.02,0.02,0.02
4,2079,Defender,A. Bamba,Angers,31,1520,0,1.0,0,0,0.08,0.09,0.27,22,76,19,11,0,42,560,502,55,5,0,6,0.0,0.00,0.00,0,0.00,0.06,0.00,2.49,33.16,29.72,3.26,0.30,0.00,0.36,1.30,4.50,1.12,0.65,0.00,0.0,0.00,0.01,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,2331,Midfielder,D. Cissé,Stade Rennais,13,1074,0,15.0,7,1,0.43,0.43,0.69,31,11,12,4,4,58,588,518,69,3,0,5,0.0,0.08,0.00,1,0.08,1.26,0.59,4.86,49.27,43.41,5.78,0.25,0.00,0.42,2.60,0.92,1.01,0.34,0.34,0.0,0.04,0.04,0.06
257,2332,Midfielder,S. Mayulu,Paris Saint-Germain,29,811,2,24.0,7,2,2.77,2.92,2.01,25,10,5,2,9,59,428,385,14,9,3,12,0.0,0.22,0.22,4,0.44,2.66,0.78,6.55,47.50,42.73,1.55,1.00,0.33,1.33,2.77,1.11,0.55,0.22,1.00,0.0,0.31,0.32,0.22
258,2333,Midfielder,A. Sishuba,Montpellier,4,2,0,0.0,0,0,0.00,0.00,0.00,1,0,0,0,0,1,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
259,2334,Midfielder,A. Bouaddi,Lille,34,1154,1,3.0,1,0,0.12,0.12,1.23,50,11,10,9,2,82,548,483,25,3,2,5,0.0,0.00,0.08,1,0.08,0.23,0.08,6.40,42.74,37.67,1.95,0.23,0.16,0.39,3.90,0.86,0.78,0.70,0.16,0.0,0.01,0.01,0.10
260,2335,Midfielder,H. Makalou,Stade Brestois,8,40,0,0.0,0,0,0.00,0.00,0.01,0,0,0,0,0,1,18,17,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,2.25,40.50,38.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.01

Adding and moving "League" column

In [18]:
#label
leagueLabel = "Ligue 1"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2075,Defender,Ligue 1,Dante,Nice,26,1966,0,9.0,2,0,0.46,0.47,0.49,32,71,34,41,3,93,1423,1263,143,2,0,4,0.0,0.00,0.00,0,0.00,0.41,0.09,4.26,65.14,57.82,6.55,0.09,0.00,0.18,1.46,3.25,1.56,1.88,0.14,0.0,0.02,0.02,0.02
1,2076,Defender,Ligue 1,I. Traoré,Metz,3,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
2,2077,Defender,Ligue 1,S. Umtiti,Lille,3,0,0,0.0,0,0,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
3,2078,Defender,Ligue 1,N. Pallois,Stade de Reims,32,2020,2,3.0,1,0,0.42,0.43,0.37,61,155,28,20,0,95,843,707,138,7,1,3,0.0,0.00,0.09,2,0.09,0.13,0.04,4.23,37.56,31.50,6.15,0.31,0.04,0.13,2.72,6.91,1.25,0.89,0.00,0.0,0.02,0.02,0.02
4,2079,Defender,Ligue 1,A. Bamba,Angers,31,1520,0,1.0,0,0,0.08,0.09,0.27,22,76,19,11,0,42,560,502,55,5,0,6,0.0,0.00,0.00,0,0.00,0.06,0.00,2.49,33.16,29.72,3.26,0.30,0.00,0.36,1.30,4.50,1.12,0.65,0.00,0.0,0.00,0.01,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,2331,Midfielder,Ligue 1,D. Cissé,Stade Rennais,13,1074,0,15.0,7,1,0.43,0.43,0.69,31,11,12,4,4,58,588,518,69,3,0,5,0.0,0.08,0.00,1,0.08,1.26,0.59,4.86,49.27,43.41,5.78,0.25,0.00,0.42,2.60,0.92,1.01,0.34,0.34,0.0,0.04,0.04,0.06
257,2332,Midfielder,Ligue 1,S. Mayulu,Paris Saint-Germain,29,811,2,24.0,7,2,2.77,2.92,2.01,25,10,5,2,9,59,428,385,14,9,3,12,0.0,0.22,0.22,4,0.44,2.66,0.78,6.55,47.50,42.73,1.55,1.00,0.33,1.33,2.77,1.11,0.55,0.22,1.00,0.0,0.31,0.32,0.22
258,2333,Midfielder,Ligue 1,A. Sishuba,Montpellier,4,2,0,0.0,0,0,0.00,0.00,0.00,1,0,0,0,0,1,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
259,2334,Midfielder,Ligue 1,A. Bouaddi,Lille,34,1154,1,3.0,1,0,0.12,0.12,1.23,50,11,10,9,2,82,548,483,25,3,2,5,0.0,0.00,0.08,1,0.08,0.23,0.08,6.40,42.74,37.67,1.95,0.23,0.16,0.39,3.90,0.86,0.78,0.70,0.16,0.0,0.01,0.01,0.10
260,2335,Midfielder,Ligue 1,H. Makalou,Stade Brestois,8,40,0,0.0,0,0,0.00,0.00,0.01,0,0,0,0,0,1,18,17,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,2.25,40.50,38.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.01

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/L1complete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000
mean,2204.259259,24.671296,1375.310185,1.430556,17.055556,6.361111,1.986111,2.083796,1.968843,1.534259,26.490741,32.074074,13.027778,16.148148,4.435185,67.657407,697.893519,596.537037,64.800926,23.273148,2.777778,13.212963,3.777778,0.133611,0.084491,3.416667,0.218611,1.176713,0.429259,4.534676,43.225185,36.713704,3.956991,1.551019,0.177407,0.849722,1.806204,2.000139,0.846435,1.030417,0.307130,0.254074,0.142546,0.136065,0.093519
std,76.968658,8.591955,825.463332,2.047072,18.278127,8.290043,3.120046,2.950443,2.809275,1.770246,20.798254,36.900042,11.950641,17.690788,5.127714,46.712214,563.533514,511.449203,83.664959,32.587120,3.705014,14.420625,17.985955,0.198152,0.111128,4.557896,0.261317,1.020000,0.486198,1.891761,17.862077,17.556491,3.484984,1.702923,0.225000,0.722330,1.054707,1.748770,0.588231,0.811062,0.324532,0.914537,0.183391,0.172365,0.090212
min,2075.000000,2.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.180000,10.080000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2135.750000,19.000000,656.000000,0.000000,4.000000,1.000000,0.000000,0.192500,0.192500,0.197500,8.750000,6.000000,3.000000,4.000000,0.750000,26.750000,238.500000,191.000000,12.750000,2.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.360000,0.040000,3.595000,30.435000,23.215000,1.502500,0.180000,0.000000,0.277500,1.087500,0.607500,0.407500,0.427500,0.022500,0.000000,0.020000,0.020000,0.020000
50%,2197.500000,27.500000,1279.000000,1.000000,11.000000,3.000000,1.000000,0.915000,0.905000,0.890000,23.000000,18.000000,9.000000,11.000000,3.000000,66.500000,554.500000,461.000000,40.000000,10.000000,1.000000,7.000000,0.000000,0.050000,0.035000,1.500000,0.100000,0.915000,0.260000,4.550000,40.940000,34.785000,3.120000,0.945000,0.100000,0.700000,1.775000,1.450000,0.805000,0.825000,0.220000,0.000000,0.065000,0.065000,0.070000
75%,2274.250000,31.000000,2028.000000,2.000000,24.250000,9.000000,3.000000,2.835000,2.390000,2.330000,40.250000,49.250000,21.000000,21.000000,7.000000,97.250000,1035.250000,857.250000,82.250000,31.000000,4.000000,18.250000,0.000000,0.212500,0.150000,5.000000,0.365000,1.842500,0.692500,5.602500,53.660000,45.935000,5.015000,2.545000,0.285000,1.350000,2.565000,2.812500,1.220000,1.392500,0.475000,0.000000,0.200000,0.200000,0.140000
max,2340.000000,36.000000,3270.000000,10.000000,97.000000,51.000000,21.000000,16.610000,16.960000,7.830000,103.000000,195.000000,48.000000,133.000000,28.000000,255.000000,2866.000000,2658.000000,591.000000,194.000000,18.000000,67.000000,138.000000,1.150000,0.560000,27.000000,1.400000,5.030000,2.720000,9.120000,104.640000,98.140000,21.000000,7.700000,1.530000,3.600000,5.950000,7.770000,2.800000,4.780000,1.910000,5.330000,1.160000,0.960000,0.440000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/L1complete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.00000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.00000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000
mean,2207.500000,21.214286,1119.729323,1.161654,13.887218,5.180451,1.616541,1.693120,1.599812,1.249135,21.609023,26.112782,10.597744,13.157895,3.616541,55.142857,567.733083,485.236842,52.680451,18.93609,2.263158,10.751880,3.067669,0.113609,0.068609,2.778195,0.182632,1.027444,0.378195,4.33015,37.944699,32.171541,3.322293,1.354549,0.155451,0.730752,1.864962,2.177293,0.757406,0.971992,0.276617,0.206316,0.117669,0.112406,0.082857
std,76.931788,11.132612,914.430542,1.927016,17.737777,7.862339,2.914432,2.779303,2.644531,1.701794,21.320850,35.481519,11.895133,17.110007,4.924673,49.500775,575.449121,515.716955,79.475541,30.71131,3.506102,13.964865,16.267897,0.201074,0.105419,4.315795,0.260491,1.054101,0.523014,3.53228,21.606940,20.350092,3.479276,1.691152,0.244897,0.773009,3.030263,5.837845,0.837772,1.096855,0.385781,0.829736,0.173618,0.163415,0.104889
min,2075.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2141.250000,11.000000,232.750000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.010000,2.000000,2.000000,1.000000,1.000000,0.000000,9.000000,89.250000,73.250000,4.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060000,0.000000,3.01000,23.612500,17.810000,0.742500,0.000000,0.000000,0.035000,0.670000,0.400000,0.032500,0.222500,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2207.500000,26.000000,1042.000000,0.000000,7.000000,2.000000,0.000000,0.575000,0.590000,0.510000,17.500000,11.000000,6.000000,7.000000,2.000000,50.000000,423.000000,331.500000,24.000000,5.00000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.070000,0.760000,0.165000,4.33500,38.230000,31.485000,2.605000,0.625000,0.040000,0.500000,1.565000,1.120000,0.685000,0.715000,0.145000,0.000000,0.050000,0.050000,0.050000
75%,2273.750000,31.000000,1910.500000,2.000000,21.000000,7.000000,2.000000,2.197500,2.150000,1.722500,36.000000,36.000000,18.000000,18.750000,5.000000,91.000000,921.750000,734.000000,69.000000,21.00000,3.000000,15.750000,0.000000,0.150000,0.120000,4.000000,0.295000,1.732500,0.600000,5.59000,50.537500,43.902500,4.780000,2.225000,0.237500,1.207500,2.517500,2.732500,1.127500,1.340000,0.417500,0.000000,0.177500,0.150000,0.120000
max,2340.000000,36.000000,3270.000000,10.000000,97.000000,51.000000,21.000000,16.610000,16.960000,7.830000,103.000000,195.000000,48.000000,133.000000,28.000000,255.000000,2866.000000,2658.000000,591.000000,194.00000,18.000000,67.000000,138.000000,1.360000,0.560000,27.000000,1.400000,5.030000,3.750000,45.00000,104.640000,98.140000,21.000000,7.700000,1.670000,3.600000,45.000000,90.000000,9.000000,9.000000,3.460000,5.330000,1.160000,0.960000,0.870000

In [27]:
#We can see that the 25% cutoff is 232.75, so we round up to 233
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 233].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000
mean,2202.477387,25.613065,1478.391960,1.542714,18.366834,6.869347,2.145729,2.246734,2.121508,1.661307,28.391960,34.492462,13.974874,17.381910,4.768844,72.698492,750.728643,641.834171,69.462312,25.085427,3.000000,14.251256,3.994975,0.140050,0.086935,3.688442,0.227538,1.206935,0.447739,4.559397,43.422362,36.945779,3.807035,1.591859,0.185276,0.880653,1.786080,1.996281,0.837186,1.047638,0.313467,0.207940,0.147487,0.140201,0.099648
std,77.345860,7.692055,777.189366,2.093022,18.451167,8.443096,3.199411,3.017485,2.874613,1.787747,20.548222,37.459725,11.972796,17.891787,5.201674,45.178429,555.934237,507.669798,85.523033,33.317993,3.776589,14.555612,18.711121,0.199526,0.106064,4.646430,0.260337,1.023003,0.489548,1.780766,18.150671,17.795726,3.209387,1.689248,0.226254,0.721537,0.988322,1.786117,0.560517,0.813992,0.317037,0.828502,0.184981,0.173252,0.090745
min,2075.000000,3.000000,235.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,58.000000,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,13.180000,10.080000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2133.500000,21.000000,865.000000,0.000000,5.000000,1.000000,0.000000,0.340000,0.365000,0.330000,11.500000,6.500000,4.000000,5.000000,1.000000,38.000000,301.000000,231.500000,15.000000,3.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.370000,0.080000,3.600000,30.390000,23.185000,1.490000,0.220000,0.000000,0.300000,1.095000,0.585000,0.410000,0.425000,0.055000,0.000000,0.025000,0.020000,0.030000
50%,2195.000000,28.000000,1417.000000,1.000000,12.000000,4.000000,1.000000,1.070000,0.980000,1.040000,25.000000,22.000000,11.000000,12.000000,3.000000,71.000000,624.000000,502.000000,44.000000,12.000000,2.000000,9.000000,0.000000,0.060000,0.040000,2.000000,0.130000,0.970000,0.270000,4.590000,41.050000,35.100000,3.120000,0.980000,0.110000,0.740000,1.760000,1.420000,0.800000,0.850000,0.230000,0.000000,0.070000,0.070000,0.080000
75%,2275.500000,31.000000,2059.500000,2.000000,26.000000,10.000000,3.000000,2.990000,2.830000,2.520000,41.500000,51.000000,22.000000,22.000000,7.000000,100.500000,1063.000000,904.500000,94.000000,33.000000,4.000000,20.500000,0.000000,0.220000,0.150000,5.000000,0.385000,1.855000,0.700000,5.545000,54.335000,47.960000,4.990000,2.650000,0.300000,1.365000,2.500000,2.825000,1.205000,1.400000,0.480000,0.000000,0.205000,0.200000,0.145000
max,2334.000000,36.000000,3270.000000,10.000000,97.000000,51.000000,21.000000,16.610000,16.960000,7.830000,103.000000,195.000000,48.000000,133.000000,28.000000,255.000000,2866.000000,2658.000000,591.000000,194.000000,18.000000,67.000000,138.000000,1.150000,0.410000,27.000000,1.400000,5.030000,2.720000,8.890000,104.640000,98.140000,17.610000,7.700000,1.530000,3.600000,5.180000,7.770000,2.620000,4.780000,1.910000,5.330000,1.160000,0.960000,0.440000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/L1complete25.csv")